// src/modules/casino-refactor/aggregator/dc/domain/index.ts
export * from './validation.exception';

// Exceptions
export {
  DcCallbackException,
  IncorrectTimeFormatException,
  IncorrectProviderException,
  IncorrectAmountException,
  CurrencyNotSupportedException,
  PlayerNotFoundException,
  NotLoggedInException,
  GameIdNotFoundException,
  BetRecordNotFoundException,
  BetRecordDuplicateException,
  BalanceInsufficientException,
  IncorrectBrandUidException,
  SystemErrorException,
  UnknownErrorException,
  SignErrorException,
  RequestParamErrorException,
  BrandNotExistException,
  CountryCodeErrorException,
  PlayerBlockedException,
  ApiInsufficientPermissionException,
  ProviderMaintainingException,
  BrandLockedException,
  NoSupportTryGameException,
  NoSupportGetReplayException,
  TokenCannotBeUsedException,
  UnsupportedMethodException,
  RequestRateLimitException,
  RequestDateRangeLimitException,
  FreeSpinIdNotFoundException,
  IncorrectRoundCountException,
  FreeSpinAlreadyCancelledException,
  FreeSpinAlreadyLockedException,
  ProviderNotSupportFreeSpinException,
  FreeSpinSetupErrorException,
} from './exception';

