/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  ErrorResponseDto,
  WhitecliffTestControllerGetBetResultsParams,
  WhitecliffTestControllerGetProductGameListBody,
  WhitecliffTestControllerGetPushedBetHistoryBody,
  WhitecliffTestControllerGetRefreshStatus200,
  WhitecliffTestControllerRefreshGameList200,
  WhitecliffTestControllerRefreshGameListBody
} from '../../models';

import { customInstance } from '../../axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary 베팅 결과 재확인 테스트
 */
export const whitecliffTestControllerGetBetResults = (
    params: MaybeRef<WhitecliffTestControllerGetBetResultsParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = unref(params);
      
      return customInstance<void>(
      {url: `/whitecliff/test/getBetResults`, method: 'GET',
        params: unref(params), signal
    },
      options);
    }
  



export const getWhitecliffTestControllerGetBetResultsQueryKey = (params?: MaybeRef<WhitecliffTestControllerGetBetResultsParams>,) => {
    return [
    'whitecliff','test','getBetResults', ...(params ? [params]: [])
    ] as const;
    }

    
export const getWhitecliffTestControllerGetBetResultsQueryOptions = <TData = Awaited<ReturnType<typeof whitecliffTestControllerGetBetResults>>, TError = ErrorResponseDto>(params: MaybeRef<WhitecliffTestControllerGetBetResultsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof whitecliffTestControllerGetBetResults>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getWhitecliffTestControllerGetBetResultsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof whitecliffTestControllerGetBetResults>>> = ({ signal }) => whitecliffTestControllerGetBetResults(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof whitecliffTestControllerGetBetResults>>, TError, TData> 
}

export type WhitecliffTestControllerGetBetResultsQueryResult = NonNullable<Awaited<ReturnType<typeof whitecliffTestControllerGetBetResults>>>
export type WhitecliffTestControllerGetBetResultsQueryError = ErrorResponseDto


/**
 * @summary 베팅 결과 재확인 테스트
 */

export function useWhitecliffTestControllerGetBetResults<TData = Awaited<ReturnType<typeof whitecliffTestControllerGetBetResults>>, TError = ErrorResponseDto>(
 params: MaybeRef<WhitecliffTestControllerGetBetResultsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof whitecliffTestControllerGetBetResults>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getWhitecliffTestControllerGetBetResultsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




/**
 * @summary 게임 리스트 조회 테스트
 */
export const whitecliffTestControllerGetProductGameList = (
    whitecliffTestControllerGetProductGameListBody: MaybeRef<WhitecliffTestControllerGetProductGameListBody>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      whitecliffTestControllerGetProductGameListBody = unref(whitecliffTestControllerGetProductGameListBody);
      
      return customInstance<void>(
      {url: `/whitecliff/test/getProductGameList`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: whitecliffTestControllerGetProductGameListBody, signal
    },
      options);
    }
  


export const getWhitecliffTestControllerGetProductGameListMutationOptions = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof whitecliffTestControllerGetProductGameList>>, TError,{data: WhitecliffTestControllerGetProductGameListBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof whitecliffTestControllerGetProductGameList>>, TError,{data: WhitecliffTestControllerGetProductGameListBody}, TContext> => {

const mutationKey = ['whitecliffTestControllerGetProductGameList'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof whitecliffTestControllerGetProductGameList>>, {data: WhitecliffTestControllerGetProductGameListBody}> = (props) => {
          const {data} = props ?? {};

          return  whitecliffTestControllerGetProductGameList(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type WhitecliffTestControllerGetProductGameListMutationResult = NonNullable<Awaited<ReturnType<typeof whitecliffTestControllerGetProductGameList>>>
    export type WhitecliffTestControllerGetProductGameListMutationBody = WhitecliffTestControllerGetProductGameListBody
    export type WhitecliffTestControllerGetProductGameListMutationError = ErrorResponseDto

    /**
 * @summary 게임 리스트 조회 테스트
 */
export const useWhitecliffTestControllerGetProductGameList = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof whitecliffTestControllerGetProductGameList>>, TError,{data: WhitecliffTestControllerGetProductGameListBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof whitecliffTestControllerGetProductGameList>>,
        TError,
        {data: WhitecliffTestControllerGetProductGameListBody},
        TContext
      > => {

      const mutationOptions = getWhitecliffTestControllerGetProductGameListMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary 푸시 베팅 내역 조회 테스트
 */
export const whitecliffTestControllerGetPushedBetHistory = (
    whitecliffTestControllerGetPushedBetHistoryBody: MaybeRef<WhitecliffTestControllerGetPushedBetHistoryBody>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      whitecliffTestControllerGetPushedBetHistoryBody = unref(whitecliffTestControllerGetPushedBetHistoryBody);
      
      return customInstance<void>(
      {url: `/whitecliff/test/getPushedBetHistory`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: whitecliffTestControllerGetPushedBetHistoryBody, signal
    },
      options);
    }
  


export const getWhitecliffTestControllerGetPushedBetHistoryMutationOptions = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof whitecliffTestControllerGetPushedBetHistory>>, TError,{data: WhitecliffTestControllerGetPushedBetHistoryBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof whitecliffTestControllerGetPushedBetHistory>>, TError,{data: WhitecliffTestControllerGetPushedBetHistoryBody}, TContext> => {

const mutationKey = ['whitecliffTestControllerGetPushedBetHistory'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof whitecliffTestControllerGetPushedBetHistory>>, {data: WhitecliffTestControllerGetPushedBetHistoryBody}> = (props) => {
          const {data} = props ?? {};

          return  whitecliffTestControllerGetPushedBetHistory(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type WhitecliffTestControllerGetPushedBetHistoryMutationResult = NonNullable<Awaited<ReturnType<typeof whitecliffTestControllerGetPushedBetHistory>>>
    export type WhitecliffTestControllerGetPushedBetHistoryMutationBody = WhitecliffTestControllerGetPushedBetHistoryBody
    export type WhitecliffTestControllerGetPushedBetHistoryMutationError = ErrorResponseDto

    /**
 * @summary 푸시 베팅 내역 조회 테스트
 */
export const useWhitecliffTestControllerGetPushedBetHistory = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof whitecliffTestControllerGetPushedBetHistory>>, TError,{data: WhitecliffTestControllerGetPushedBetHistoryBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof whitecliffTestControllerGetPushedBetHistory>>,
        TError,
        {data: WhitecliffTestControllerGetPushedBetHistoryBody},
        TContext
      > => {

      const mutationOptions = getWhitecliffTestControllerGetPushedBetHistoryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * mock2 데이터를 사용하여 게임 목록 갱신을 테스트합니다.
 * @summary [TEST] 게임 목록 갱신 테스트
 */
export const whitecliffTestControllerRefreshGameList = (
    whitecliffTestControllerRefreshGameListBody: MaybeRef<WhitecliffTestControllerRefreshGameListBody>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      whitecliffTestControllerRefreshGameListBody = unref(whitecliffTestControllerRefreshGameListBody);
      
      return customInstance<WhitecliffTestControllerRefreshGameList200>(
      {url: `/whitecliff/test/refresh-game-list`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: whitecliffTestControllerRefreshGameListBody, signal
    },
      options);
    }
  


export const getWhitecliffTestControllerRefreshGameListMutationOptions = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof whitecliffTestControllerRefreshGameList>>, TError,{data: WhitecliffTestControllerRefreshGameListBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof whitecliffTestControllerRefreshGameList>>, TError,{data: WhitecliffTestControllerRefreshGameListBody}, TContext> => {

const mutationKey = ['whitecliffTestControllerRefreshGameList'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof whitecliffTestControllerRefreshGameList>>, {data: WhitecliffTestControllerRefreshGameListBody}> = (props) => {
          const {data} = props ?? {};

          return  whitecliffTestControllerRefreshGameList(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type WhitecliffTestControllerRefreshGameListMutationResult = NonNullable<Awaited<ReturnType<typeof whitecliffTestControllerRefreshGameList>>>
    export type WhitecliffTestControllerRefreshGameListMutationBody = WhitecliffTestControllerRefreshGameListBody
    export type WhitecliffTestControllerRefreshGameListMutationError = ErrorResponseDto

    /**
 * @summary [TEST] 게임 목록 갱신 테스트
 */
export const useWhitecliffTestControllerRefreshGameList = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof whitecliffTestControllerRefreshGameList>>, TError,{data: WhitecliffTestControllerRefreshGameListBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof whitecliffTestControllerRefreshGameList>>,
        TError,
        {data: WhitecliffTestControllerRefreshGameListBody},
        TContext
      > => {

      const mutationOptions = getWhitecliffTestControllerRefreshGameListMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * 현재 게임 목록 갱신 진행 상태를 조회합니다.
 * @summary [TEST] 게임 목록 갱신 상태 조회
 */
export const whitecliffTestControllerGetRefreshStatus = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<WhitecliffTestControllerGetRefreshStatus200>(
      {url: `/whitecliff/test/refresh-status`, method: 'GET', signal
    },
      options);
    }
  



export const getWhitecliffTestControllerGetRefreshStatusQueryKey = () => {
    return [
    'whitecliff','test','refresh-status'
    ] as const;
    }

    
export const getWhitecliffTestControllerGetRefreshStatusQueryOptions = <TData = Awaited<ReturnType<typeof whitecliffTestControllerGetRefreshStatus>>, TError = ErrorResponseDto>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof whitecliffTestControllerGetRefreshStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getWhitecliffTestControllerGetRefreshStatusQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof whitecliffTestControllerGetRefreshStatus>>> = ({ signal }) => whitecliffTestControllerGetRefreshStatus(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof whitecliffTestControllerGetRefreshStatus>>, TError, TData> 
}

export type WhitecliffTestControllerGetRefreshStatusQueryResult = NonNullable<Awaited<ReturnType<typeof whitecliffTestControllerGetRefreshStatus>>>
export type WhitecliffTestControllerGetRefreshStatusQueryError = ErrorResponseDto


/**
 * @summary [TEST] 게임 목록 갱신 상태 조회
 */

export function useWhitecliffTestControllerGetRefreshStatus<TData = Awaited<ReturnType<typeof whitecliffTestControllerGetRefreshStatus>>, TError = ErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof whitecliffTestControllerGetRefreshStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getWhitecliffTestControllerGetRefreshStatusQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




