export enum ActivityType {
  ADMIN_LOGIN = 'ADMIN_LOGIN',
  ADMIN_LOGOUT = 'ADMIN_LOGOUT',
  USER_REGISTER = 'USER_REGISTER',
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',
  PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST',
  PASSWORD_RESET = 'PASSWORD_RESET',
  TOKEN_REFRESH = 'TOKEN_REFRESH',
  PROFILE_VIEW = 'PROFILE_VIEW',
  PROFILE_UPDATE = 'PROFILE_UPDATE',
  USER_COUNTRY_UPDATE = 'USER_COUNTRY_UPDATE',
  STATUS_CHANGE = 'STATUS_CHANGE',
  GAME_LAUNCH = 'GAME_LAUNCH',
  WHITECLIFF_USER_REGENERATED = 'WHITECLIFF_USER_REGENERATED',
  DEPOSIT_REQUEST = 'DEPOSIT_REQUEST',
  DEPOSIT_INVOICE_STATUS_CHECK = 'DEPOSIT_INVOICE_STATUS_CHECK',
  DEPOSIT_HISTORY_VIEW = 'DEPOSIT_HISTORY_VIEW',
  WITHDRAW_REQUEST = 'WITHDRAW_REQUEST',
  WITHDRAW_HISTORY_VIEW = 'WITHDRAW_HISTORY_VIEW',
  // 통화 관련 액션 타입 추가
  CURRENCY_LIST_VIEW = 'CURRENCY_LIST_VIEW',
  WALLET_ADDRESS_VALIDATION = 'WALLET_ADDRESS_VALIDATION',
  // 프로모션 관련
  PROMOTION_VIEW = 'PROMOTION_VIEW',
  PROMOTION_DETAIL_VIEW = 'PROMOTION_DETAIL_VIEW',
  PROMOTION_HISTORY_VIEW = 'PROMOTION_HISTORY_VIEW',
  PROMOTION_TRANSLATION_CREATE = 'PROMOTION_TRANSLATION_CREATE',
  PROMOTION_TRANSLATION_UPDATE = 'PROMOTION_TRANSLATION_UPDATE',
  PROMOTION_TRANSLATION_VIEW = 'PROMOTION_TRANSLATION_VIEW',

  // 레퍼럴 관련
  REFERRAL_CODE_CREATED = 'REFERRAL_CODE_CREATED',
  REFERRAL_CODE_DEACTIVATED = 'REFERRAL_CODE_DEACTIVATED',
  REFERRAL_BONUS_EARNED = 'REFERRAL_BONUS_EARNED',
  REFERRAL_BONUS_CLAIMED = 'REFERRAL_BONUS_CLAIMED',
  REFERRAL_LINKED = 'REFERRAL_LINKED', // 레퍼럴 관계 생성 (회원가입 시)

  // --- 입금 관련 (Deposit) ---
  ADMIN_DEPOSIT_APPROVE = 'ADMIN_DEPOSIT_APPROVE',
  ADMIN_DEPOSIT_REJECT = 'ADMIN_DEPOSIT_REJECT',
  ADMIN_DEPOSIT_LIST_VIEW = 'ADMIN_DEPOSIT_LIST_VIEW',
  ADMIN_DEPOSIT_DETAIL_VIEW = 'ADMIN_DEPOSIT_DETAIL_VIEW',

  // --- 어플리에이트 관련 (Affiliate) ---
  AFFILIATE_LINK_CREATE = 'AFFILIATE_LINK_CREATE',
  AFFILIATE_LINK_UPDATE = 'AFFILIATE_LINK_UPDATE',
  AFFILIATE_LINK_DELETE = 'AFFILIATE_LINK_DELETE',
  AFFILIATE_LINK_VIEW = 'AFFILIATE_LINK_VIEW',
  AFFILIATE_LINK_LIST_VIEW = 'AFFILIATE_LINK_LIST_VIEW',

  ADMIN_AFFILIATE_LINK_STATUS_TOGGLE = 'ADMIN_AFFILIATE_LINK_STATUS_TOGGLE',
  ADMIN_AFFILIATE_LINK_LIST_VIEW = 'ADMIN_AFFILIATE_LINK_LIST_VIEW',
  // 어플리에이트 코드 관련
  AFFILIATE_CODE_CREATE = 'AFFILIATE_CODE_CREATE',
  AFFILIATE_CODE_UPDATE = 'AFFILIATE_CODE_UPDATE',
  AFFILIATE_CODE_DELETE = 'AFFILIATE_CODE_DELETE',
  AFFILIATE_CODE_TOGGLE_ACTIVE = 'AFFILIATE_CODE_TOGGLE_ACTIVE',
  AFFILIATE_CODE_SET_DEFAULT = 'AFFILIATE_CODE_SET_DEFAULT',
  // 어플리에이트 커미션 관련
  COMMISSION_WITHDRAW = 'COMMISSION_WITHDRAW', // 커미션 출금
  COMMISSION_RATE_SET = 'COMMISSION_RATE_SET', // 수동 요율 설정
  COMMISSION_RATE_RESET = 'COMMISSION_RATE_RESET', // 수동 요율 해제

  // --- 시스템 관련 ---
  KOREAN_DETECTED_IN_API_RESPONSE = 'KOREAN_DETECTED_IN_API_RESPONSE',
}

export enum ActivityStatus {
  SUCCESS = 'SUCCESS',
  FAILURE = 'FAILURE',
}
export interface ActivityLogData {
  userId: bigint;
  isAdmin?: boolean; // 추가 (선택적)
  activityType: ActivityType;
  status: ActivityStatus;
  description: string;
  metadata?: Record<string, any>;
}
