packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - bcrypt
  - msgpackr-extract
  - prisma
  - protobufjs
  - puppeteer
  - unrs-resolver
