import { Inject, Injectable } from '@nestjs/common';
import { CHAT_ROOM_REPOSITORY_PORT, type ChatRoomRepositoryPort } from '../ports/chat-room.repository.port';
import { CHAT_ROOM_MEMBER_REPOSITORY_PORT, type ChatRoomMemberRepositoryPort } from '../ports/chat-room-member.repository.port';
import { ChatRoomNotFoundException, ChatRoomInactiveException, ChatRoomInsufficientTierException } from '../domain/chat-room.exception';
import { ChatRoomMember } from '../domain/chat-room-member.entity';
import { ChatMemberRole } from '@prisma/client';

export interface JoinChatRoomParams {
    roomId: bigint;
    userId: bigint;
    tierLevel: number;
}

@Injectable()
export class JoinChatRoomService {
    constructor(
        @Inject(CHAT_ROOM_REPOSITORY_PORT)
        private readonly roomRepository: ChatRoomRepositoryPort,
        @Inject(CHAT_ROOM_MEMBER_REPOSITORY_PORT)
        private readonly memberRepository: ChatRoomMemberRepositoryPort,
    ) { }

    async execute(params: JoinChatRoomParams): Promise<ChatRoomMember> {
        const room = await this.roomRepository.findById(params.roomId);

        if (!room) {
            throw new ChatRoomNotFoundException();
        }

        if (!room.isActive) {
            throw new ChatRoomInactiveException();
        }

        // Tier level check
        if (params.tierLevel < room.minTierLevel) {
            throw new ChatRoomInsufficientTierException(room.minTierLevel);
        }

        // Check if already a member
        const existingMember = await this.memberRepository.findByRoomIdAndUserId(params.roomId, params.userId);
        if (existingMember) {
            return existingMember;
        }

        // Create new member
        const newMember = new ChatRoomMember(
            0n, // ID will be auto-generated by DB
            params.roomId,
            params.userId,
            ChatMemberRole.MEMBER,
            null,
            new Date(),
        );

        return await this.memberRepository.save(newMember);
    }
}
