export enum MessageCode {
    // --- 결제 관련 (Payment) ---
    DEPOSIT_METHOD_NOT_AVAILABLE = 'DEPOSIT_METHOD_NOT_AVAILABLE', // 입금 방법을 사용할 수 없을 때
    DEPOSIT_REQUEST_ALREADY_EXISTS = 'DEPOSIT_REQUEST_ALREADY_EXISTS', // 이미 처리 중인 입금 요청이 있을 때
    WITHDRAW_REQUEST_ALREADY_EXISTS = 'WITHDRAW_REQUEST_ALREADY_EXISTS', // 이미 처리 중인 출금 요청이 있을 때
    DEPOSIT_NOT_FOUND = 'DEPOSIT_NOT_FOUND', // 입금 내역을 찾을 수 없을 때
    DEPOSIT_ALREADY_PROCESSED = 'DEPOSIT_ALREADY_PROCESSED', // 이미 처리된 입금 내역일 때
    DEPOSIT_INVALID_STATUS = 'DEPOSIT_INVALID_STATUS', // 입금 상태가 유효하지 않을 때
    DEPOSIT_INVALID_AMOUNT = 'DEPOSIT_INVALID_AMOUNT', // 입금 금액이 유효하지 않을 때
    DEPOSIT_AMOUNT_BELOW_MINIMUM = 'DEPOSIT_AMOUNT_BELOW_MINIMUM', // 입금 금액이 최소 금액보다 작을 때
    DEPOSIT_AMOUNT_EXCEEDS_MAXIMUM = 'DEPOSIT_AMOUNT_EXCEEDS_MAXIMUM', // 입금 금액이 최대 금액을 초과할 때
    DEPOSIT_UNAUTHORIZED_ACTION = 'DEPOSIT_UNAUTHORIZED_ACTION', // 승인되지 않은 입금 처리 액션일 때
    DEPOSIT_FIAT_NOT_IN_PROCESSING = 'DEPOSIT_FIAT_NOT_IN_PROCESSING', // 피아트 입금이 승인/거절 전 'PROCESSING' 상태가 아닐 때
    BANK_CONFIG_NOT_FOUND = 'BANK_CONFIG_NOT_FOUND', // 은행 설정을 찾을 수 없을 때
    BANK_CONFIG_INACTIVE = 'BANK_CONFIG_INACTIVE', // 은행 설정이 비활성화되어 있을 때
    CRYPTO_CONFIG_NOT_FOUND = 'CRYPTO_CONFIG_NOT_FOUND', // 암호화폐 설정을 찾을 수 없을 때
    CRYPTO_CONFIG_INACTIVE = 'CRYPTO_CONFIG_INACTIVE', // 암호화폐 설정이 비활성화되어 있을 때

    // --- 출금 관련 (Withdrawal) ---
    WITHDRAWAL_NOT_FOUND = 'WITHDRAWAL_NOT_FOUND', // 출금 내역을 찾을 수 없을 때
    WITHDRAWAL_INVALID_STATUS = 'WITHDRAWAL_INVALID_STATUS', // 출금 상태가 유효하지 않을 때
    WITHDRAWAL_AMOUNT_BELOW_MINIMUM = 'WITHDRAWAL_AMOUNT_BELOW_MINIMUM', // 출금 금액이 최소 금액보다 작을 때
    WITHDRAWAL_AMOUNT_EXCEEDS_MAXIMUM = 'WITHDRAWAL_AMOUNT_EXCEEDS_MAXIMUM', // 출금 금액이 최대 금액을 초과할 때
    WITHDRAWAL_PENDING_EXISTS = 'WITHDRAWAL_PENDING_EXISTS', // 이미 진행 중인 출금 요청이 있을 때
    WITHDRAWAL_PROCESSING_FAILED = 'WITHDRAWAL_PROCESSING_FAILED', // 출금 처리 중 오류가 발생했을 때
    INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE', // 잔액이 부족할 때

    // --- 인증 관련 (Authentication) ---
    AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN', // JWT 토큰이 유효하지 않을 때
    AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED', // JWT 토큰이 만료되었을 때
    AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS', // 로그인 정보(ID, 비밀번호)가 틀렸을 때
    AUTH_ACCOUNT_INACTIVE = 'AUTH_ACCOUNT_INACTIVE', // 사용자 계정이 비활성화 상태일 때
    AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED', // 로그인 실패
    AUTH_SESSION_NOT_FOUND = 'AUTH_SESSION_NOT_FOUND', // 세션을 찾을 수 없을 때
    AUTH_SESSION_NOT_OWNER = 'AUTH_SESSION_NOT_OWNER', // 세션 소유자가 아닐 때
    AUTH_MULTIPLE_LOGIN_NOT_ALLOWED = 'AUTH_MULTIPLE_LOGIN_NOT_ALLOWED', // 다중 로그인 제한
    AUTH_PASSWORD_MISMATCH = 'AUTH_PASSWORD_MISMATCH', // 비밀번호 불일치
    AUTH_PASSWORD_SAME_AS_OLD = 'AUTH_PASSWORD_SAME_AS_OLD', // 새 비밀번호가 이전과 같을 때

    // --- 권한 관련 (Authorization) ---
    AUTH_ALREADY_AUTHENTICATED_USERS_CANNOT_ACCESS_THIS_ENDPOINT = 'AUTH_ALREADY_AUTHENTICATED_USERS_CANNOT_ACCESS_THIS_ENDPOINT', // 이미 로그인한 사용자가 접근할 수 없는 엔드포인트(예: 로그인, 회원가입)에 접근 시
    AUTH_INSUFFICIENT_PERMISSIONS = 'AUTH_INSUFFICIENT_PERMISSIONS', // 특정 작업을 수행할 권한이 없을 때

    // --- 사용자 관련 (User) ---
    USER_NOT_FOUND = 'USER_NOT_FOUND', // 해당 사용자를 찾을 수 없을 때
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS', // 이미 존재하는 사용자(예: 이메일 중복)일 때
    USER_COUNTRY_ALREADY_SET = 'USER_COUNTRY_ALREADY_SET', // 사용자 국가가 이미 설정되어 있을 때
    USER_CONFIG_NOT_FOUND = 'USER_CONFIG_NOT_FOUND', // 사용자 설정을 찾을 수 없을 때

    // --- 인증 요구조건 관련 (Verification Requirements) ---
    PHONE_VERIFICATION_REQUIRED = 'PHONE_VERIFICATION_REQUIRED', // 휴대전화 인증이 필요할 때
    EMAIL_VERIFICATION_REQUIRED = 'EMAIL_VERIFICATION_REQUIRED', // 이메일 인증이 필요할 때
    IDENTITY_VERIFICATION_REQUIRED = 'IDENTITY_VERIFICATION_REQUIRED', // 본인인증(KYC)이 필요할 때

    // --- 데이터베이스 관련 (Database) ---
    DB_CONNECTION_ERROR = 'DB_CONNECTION_ERROR', // 데이터베이스 연결에 실패했을 때
    DB_QUERY_ERROR = 'DB_QUERY_ERROR', // 쿼리 실행 중 오류가 발생했을 때
    DB_CONSTRAINT_VIOLATION = 'DB_CONSTRAINT_VIOLATION', // 데이터베이스 제약 조건(예: Unique Key)을 위반했을 때

    // --- 일반 오류 (General Errors) ---
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR', // 예측하지 못한 서버 내부 오류가 발생했을 때
    VALIDATION_ERROR = 'VALIDATION_ERROR', // 요청 데이터의 유효성 검사에 실패했을 때 (예: DTO 검증)

    // --- 에이전트 관련 (Agent) ---
    USER_AGENT_CODE_NOT_FOUND = 'USER_AGENT_CODE_NOT_FOUND', // 요청의 User-Agent 정보를 식별할 수 없을 때

    // --- 큐 관련 (Queue) ---
    QUEUE_UNKNOWN_EMAIL_TYPE = 'QUEUE_UNKNOWN_EMAIL_TYPE', // 큐에서 정의되지 않은 이메일 타입을 처리하려고 할 때

    // --- 콤프 관련 (Comp) ---
    COMP_NOT_AVAILABLE_YET = 'COMP_NOT_AVAILABLE_YET', // 콤프가 아직 수령 가능하지 않을 때
    COMP_TRANSACTION_REVERSED = 'COMP_TRANSACTION_REVERSED', // 이미 취소된 트랜잭션일 때

    // Reward Errors
    REWARD_NOT_FOUND = 'REWARD_NOT_FOUND', // 보상을 찾을 수 없을 때
    REWARD_NOT_CLAIMABLE = 'REWARD_NOT_CLAIMABLE', // 해당 보상의 상태나 조건상 수령/변경을 할 수 없을 때
    COMP_ALREADY_CLAIMED = 'COMP_ALREADY_CLAIMED', // 이미 수령된 콤프일 때
    COMP_NOT_FOUND = 'COMP_NOT_FOUND', // 해당 날짜에 적립된 콤프가 없을 때
    COMP_NO_AMOUNT = 'COMP_NO_AMOUNT', // 수령할 콤프가 없을 때
    COMP_INSUFFICIENT_BALANCE = 'COMP_INSUFFICIENT_BALANCE', // 콤프 잔액이 부족할 때
    COMP_INVALID_PARAMETER = 'COMP_INVALID_PARAMETER', // 콤프 관련 파라미터가 유효하지 않을 때
    COMP_POLICY_VIOLATION = 'COMP_POLICY_VIOLATION', // 콤프 정책 위반일 때

    // --- 게임 관련 (Game) ---
    GAME_NOT_FOUND = 'GAME_NOT_FOUND', // 게임을 찾을 수 없을 때
    CASINO_AGGREGATOR_NOT_FOUND = 'CASINO_AGGREGATOR_NOT_FOUND', // 카지노 어그리게이터를 찾을 수 없을 때
    CASINO_AGGREGATOR_INACTIVE = 'CASINO_AGGREGATOR_INACTIVE', // 카지노 어그리게이터가 비활성 상태일 때
    CASINO_AGGREGATOR_MAINTENANCE = 'CASINO_AGGREGATOR_MAINTENANCE', // 카지노 어그리게이터가 점검 중일 때
    CASINO_GAME_PROVIDER_NOT_FOUND = 'CASINO_GAME_PROVIDER_NOT_FOUND', // 카지노 게임 프로바이더를 찾을 수 없을 때
    CASINO_CATEGORY_NOT_FOUND = 'CASINO_CATEGORY_NOT_FOUND', // 카지노 카테고리를 찾을 수 없을 때
    CASINO_CATEGORY_ALREADY_EXISTS = 'CASINO_CATEGORY_ALREADY_EXISTS', // 이미 존재하는 카지노 카테고리일 때

    // --- 통화 관련 (Currency) ---
    CURRENCY_UNSUPPORTED = 'CURRENCY_UNSUPPORTED', // 지원하지 않는 통화일 때
    CURRENCY_DISABLED = 'CURRENCY_DISABLED', // 비활성화된 통화일 때
    CURRENCY_INVALID_WALLET_FORMAT = 'CURRENCY_INVALID_WALLET_FORMAT', // 잘못된 지갑 주소 형식일 때
    CURRENCY_EXTRA_ID_REQUIRED = 'CURRENCY_EXTRA_ID_REQUIRED', // 추가 ID가 필요할 때
    CURRENCY_INVALID_EXTRA_ID_FORMAT = 'CURRENCY_INVALID_EXTRA_ID_FORMAT', // 잘못된 추가 ID 형식일 때

    // --- 잔액 관련 (Balance) ---
    USER_BALANCE_NOT_FOUND = 'USER_BALANCE_NOT_FOUND', // 사용자 잔액을 찾을 수 없을 때

    // --- VIP 관련 (VIP) ---
    VIP_LEVEL_NOT_FOUND = 'VIP_LEVEL_NOT_FOUND', // VIP 레벨을 찾을 수 없을 때

    // --- 티어 관련 (Tier) ---
    TIER_NOT_FOUND = 'TIER_NOT_FOUND', // 티어를 찾을 수 없을 때
    USER_TIER_NOT_FOUND = 'USER_TIER_NOT_FOUND', // 사용자 티어 정보를 찾을 수 없을 때
    TIER_INVALID_ROLLING_AMOUNT = 'TIER_INVALID_ROLLING_AMOUNT', // 유효하지 않은 롤링 금액일 때

    // --- 티어 보상 관련 ---
    TIER_REWARD_NOT_FOUND = 'TIER_REWARD_NOT_FOUND', // 티어 보상을 찾을 수 없을 때
    TIER_REWARD_NOT_PENDING = 'TIER_REWARD_NOT_PENDING', // 티어 보상이 대기 상태가 아닐 때
    TIER_REWARD_EXPIRED = 'TIER_REWARD_EXPIRED', // 티어 보상이 만료되었을 때
    TIER_REWARD_OWNER_MISMATCH = 'TIER_REWARD_OWNER_MISMATCH', // 티어 보상 소유자가 일치하지 않을 때

    // --- 롤링 관련 (Rolling) ---
    ROLLING_NOT_COMPLETED = 'ROLLING_NOT_COMPLETED', // 롤링 조건을 완료하지 않아 출금할 수 없을 때

    // --- 프로모션 관련 (Promotion) ---
    PROMOTION_NOT_FOUND = 'PROMOTION_NOT_FOUND', // 프로모션을 찾을 수 없을 때
    PROMOTION_TRANSLATION_NOT_FOUND = 'PROMOTION_TRANSLATION_NOT_FOUND', // 프로모션 번역을 찾을 수 없을 때
    PROMOTION_NOT_ACTIVE = 'PROMOTION_NOT_ACTIVE', // 프로모션이 활성 상태가 아닐 때
    PROMOTION_NOT_ELIGIBLE = 'PROMOTION_NOT_ELIGIBLE', // 프로모션 대상이 아닐 때
    PROMOTION_ALREADY_USED = 'PROMOTION_ALREADY_USED', // 이미 사용된 프로모션일 때

    // --- 쓰로틀링 관련 (Throttle) ---
    THROTTLE_TOO_MANY_REQUESTS = 'THROTTLE_TOO_MANY_REQUESTS', // 요청 한도 초과

    // 레퍼럴 관련
    REFERRAL_CODE_NOT_FOUND = 'REFERRAL_CODE_NOT_FOUND',
    REFERRAL_CODE_INVALID_FORMAT = 'REFERRAL_CODE_INVALID_FORMAT', // 레퍼럴 코드 형식이 올바르지 않을 때
    REFERRAL_CODE_LIMIT_EXCEEDED = 'REFERRAL_CODE_LIMIT_EXCEEDED', // 레퍼럴 코드 한도 초과
    REFERRAL_CODE_ALREADY_EXISTS = 'REFERRAL_CODE_ALREADY_EXISTS',
    REFERRAL_BONUS_NOT_FOUND = 'REFERRAL_BONUS_NOT_FOUND',
    REFERRAL_BONUS_ALREADY_CLAIMED = 'REFERRAL_BONUS_ALREADY_CLAIMED',
    REFERRAL_BONUS_INSUFFICIENT_AMOUNT = 'REFERRAL_BONUS_INSUFFICIENT_AMOUNT',
    REFERRAL_NOT_FOUND = 'REFERRAL_NOT_FOUND',
    REFERRAL_SELF_REFERRAL = 'REFERRAL_SELF_REFERRAL',
    REFERRAL_DUPLICATE = 'REFERRAL_DUPLICATE',
    REFERRAL_ACCESS_DENIED = 'REFERRAL_ACCESS_DENIED',
    REFERRAL_CODE_INACTIVE = 'REFERRAL_CODE_INACTIVE',
    REFERRAL_CODE_EXPIRED = 'REFERRAL_CODE_EXPIRED',
    REFERRAL_COMMISSION_NOT_FOUND = 'REFERRAL_COMMISSION_NOT_FOUND',
    REFERRAL_COMMISSION_INVALID_STATUS = 'REFERRAL_COMMISSION_INVALID_STATUS',
    REFERRAL_MILESTONE_NOT_FOUND = 'REFERRAL_MILESTONE_NOT_FOUND',
    REFERRAL_MILESTONE_ALREADY_CLAIMED = 'REFERRAL_MILESTONE_ALREADY_CLAIMED',
    REFERRAL_STATS_NOT_FOUND = 'REFERRAL_STATS_NOT_FOUND',

    // 커미션 관련
    COMMISSION_INVALID_RATE = 'COMMISSION_INVALID_RATE',
    COMMISSION_INSUFFICIENT_BALANCE = 'COMMISSION_INSUFFICIENT_BALANCE',
    COMMISSION_NOT_FOUND = 'COMMISSION_NOT_FOUND',
    COMMISSION_NOT_AVAILABLE = 'COMMISSION_NOT_AVAILABLE',
    COMMISSION_WALLET_NOT_FOUND = 'COMMISSION_WALLET_NOT_FOUND',
    COMMISSION_TIER_NOT_FOUND = 'COMMISSION_TIER_NOT_FOUND',
    COMMISSION_INVALID_CALCULATION = 'COMMISSION_INVALID_CALCULATION',
    COMMISSION_INVALID_SETTLEMENT_DATE = 'COMMISSION_INVALID_SETTLEMENT_DATE',
    COMMISSION_INVALID_WALLET_BALANCE = 'COMMISSION_INVALID_WALLET_BALANCE',
    COMMISSION_INVALID_PARAMETER = 'COMMISSION_INVALID_PARAMETER',
    COMMISSION_ACCESS_DENIED = 'COMMISSION_ACCESS_DENIED',

    // --- 언어 관련 (Language) ---
    INVALID_LANGUAGE_CODE = 'INVALID_LANGUAGE_CODE', // 지원하지 않는 언어 코드일 때
    INVALID_GAME_PROVIDER = 'INVALID_GAME_PROVIDER', // 지원하지 않는 게임 프로바이더일 때

    // --- DCS 관련 (DCS) ---
    NO_SUPPORT_GET_REPLAY = 'NO_SUPPORT_GET_REPLAY', // 리플레이 URL 조회 지원하지 않을 때

    // --- 비밀번호 관련 (Password) ---
    PASSWORD_RESET_TOKEN_INVALID = 'PASSWORD_RESET_TOKEN_INVALID', // 비밀번호 재설정 토큰이 유효하지 않을 때
    PASSWORD_SAME_AS_CURRENT = 'PASSWORD_SAME_AS_CURRENT', // 새 비밀번호와 현재 비밀번호가 같을 때
    NICKNAME_SAME_AS_CURRENT = 'NICKNAME_SAME_AS_CURRENT', // 새 닉네임과 현재 닉네임이 같을 때

    // --- 어플리에이트 관련 (Affiliate) ---
    AFFILIATE_LINK_LIMIT_EXCEEDED = 'AFFILIATE_LINK_LIMIT_EXCEEDED', // 레퍼럴 링크 최대 개수 초과
    AFFILIATE_CODE_ALREADY_EXISTS = 'AFFILIATE_CODE_ALREADY_EXISTS', // 이미 존재하는 레퍼럴 코드
    AFFILIATE_CODE_NOT_FOUND = 'AFFILIATE_CODE_NOT_FOUND', // 어플리에이트 코드를 찾을 수 없음
    AFFILIATE_CODE_LIMIT_EXCEEDED = 'AFFILIATE_CODE_LIMIT_EXCEEDED', // 어플리에이트 코드 최대 개수 초과
    AFFILIATE_CODE_CANNOT_DELETE = 'AFFILIATE_CODE_CANNOT_DELETE', // 어플리에이트 코드 삭제 불가 (기본 코드이면서 유일한 코드)
    AFFILIATE_CODE_INVALID_FORMAT = 'AFFILIATE_CODE_INVALID_FORMAT', // 어플리에이트 코드 형식이 올바르지 않음
    AFFILIATE_LINK_NOT_FOUND = 'AFFILIATE_LINK_NOT_FOUND', // 레퍼럴 링크를 찾을 수 없음
    AFFILIATE_DEFAULT_LINK_CANNOT_DELETE = 'AFFILIATE_DEFAULT_LINK_CANNOT_DELETE', // 기본 레퍼럴 링크는 삭제 불가
    AFFILIATE_CODE_DEFAULT_MUST_EXIST = 'AFFILIATE_CODE_DEFAULT_MUST_EXIST', // 기본 어플리에이트 코드는 반드시 하나 이상 존재해야 함
    AFFILIATE_CODE_DEFAULT_CANNOT_BE_INACTIVE = 'AFFILIATE_CODE_DEFAULT_CANNOT_BE_INACTIVE', // 기본 어플리에이트 코드는 비활성화할 수 없음

    // --- 롤링/와저링 관련 (Wagering/Rolling) ---
    WAGERING_NOT_FOUND = 'WAGERING_NOT_FOUND', // 롤링 조건을 찾을 수 없을 때
    WAGERING_INVALID_STATUS = 'WAGERING_INVALID_STATUS', // 유효하지 않은 롤링 상태일 때
    WAGERING_NOT_FORFEITABLE = 'WAGERING_NOT_FORFEITABLE', // 포기할 수 없는 롤링 조건일 때 (예: AML 입금 롤링)

    // --- 통계 관련 (Analytics) ---
    ANALYTICS_STATS_NOT_FOUND = 'ANALYTICS_STATS_NOT_FOUND',
    ANALYTICS_INVALID_PARAMETER = 'ANALYTICS_INVALID_PARAMETER',
    ANALYTICS_INVALID_DATE_RANGE = 'ANALYTICS_INVALID_DATE_RANGE',

    // --- Sqids 관련 ---
    SQID_INVALID_FORMAT = 'SQID_INVALID_FORMAT',
    SQID_INVALID_ID = 'SQID_INVALID_ID',

    // --- 알림 템플릿 관련 (Notification Template) ---
    NOTIFICATION_TEMPLATE_NOT_FOUND = 'NOTIFICATION_TEMPLATE_NOT_FOUND',
    NOTIFICATION_TEMPLATE_ALREADY_EXISTS = 'NOTIFICATION_TEMPLATE_ALREADY_EXISTS',
    NOTIFICATION_TEMPLATE_TRANSLATION_NOT_FOUND = 'NOTIFICATION_TEMPLATE_TRANSLATION_NOT_FOUND',

    // --- 알림 인박스 관련 (Notification Inbox) ---
    NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',
    NOTIFICATION_ALREADY_READ = 'NOTIFICATION_ALREADY_READ',
    NOTIFICATION_ALREADY_DELETED = 'NOTIFICATION_ALREADY_DELETED',
    NOTIFICATION_ACCESS_DENIED = 'NOTIFICATION_ACCESS_DENIED',

    // --- 알림 발송 관련 (Notification Alert) ---
    NOTIFICATION_ALERT_NOT_FOUND = 'NOTIFICATION_ALERT_NOT_FOUND',
    NOTIFICATION_ALERT_ALREADY_EXISTS = 'NOTIFICATION_ALERT_ALREADY_EXISTS',
    NOTIFICATION_ALERT_INVALID_STATUS_TRANSITION = 'NOTIFICATION_ALERT_INVALID_STATUS_TRANSITION',

    // --- 파일 관련 (File) ---
    FILE_NOT_FOUND = 'FILE_NOT_FOUND',
    FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED',
    FILE_REQUIRED = 'FILE_REQUIRED',
    FILE_INVALID_FORMAT = 'FILE_INVALID_FORMAT',
    FILE_SIZE_EXCEEDED = 'FILE_SIZE_EXCEEDED',
    FILE_EXTENSION_NOT_ALLOWED = 'FILE_EXTENSION_NOT_ALLOWED',
    FILE_POLICY_VIOLATION = 'FILE_POLICY_VIOLATION',

    // --- 회원가입 관련 (Signup) ---
    SIGNUP_DISABLED = 'SIGNUP_DISABLED', // 회원가입이 비활성화되었을 때
    SIGNUP_DAILY_LIMIT_EXCEEDED = 'SIGNUP_DAILY_LIMIT_EXCEEDED', // IP당 일일 가입 한도를 초과했을 때
    FORBIDDEN_WORD_NOT_FOUND = 'FORBIDDEN_WORD_NOT_FOUND', // 금지어를 찾을 수 없을 때
    FORBIDDEN_WORD_ALREADY_EXISTS = 'FORBIDDEN_WORD_ALREADY_EXISTS', // 이미 존재하는 금지어일 때

    // --- 관리자 메모 관련 (Admin Memo) ---
    ADMIN_MEMO_NOT_FOUND = 'ADMIN_MEMO_NOT_FOUND',
    ADMIN_MEMO_CONTENT_EMPTY = 'ADMIN_MEMO_CONTENT_EMPTY',

    // --- 채팅 관련 (Chat) ---
    CHAT_CONFIG_NOT_FOUND = 'CHAT_CONFIG_NOT_FOUND',
    CHAT_ROOM_NOT_FOUND = 'CHAT_ROOM_NOT_FOUND',
    CHAT_MESSAGE_TOO_LONG = 'CHAT_MESSAGE_TOO_LONG',
    CHAT_TICKET_NOT_FOUND = 'CHAT_TICKET_NOT_FOUND',
    CHAT_UNAUTHORIZED = 'CHAT_UNAUTHORIZED',
    CHAT_ROOM_LOCKED = 'CHAT_ROOM_LOCKED',
    CHAT_INSUFFICIENT_TIER = 'CHAT_INSUFFICIENT_TIER',
    CHAT_INVALID_FILE_TYPE = 'CHAT_INVALID_FILE_TYPE',
    CHAT_SUPPORT_INVALID_ACTION = 'CHAT_SUPPORT_INVALID_ACTION',
}

