"use client";

import React, { Suspense } from "react";
import { RefineContext } from "./_refine_context";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Refine</title>
        <meta name="description" content="Generated by create refine app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <Suspense>
          <RefineContext>{children}</RefineContext>
        </Suspense>
      </body>
    </html>
  );
}
