"use client";

import React, { Suspense, useEffect } from "react";
import { RefineContext } from "./_refine_context";
import { I18nProvider } from "@/providers/i18n-provider";
// dayjs 초기화 (플러그인 및 로케일 설정)
import "@/lib/dayjs";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    // CSR에서 메타데이터 동적 설정
    document.title = "Refine";
    const metaDescription = document.querySelector('meta[name="description"]');
    if (!metaDescription) {
      const meta = document.createElement("meta");
      meta.name = "description";
      meta.content = "Generated by create refine app";
      document.head.appendChild(meta);
    }
  }, []);

  return (
    <html lang="ko">
      <body>
        <Suspense>
          <I18nProvider>
            <RefineContext>{children}</RefineContext>
          </I18nProvider>
        </Suspense>
      </body>
    </html>
  );
}
