/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/vue-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationReturnType
} from '@tanstack/vue-query';

import {
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  CreateWithdrawRequestDto,
  CreateWithdrawResponseDto
} from '../../models';

import { customInstance } from '../../axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary 출금 요청
 */
export const withdrawControllerCreateWithdraw = (
    createWithdrawRequestDto: MaybeRef<CreateWithdrawRequestDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      createWithdrawRequestDto = unref(createWithdrawRequestDto);
      
      return customInstance<CreateWithdrawResponseDto>(
      {url: `/withdraws`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createWithdrawRequestDto, signal
    },
      options);
    }
  


export const getWithdrawControllerCreateWithdrawMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof withdrawControllerCreateWithdraw>>, TError,{data: CreateWithdrawRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof withdrawControllerCreateWithdraw>>, TError,{data: CreateWithdrawRequestDto}, TContext> => {

const mutationKey = ['withdrawControllerCreateWithdraw'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof withdrawControllerCreateWithdraw>>, {data: CreateWithdrawRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  withdrawControllerCreateWithdraw(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type WithdrawControllerCreateWithdrawMutationResult = NonNullable<Awaited<ReturnType<typeof withdrawControllerCreateWithdraw>>>
    export type WithdrawControllerCreateWithdrawMutationBody = CreateWithdrawRequestDto
    export type WithdrawControllerCreateWithdrawMutationError = void

    /**
 * @summary 출금 요청
 */
export const useWithdrawControllerCreateWithdraw = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof withdrawControllerCreateWithdraw>>, TError,{data: CreateWithdrawRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof withdrawControllerCreateWithdraw>>,
        TError,
        {data: CreateWithdrawRequestDto},
        TContext
      > => {

      const mutationOptions = getWithdrawControllerCreateWithdrawMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    