/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  AffiliateCodeControllerCreate201,
  AffiliateCodeControllerGetCodes200,
  AffiliateCodeControllerGetCodesParams,
  AffiliateCodeControllerGetDefaultCode200,
  AffiliateCodeControllerUpdate200,
  AffiliateCodeControllerValidateCodeFormat200,
  CreateAffiliateCodeDto,
  ErrorResponseDto,
  UpdateAffiliateCodeDto,
  ValidateCodeFormatDto
} from '../../models';

import { customInstance } from '../../axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Create affiliate code / 어플리에이트 코드 생성
 */
export const affiliateCodeControllerCreate = (
    createAffiliateCodeDto: MaybeRef<CreateAffiliateCodeDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      createAffiliateCodeDto = unref(createAffiliateCodeDto);
      
      return customInstance<AffiliateCodeControllerCreate201>(
      {url: `/affiliate-codes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createAffiliateCodeDto, signal
    },
      options);
    }
  


export const getAffiliateCodeControllerCreateMutationOptions = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof affiliateCodeControllerCreate>>, TError,{data: CreateAffiliateCodeDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof affiliateCodeControllerCreate>>, TError,{data: CreateAffiliateCodeDto}, TContext> => {

const mutationKey = ['affiliateCodeControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof affiliateCodeControllerCreate>>, {data: CreateAffiliateCodeDto}> = (props) => {
          const {data} = props ?? {};

          return  affiliateCodeControllerCreate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AffiliateCodeControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof affiliateCodeControllerCreate>>>
    export type AffiliateCodeControllerCreateMutationBody = CreateAffiliateCodeDto
    export type AffiliateCodeControllerCreateMutationError = ErrorResponseDto

    /**
 * @summary Create affiliate code / 어플리에이트 코드 생성
 */
export const useAffiliateCodeControllerCreate = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof affiliateCodeControllerCreate>>, TError,{data: CreateAffiliateCodeDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof affiliateCodeControllerCreate>>,
        TError,
        {data: CreateAffiliateCodeDto},
        TContext
      > => {

      const mutationOptions = getAffiliateCodeControllerCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * 사용자의 어플리에이트 코드 목록을 조회합니다. 만약 코드가 하나도 없다면 자동으로 대표 코드를 하나 생성하여 반환합니다.
 * @summary Get affiliate codes / 어플리에이트 코드 목록 조회
 */
export const affiliateCodeControllerGetCodes = (
    params?: MaybeRef<AffiliateCodeControllerGetCodesParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = unref(params);
      
      return customInstance<AffiliateCodeControllerGetCodes200>(
      {url: `/affiliate-codes`, method: 'GET',
        params: unref(params), signal
    },
      options);
    }
  



export const getAffiliateCodeControllerGetCodesQueryKey = (params?: MaybeRef<AffiliateCodeControllerGetCodesParams>,) => {
    return [
    'affiliate-codes', ...(params ? [params]: [])
    ] as const;
    }

    
export const getAffiliateCodeControllerGetCodesQueryOptions = <TData = Awaited<ReturnType<typeof affiliateCodeControllerGetCodes>>, TError = ErrorResponseDto>(params?: MaybeRef<AffiliateCodeControllerGetCodesParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof affiliateCodeControllerGetCodes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getAffiliateCodeControllerGetCodesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof affiliateCodeControllerGetCodes>>> = ({ signal }) => affiliateCodeControllerGetCodes(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof affiliateCodeControllerGetCodes>>, TError, TData> 
}

export type AffiliateCodeControllerGetCodesQueryResult = NonNullable<Awaited<ReturnType<typeof affiliateCodeControllerGetCodes>>>
export type AffiliateCodeControllerGetCodesQueryError = ErrorResponseDto


/**
 * @summary Get affiliate codes / 어플리에이트 코드 목록 조회
 */

export function useAffiliateCodeControllerGetCodes<TData = Awaited<ReturnType<typeof affiliateCodeControllerGetCodes>>, TError = ErrorResponseDto>(
 params?: MaybeRef<AffiliateCodeControllerGetCodesParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof affiliateCodeControllerGetCodes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAffiliateCodeControllerGetCodesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




/**
 * 사용자의 대표 어플리에이트 코드를 조회합니다. 만약 코드가 없다면 자동으로 하나를 생성하여 반환합니다.
 * @summary Get default affiliate code / 대표 어플리에이트 코드 조회
 */
export const affiliateCodeControllerGetDefaultCode = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AffiliateCodeControllerGetDefaultCode200>(
      {url: `/affiliate-codes/default`, method: 'GET', signal
    },
      options);
    }
  



export const getAffiliateCodeControllerGetDefaultCodeQueryKey = () => {
    return [
    'affiliate-codes','default'
    ] as const;
    }

    
export const getAffiliateCodeControllerGetDefaultCodeQueryOptions = <TData = Awaited<ReturnType<typeof affiliateCodeControllerGetDefaultCode>>, TError = ErrorResponseDto>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof affiliateCodeControllerGetDefaultCode>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getAffiliateCodeControllerGetDefaultCodeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof affiliateCodeControllerGetDefaultCode>>> = ({ signal }) => affiliateCodeControllerGetDefaultCode(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof affiliateCodeControllerGetDefaultCode>>, TError, TData> 
}

export type AffiliateCodeControllerGetDefaultCodeQueryResult = NonNullable<Awaited<ReturnType<typeof affiliateCodeControllerGetDefaultCode>>>
export type AffiliateCodeControllerGetDefaultCodeQueryError = ErrorResponseDto


/**
 * @summary Get default affiliate code / 대표 어플리에이트 코드 조회
 */

export function useAffiliateCodeControllerGetDefaultCode<TData = Awaited<ReturnType<typeof affiliateCodeControllerGetDefaultCode>>, TError = ErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof affiliateCodeControllerGetDefaultCode>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAffiliateCodeControllerGetDefaultCodeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




/**
 * @summary Update affiliate code / 어플리에이트 코드 수정
 */
export const affiliateCodeControllerUpdate = (
    id: MaybeRef<string>,
    updateAffiliateCodeDto: MaybeRef<UpdateAffiliateCodeDto>,
 options?: SecondParameter<typeof customInstance>,) => {
      id = unref(id);
updateAffiliateCodeDto = unref(updateAffiliateCodeDto);
      
      return customInstance<AffiliateCodeControllerUpdate200>(
      {url: `/affiliate-codes/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateAffiliateCodeDto
    },
      options);
    }
  


export const getAffiliateCodeControllerUpdateMutationOptions = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof affiliateCodeControllerUpdate>>, TError,{id: string;data: UpdateAffiliateCodeDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof affiliateCodeControllerUpdate>>, TError,{id: string;data: UpdateAffiliateCodeDto}, TContext> => {

const mutationKey = ['affiliateCodeControllerUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof affiliateCodeControllerUpdate>>, {id: string;data: UpdateAffiliateCodeDto}> = (props) => {
          const {id,data} = props ?? {};

          return  affiliateCodeControllerUpdate(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AffiliateCodeControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof affiliateCodeControllerUpdate>>>
    export type AffiliateCodeControllerUpdateMutationBody = UpdateAffiliateCodeDto
    export type AffiliateCodeControllerUpdateMutationError = ErrorResponseDto

    /**
 * @summary Update affiliate code / 어플리에이트 코드 수정
 */
export const useAffiliateCodeControllerUpdate = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof affiliateCodeControllerUpdate>>, TError,{id: string;data: UpdateAffiliateCodeDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof affiliateCodeControllerUpdate>>,
        TError,
        {id: string;data: UpdateAffiliateCodeDto},
        TContext
      > => {

      const mutationOptions = getAffiliateCodeControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Validate code format / 코드 형식 검증
 */
export const affiliateCodeControllerValidateCodeFormat = (
    validateCodeFormatDto: MaybeRef<ValidateCodeFormatDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      validateCodeFormatDto = unref(validateCodeFormatDto);
      
      return customInstance<AffiliateCodeControllerValidateCodeFormat200>(
      {url: `/affiliate-codes/validate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: validateCodeFormatDto, signal
    },
      options);
    }
  


export const getAffiliateCodeControllerValidateCodeFormatMutationOptions = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof affiliateCodeControllerValidateCodeFormat>>, TError,{data: ValidateCodeFormatDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof affiliateCodeControllerValidateCodeFormat>>, TError,{data: ValidateCodeFormatDto}, TContext> => {

const mutationKey = ['affiliateCodeControllerValidateCodeFormat'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof affiliateCodeControllerValidateCodeFormat>>, {data: ValidateCodeFormatDto}> = (props) => {
          const {data} = props ?? {};

          return  affiliateCodeControllerValidateCodeFormat(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AffiliateCodeControllerValidateCodeFormatMutationResult = NonNullable<Awaited<ReturnType<typeof affiliateCodeControllerValidateCodeFormat>>>
    export type AffiliateCodeControllerValidateCodeFormatMutationBody = ValidateCodeFormatDto
    export type AffiliateCodeControllerValidateCodeFormatMutationError = ErrorResponseDto

    /**
 * @summary Validate code format / 코드 형식 검증
 */
export const useAffiliateCodeControllerValidateCodeFormat = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof affiliateCodeControllerValidateCodeFormat>>, TError,{data: ValidateCodeFormatDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof affiliateCodeControllerValidateCodeFormat>>,
        TError,
        {data: ValidateCodeFormatDto},
        TContext
      > => {

      const mutationOptions = getAffiliateCodeControllerValidateCodeFormatMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    