/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */
import type { AdminDepositControllerGetDepositsSortBy } from './adminDepositControllerGetDepositsSortBy';
import type { AdminDepositControllerGetDepositsSortOrder } from './adminDepositControllerGetDepositsSortOrder';
import type { AdminDepositControllerGetDepositsStatus } from './adminDepositControllerGetDepositsStatus';
import type { AdminDepositControllerGetDepositsMethodType } from './adminDepositControllerGetDepositsMethodType';
import type { AdminDepositControllerGetDepositsCurrency } from './adminDepositControllerGetDepositsCurrency';

export type AdminDepositControllerGetDepositsParams = {
/**
 * 페이지 번호 (기본값: 1)
 * @minimum 1
 */
page?: number;
/**
 * 페이지당 항목 수 (기본값: 20, 최대: 100)
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * 정렬 필드
 */
sortBy?: AdminDepositControllerGetDepositsSortBy;
/**
 * 정렬 방향 (asc, desc)
 */
sortOrder?: AdminDepositControllerGetDepositsSortOrder;
/**
 * 입금 상태 필터
 */
status?: AdminDepositControllerGetDepositsStatus;
/**
 * 입금 방법 필터
 */
methodType?: AdminDepositControllerGetDepositsMethodType;
/**
 * 사용자 ID 필터
 */
userId?: number;
/**
 * 통화 필터
 */
currency?: AdminDepositControllerGetDepositsCurrency;
/**
 * 시작 날짜 (ISO 8601 형식)
 */
startDate?: string;
/**
 * 종료 날짜 (ISO 8601 형식)
 */
endDate?: string;
};
