/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */
import type { ApiResponseDto } from './apiResponseDto';
import type { AdminDepositControllerCreateCryptoConfig201AllOf } from './adminDepositControllerCreateCryptoConfig201AllOf';

export type AdminDepositControllerCreateCryptoConfig201 = ApiResponseDto & AdminDepositControllerCreateCryptoConfig201AllOf;
