/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * 티어
 */
export type AffiliateTierResponseDtoTier = typeof AffiliateTierResponseDtoTier[keyof typeof AffiliateTierResponseDtoTier];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AffiliateTierResponseDtoTier = {
  BRONZE: 'BRONZE',
  SILVER: 'SILVER',
  GOLD: 'GOLD',
  PLATINUM: 'PLATINUM',
  DIAMOND: 'DIAMOND',
} as const;
