/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */
import type { ApiResponseDto } from './apiResponseDto';
import type { AffiliateCodeControllerGetDefaultCode200AllOf } from './affiliateCodeControllerGetDefaultCode200AllOf';

export type AffiliateCodeControllerGetDefaultCode200 = ApiResponseDto & AffiliateCodeControllerGetDefaultCode200AllOf;
