/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */

export interface AppendWagerRequestDto {
  /**
   * Brand ID
   * @maxLength 9
   */
  brand_id: string;
  /**
   * Sign (MD5 hash: brand_id+wager_id+api_key)
   * @maxLength 32
   */
  sign: string;
  /**
   * Unique User ID from operator (only English characters and numbers, case insensitive)
   * @maxLength 20
   */
  brand_uid: string;
  /**
   * Player currency code
   * @maxLength 4
   */
  currency: string;
  /** Player jackpot winning amount */
  amount: number;
  /** DC game ID */
  game_id: number;
  /**
   * DC Game Name
   * @maxLength 50
   */
  game_name: string;
  /**
   * Unique bet round identifier
   * @maxLength 64
   */
  round_id: string;
  /**
   * Unique transaction identifier within a bet round
   * @maxLength 64
   */
  wager_id: string;
  /**
   * Game provider code
   * @maxLength 20
   */
  provider: string;
  /**
   * Description of appendWager
   * @maxLength 100
   */
  description: string;
  /** Round finish status (false=Unfinished, true=Round Finish) */
  is_endround: boolean;
  /**
   * Transaction time (format: yyyy-MM-ddTHH:mm:ssZ)
   * @maxLength 20
   */
  transaction_time: string;
}
