/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * Deposit method type (입금 방법)
 */
export type CreateDepositRequestDtoMethodType = typeof CreateDepositRequestDtoMethodType[keyof typeof CreateDepositRequestDtoMethodType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateDepositRequestDtoMethodType = {
  CRYPTO_WALLET: 'CRYPTO_WALLET',
  BANK_TRANSFER: 'BANK_TRANSFER',
} as const;
