/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */
import type { CreateDepositResponseDtoPayAddressExtraId } from './createDepositResponseDtoPayAddressExtraId';

export interface CreateDepositResponseDto {
  /** Payment address (결제 주소, 암호화폐 입금 시) */
  payAddress?: string;
  /** Payment currency (결제 통화, 암호화폐 입금 시) */
  payCurrency?: string;
  /**
   * Payment address extra ID (추가 ID, 예: 태그, 메모 등 네트워크별 필요시 사용)
   * @nullable
   */
  payAddressExtraId?: CreateDepositResponseDtoPayAddressExtraId;
  /** Payment network (네트워크, 암호화폐 입금 시) */
  payNetwork?: string;
  /** Bank name (은행명, 무통장 입금 시) */
  bankName?: string;
  /** Account number (계좌번호, 무통장 입금 시) */
  accountNumber?: string;
  /** Account holder name (예금주명, 무통장 입금 시) */
  accountHolder?: string;
  /** Transaction ID (입금 대기 중인 거래 ID) */
  transactionId?: string;
  /** Whether this is a duplicate request (중복 요청 여부) */
  isDuplicate?: boolean;
  /** Deposit Record UID (입금 기록 UID) */
  depositUid?: string;
}
