/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */

export type DcsTestControllerLoginGameBody = {
  /** DCS 사용자 ID */
  dcsUserId: string;
  /** DCS 사용자 토큰 */
  dcsUserToken: string;
  /** 게임 ID */
  gameId: number;
  /** 통화 */
  currency: string;
  /** 언어 */
  language: string;
  /** 국가 코드 */
  country_code: string;
  /** 채널 */
  channel: string;
  /**
   * 리턴 URL (선택)
   * @nullable
   */
  return_url?: string | null;
  /**
   * 전체 화면 모드 (선택)
   * @nullable
   */
  full_screen?: boolean | null;
};
