/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */
import type { ApiResponseDto } from './apiResponseDto';
import type { DepositControllerGetDepositDetail200AllOf } from './depositControllerGetDepositDetail200AllOf';

export type DepositControllerGetDepositDetail200 = ApiResponseDto & DepositControllerGetDepositDetail200AllOf;
