/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */
import type { PromotionCurrencyResponseDto } from './promotionCurrencyResponseDto';

export interface PromotionCurrencyListResponseDto {
  /** 통화별 설정 목록 */
  currencies: PromotionCurrencyResponseDto[];
}
