/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */
import type { PaginatedResponseDto } from './paginatedResponseDto';
import type { PromotionAdminControllerGetPromotionParticipants200AllOf } from './promotionAdminControllerGetPromotionParticipants200AllOf';

export type PromotionAdminControllerGetPromotionParticipants200 = PaginatedResponseDto & PromotionAdminControllerGetPromotionParticipants200AllOf;
