/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */

export interface PromoPayoutRequestDto {
  /**
   * Brand ID
   * @maxLength 9
   */
  brand_id: string;
  /**
   * Sign (MD5 hash: brand_id+promotion_id+trans_id+api_key)
   * @maxLength 32
   */
  sign: string;
  /**
   * Unique User ID from operator (only English characters and numbers, case insensitive)
   * @maxLength 20
   */
  brand_uid: string;
  /**
   * Player currency code
   * @maxLength 4
   */
  currency: string;
  /** Promo bonus */
  amount: number;
  /**
   * Promotion id
   * @maxLength 36
   */
  promotion_id: string;
  /**
   * Trans id
   * @maxLength 128
   */
  trans_id: string;
  /**
   * Game provider code
   * @maxLength 16
   */
  provider: string;
  /**
   * Transaction time (format: yyyy-MM-ddTHH:mm:ssZ)
   * @maxLength 20
   */
  transaction_time: string;
}
