/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */

export type PromotionUserControllerGetMyPromotionsSortOrder = typeof PromotionUserControllerGetMyPromotionsSortOrder[keyof typeof PromotionUserControllerGetMyPromotionsSortOrder];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PromotionUserControllerGetMyPromotionsSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
