/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */

export type RollingResponseDtoSourceType = typeof RollingResponseDtoSourceType[keyof typeof RollingResponseDtoSourceType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RollingResponseDtoSourceType = {
  DEPOSIT: 'DEPOSIT',
  PROMOTION_BONUS: 'PROMOTION_BONUS',
} as const;
