/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * 종료 시간 (REVOKED 상태일 때)
 * @nullable
 */
export type SessionListItemDtoRevokedAt = { [key: string]: unknown } | null;
