/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */
import type { TranslationDtoLanguage } from './translationDtoLanguage';
import type { TranslationDtoDescription } from './translationDtoDescription';

export interface TranslationDto {
  /** 언어 코드 */
  language: TranslationDtoLanguage;
  /** 프로모션 이름 */
  name: string;
  /**
   * 프로모션 설명
   * @nullable
   */
  description?: TranslationDtoDescription;
}
