/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */

export interface UpdateAffiliateCodeDto {
  /** Campaign name / 캠페인 이름 */
  campaignName?: string;
}
