/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * Currency code / 통화 코드
 */
export type UpdateBankConfigRequestDtoCurrency = typeof UpdateBankConfigRequestDtoCurrency[keyof typeof UpdateBankConfigRequestDtoCurrency];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateBankConfigRequestDtoCurrency = {
  USDT: 'USDT',
  USD: 'USD',
  KRW: 'KRW',
  JPY: 'JPY',
  PHP: 'PHP',
  IDR: 'IDR',
  VND: 'VND',
  BTC: 'BTC',
  ETH: 'ETH',
  SOL: 'SOL',
  XRP: 'XRP',
  DOGE: 'DOGE',
  LTC: 'LTC',
  BCH: 'BCH',
  EOS: 'EOS',
  TRX: 'TRX',
} as const;
