/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * Deposit method type
 */
export type UserDepositResponseDtoMethodType = typeof UserDepositResponseDtoMethodType[keyof typeof UserDepositResponseDtoMethodType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserDepositResponseDtoMethodType = {
  CRYPTO_WALLET: 'CRYPTO_WALLET',
  BANK_TRANSFER: 'BANK_TRANSFER',
} as const;
