/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * Deposit fee amount
 * @nullable
 */
export type UserDepositResponseDtoFeeAmount = { [key: string]: unknown } | null;
