/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * 통화
 */
export type UserBalanceItemDtoCurrency = typeof UserBalanceItemDtoCurrency[keyof typeof UserBalanceItemDtoCurrency];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserBalanceItemDtoCurrency = {
  KRW: 'KRW',
} as const;
