/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * 다음 레벨 정보
 */
export type VipMembershipResponseDtoNextLevel = { [key: string]: unknown };
