/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * 레벨 달성일
 */
export type VipMembershipResponseDtoAchievedAt = { [key: string]: unknown };
