import {
    Controller,
    Get,
    Patch,
    Query,
    Body,
    Param,
    HttpStatus,
    HttpCode,
} from '@nestjs/common';
import { ApiTags, ApiOperation } from '@nestjs/swagger';
import {
    ApiStandardResponse,
} from '../../../../../common/http/decorators/api-response.decorator';
import {
    RequireRoles,
} from 'src/common/auth/decorators/roles.decorator';
import { CurrentUser } from 'src/common/auth/decorators/current-user.decorator';
import type { CurrentUserWithSession } from 'src/common/auth/decorators/current-user.decorator';
import { RequestClientInfoParam } from 'src/common/auth/decorators/request-info.decorator';
import type { RequestClientInfo } from 'src/common/http/types/client-info.types';
import { FindLoginAttemptsService } from '../../application/find-login-attempts.service';
import { ResetUserPasswordAdminService } from '../../application/reset-user-password-admin.service';
import { LoginAttemptResponseDto } from './dto/response/login-attempt.response.dto';
import { FindLoginAttemptsQueryDto } from './dto/request/find-login-attempts-query.dto';
import { ResetUserPasswordRequestDto } from './dto/request/reset-user-password.request.dto';
import { ResetUserPasswordResponseDto } from './dto/response/reset-user-password.response.dto';
import { UserRoleType } from '@prisma/client';
import { AuditLog } from 'src/modules/audit-log/infrastructure';
import { LogType } from 'src/modules/audit-log/domain';

@ApiTags('Admin / Auth Management')
@Controller('admin/auth/management')
export class AdminAuthManagementController {
    constructor(
        private readonly findAttemptsService: FindLoginAttemptsService,
        private readonly resetUserPasswordAdminService: ResetUserPasswordAdminService,
    ) { }

    @Get('login-attempts')
    @RequireRoles(UserRoleType.ADMIN, UserRoleType.SUPER_ADMIN)
    @ApiOperation({
        summary: 'Login Attempts / 로그인 시도 내역 조회',
        description:
            '감사 및 보안 모니터링 목적. loginId 또는 ipAddress 중 하나는 필수입니다.',
    })
    @ApiStandardResponse(LoginAttemptResponseDto, {
        status: HttpStatus.OK,
        isArray: true,
    })
    async getAttempts(
        @Query() query: FindLoginAttemptsQueryDto,
    ): Promise<LoginAttemptResponseDto[]> {
        const attempts = await this.findAttemptsService.execute({
            loginId: query.loginId,
            ipAddress: query.ipAddress,
            limit: query.limit,
        });

        return attempts.map((attempt) => ({
            id: attempt.id?.toString() || '',
            uid: attempt.uid || '',
            userId: attempt.userId,
            result: attempt.result,
            failureReason: attempt.failureReason,
            ipAddress: attempt.ipAddress,
            loginId: attempt.loginId,
            attemptedAt: attempt.attemptedAt,
            isAdmin: attempt.isAdmin,
        }));
    }

    @Patch('users/:userId/password')
    @HttpCode(HttpStatus.OK)
    @RequireRoles(UserRoleType.ADMIN, UserRoleType.SUPER_ADMIN)
    @ApiOperation({
        summary: 'Reset User Password / 사용자 비밀번호 초기화',
        description: '관리자가 특정 사용자의 비밀번호를 초기화합니다.',
    })
    @ApiStandardResponse(ResetUserPasswordResponseDto, {
        status: HttpStatus.OK,
        description:
            'User password reset successfully / 사용자 비밀번호 초기화 성공',
    })
    @AuditLog({
        type: LogType.AUTH,
        action: 'ADMIN_PASSWORD_RESET',
        extractMetadata: (_, args) => {
            const [userId, dto] = args;
            return {
                targetUserId: userId,
                isAutoGenerated: !dto?.newPassword,
            };
        },
    })
    async resetUserPassword(
        @Param('userId') userId: string,
        @Body() dto: ResetUserPasswordRequestDto,
        @CurrentUser() admin: CurrentUserWithSession,
        @RequestClientInfoParam() requestInfo: RequestClientInfo,
    ): Promise<ResetUserPasswordResponseDto> {
        const targetUserId = BigInt(userId);

        const result = await this.resetUserPasswordAdminService.execute({
            targetUserId,
            adminUserId: admin.id,
            newPassword: dto.newPassword,
            requestInfo,
        });

        // 비밀번호가 자동 생성된 경우에만 응답에 포함
        const isAutoGenerated = !dto.newPassword;

        return {
            message: 'Password has been reset.',
            generatedPassword: isAutoGenerated ? result.newPassword : undefined,
            targetUserEmail: result.targetUserEmail,
        };
    }
}
