
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BonusDetail` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model BonusDetail
 * 
 */
export type BonusDetailModel = runtime.Types.Result.DefaultSelection<Prisma.$BonusDetailPayload>

export type AggregateBonusDetail = {
  _count: BonusDetailCountAggregateOutputType | null
  _avg: BonusDetailAvgAggregateOutputType | null
  _sum: BonusDetailSumAggregateOutputType | null
  _min: BonusDetailMinAggregateOutputType | null
  _max: BonusDetailMaxAggregateOutputType | null
}

export type BonusDetailAvgAggregateOutputType = {
  id: number | null
  amount: runtime.Decimal | null
  gameId: number | null
  transactionId: number | null
}

export type BonusDetailSumAggregateOutputType = {
  id: bigint | null
  amount: runtime.Decimal | null
  gameId: number | null
  transactionId: bigint | null
}

export type BonusDetailMinAggregateOutputType = {
  id: bigint | null
  createdAt: Date | null
  transactionTime: Date | null
  aggregatorType: $Enums.GameAggregatorType | null
  provider: $Enums.GameProvider | null
  bonusType: $Enums.BonusType | null
  amount: runtime.Decimal | null
  aggregatorPromotionId: string | null
  aggregatorRoundId: string | null
  aggregatorWagerId: string | null
  aggregatorTransactionId: string | null
  aggregatorFreespinId: string | null
  aggregatorSessionId: string | null
  isEndRound: boolean | null
  description: string | null
  gameId: number | null
  transactionId: bigint | null
}

export type BonusDetailMaxAggregateOutputType = {
  id: bigint | null
  createdAt: Date | null
  transactionTime: Date | null
  aggregatorType: $Enums.GameAggregatorType | null
  provider: $Enums.GameProvider | null
  bonusType: $Enums.BonusType | null
  amount: runtime.Decimal | null
  aggregatorPromotionId: string | null
  aggregatorRoundId: string | null
  aggregatorWagerId: string | null
  aggregatorTransactionId: string | null
  aggregatorFreespinId: string | null
  aggregatorSessionId: string | null
  isEndRound: boolean | null
  description: string | null
  gameId: number | null
  transactionId: bigint | null
}

export type BonusDetailCountAggregateOutputType = {
  id: number
  createdAt: number
  transactionTime: number
  aggregatorType: number
  provider: number
  bonusType: number
  amount: number
  aggregatorPromotionId: number
  aggregatorRoundId: number
  aggregatorWagerId: number
  aggregatorTransactionId: number
  aggregatorFreespinId: number
  aggregatorSessionId: number
  isEndRound: number
  description: number
  gameId: number
  transactionId: number
  _all: number
}


export type BonusDetailAvgAggregateInputType = {
  id?: true
  amount?: true
  gameId?: true
  transactionId?: true
}

export type BonusDetailSumAggregateInputType = {
  id?: true
  amount?: true
  gameId?: true
  transactionId?: true
}

export type BonusDetailMinAggregateInputType = {
  id?: true
  createdAt?: true
  transactionTime?: true
  aggregatorType?: true
  provider?: true
  bonusType?: true
  amount?: true
  aggregatorPromotionId?: true
  aggregatorRoundId?: true
  aggregatorWagerId?: true
  aggregatorTransactionId?: true
  aggregatorFreespinId?: true
  aggregatorSessionId?: true
  isEndRound?: true
  description?: true
  gameId?: true
  transactionId?: true
}

export type BonusDetailMaxAggregateInputType = {
  id?: true
  createdAt?: true
  transactionTime?: true
  aggregatorType?: true
  provider?: true
  bonusType?: true
  amount?: true
  aggregatorPromotionId?: true
  aggregatorRoundId?: true
  aggregatorWagerId?: true
  aggregatorTransactionId?: true
  aggregatorFreespinId?: true
  aggregatorSessionId?: true
  isEndRound?: true
  description?: true
  gameId?: true
  transactionId?: true
}

export type BonusDetailCountAggregateInputType = {
  id?: true
  createdAt?: true
  transactionTime?: true
  aggregatorType?: true
  provider?: true
  bonusType?: true
  amount?: true
  aggregatorPromotionId?: true
  aggregatorRoundId?: true
  aggregatorWagerId?: true
  aggregatorTransactionId?: true
  aggregatorFreespinId?: true
  aggregatorSessionId?: true
  isEndRound?: true
  description?: true
  gameId?: true
  transactionId?: true
  _all?: true
}

export type BonusDetailAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BonusDetail to aggregate.
   */
  where?: Prisma.BonusDetailWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BonusDetails to fetch.
   */
  orderBy?: Prisma.BonusDetailOrderByWithRelationInput | Prisma.BonusDetailOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BonusDetailWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BonusDetails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BonusDetails.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BonusDetails
  **/
  _count?: true | BonusDetailCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: BonusDetailAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: BonusDetailSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BonusDetailMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BonusDetailMaxAggregateInputType
}

export type GetBonusDetailAggregateType<T extends BonusDetailAggregateArgs> = {
      [P in keyof T & keyof AggregateBonusDetail]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBonusDetail[P]>
    : Prisma.GetScalarType<T[P], AggregateBonusDetail[P]>
}




export type BonusDetailGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BonusDetailWhereInput
  orderBy?: Prisma.BonusDetailOrderByWithAggregationInput | Prisma.BonusDetailOrderByWithAggregationInput[]
  by: Prisma.BonusDetailScalarFieldEnum[] | Prisma.BonusDetailScalarFieldEnum
  having?: Prisma.BonusDetailScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BonusDetailCountAggregateInputType | true
  _avg?: BonusDetailAvgAggregateInputType
  _sum?: BonusDetailSumAggregateInputType
  _min?: BonusDetailMinAggregateInputType
  _max?: BonusDetailMaxAggregateInputType
}

export type BonusDetailGroupByOutputType = {
  id: bigint
  createdAt: Date
  transactionTime: Date
  aggregatorType: $Enums.GameAggregatorType
  provider: $Enums.GameProvider
  bonusType: $Enums.BonusType
  amount: runtime.Decimal
  aggregatorPromotionId: string | null
  aggregatorRoundId: string | null
  aggregatorWagerId: string | null
  aggregatorTransactionId: string | null
  aggregatorFreespinId: string | null
  aggregatorSessionId: string | null
  isEndRound: boolean | null
  description: string | null
  gameId: number | null
  transactionId: bigint
  _count: BonusDetailCountAggregateOutputType | null
  _avg: BonusDetailAvgAggregateOutputType | null
  _sum: BonusDetailSumAggregateOutputType | null
  _min: BonusDetailMinAggregateOutputType | null
  _max: BonusDetailMaxAggregateOutputType | null
}

type GetBonusDetailGroupByPayload<T extends BonusDetailGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BonusDetailGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BonusDetailGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BonusDetailGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BonusDetailGroupByOutputType[P]>
      }
    >
  >



export type BonusDetailWhereInput = {
  AND?: Prisma.BonusDetailWhereInput | Prisma.BonusDetailWhereInput[]
  OR?: Prisma.BonusDetailWhereInput[]
  NOT?: Prisma.BonusDetailWhereInput | Prisma.BonusDetailWhereInput[]
  id?: Prisma.BigIntFilter<"BonusDetail"> | bigint | number
  createdAt?: Prisma.DateTimeFilter<"BonusDetail"> | Date | string
  transactionTime?: Prisma.DateTimeFilter<"BonusDetail"> | Date | string
  aggregatorType?: Prisma.EnumGameAggregatorTypeFilter<"BonusDetail"> | $Enums.GameAggregatorType
  provider?: Prisma.EnumGameProviderFilter<"BonusDetail"> | $Enums.GameProvider
  bonusType?: Prisma.EnumBonusTypeFilter<"BonusDetail"> | $Enums.BonusType
  amount?: Prisma.DecimalFilter<"BonusDetail"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  aggregatorPromotionId?: Prisma.StringNullableFilter<"BonusDetail"> | string | null
  aggregatorRoundId?: Prisma.StringNullableFilter<"BonusDetail"> | string | null
  aggregatorWagerId?: Prisma.StringNullableFilter<"BonusDetail"> | string | null
  aggregatorTransactionId?: Prisma.StringNullableFilter<"BonusDetail"> | string | null
  aggregatorFreespinId?: Prisma.StringNullableFilter<"BonusDetail"> | string | null
  aggregatorSessionId?: Prisma.StringNullableFilter<"BonusDetail"> | string | null
  isEndRound?: Prisma.BoolNullableFilter<"BonusDetail"> | boolean | null
  description?: Prisma.StringNullableFilter<"BonusDetail"> | string | null
  gameId?: Prisma.IntNullableFilter<"BonusDetail"> | number | null
  transactionId?: Prisma.BigIntFilter<"BonusDetail"> | bigint | number
  game?: Prisma.XOR<Prisma.GameNullableScalarRelationFilter, Prisma.GameWhereInput> | null
  transaction?: Prisma.XOR<Prisma.TransactionScalarRelationFilter, Prisma.TransactionWhereInput>
}

export type BonusDetailOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  transactionTime?: Prisma.SortOrder
  aggregatorType?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  bonusType?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  aggregatorPromotionId?: Prisma.SortOrderInput | Prisma.SortOrder
  aggregatorRoundId?: Prisma.SortOrderInput | Prisma.SortOrder
  aggregatorWagerId?: Prisma.SortOrderInput | Prisma.SortOrder
  aggregatorTransactionId?: Prisma.SortOrderInput | Prisma.SortOrder
  aggregatorFreespinId?: Prisma.SortOrderInput | Prisma.SortOrder
  aggregatorSessionId?: Prisma.SortOrderInput | Prisma.SortOrder
  isEndRound?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  gameId?: Prisma.SortOrderInput | Prisma.SortOrder
  transactionId?: Prisma.SortOrder
  game?: Prisma.GameOrderByWithRelationInput
  transaction?: Prisma.TransactionOrderByWithRelationInput
}

export type BonusDetailWhereUniqueInput = Prisma.AtLeast<{
  id?: bigint | number
  transactionId?: bigint | number
  AND?: Prisma.BonusDetailWhereInput | Prisma.BonusDetailWhereInput[]
  OR?: Prisma.BonusDetailWhereInput[]
  NOT?: Prisma.BonusDetailWhereInput | Prisma.BonusDetailWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"BonusDetail"> | Date | string
  transactionTime?: Prisma.DateTimeFilter<"BonusDetail"> | Date | string
  aggregatorType?: Prisma.EnumGameAggregatorTypeFilter<"BonusDetail"> | $Enums.GameAggregatorType
  provider?: Prisma.EnumGameProviderFilter<"BonusDetail"> | $Enums.GameProvider
  bonusType?: Prisma.EnumBonusTypeFilter<"BonusDetail"> | $Enums.BonusType
  amount?: Prisma.DecimalFilter<"BonusDetail"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  aggregatorPromotionId?: Prisma.StringNullableFilter<"BonusDetail"> | string | null
  aggregatorRoundId?: Prisma.StringNullableFilter<"BonusDetail"> | string | null
  aggregatorWagerId?: Prisma.StringNullableFilter<"BonusDetail"> | string | null
  aggregatorTransactionId?: Prisma.StringNullableFilter<"BonusDetail"> | string | null
  aggregatorFreespinId?: Prisma.StringNullableFilter<"BonusDetail"> | string | null
  aggregatorSessionId?: Prisma.StringNullableFilter<"BonusDetail"> | string | null
  isEndRound?: Prisma.BoolNullableFilter<"BonusDetail"> | boolean | null
  description?: Prisma.StringNullableFilter<"BonusDetail"> | string | null
  gameId?: Prisma.IntNullableFilter<"BonusDetail"> | number | null
  game?: Prisma.XOR<Prisma.GameNullableScalarRelationFilter, Prisma.GameWhereInput> | null
  transaction?: Prisma.XOR<Prisma.TransactionScalarRelationFilter, Prisma.TransactionWhereInput>
}, "id" | "transactionId">

export type BonusDetailOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  transactionTime?: Prisma.SortOrder
  aggregatorType?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  bonusType?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  aggregatorPromotionId?: Prisma.SortOrderInput | Prisma.SortOrder
  aggregatorRoundId?: Prisma.SortOrderInput | Prisma.SortOrder
  aggregatorWagerId?: Prisma.SortOrderInput | Prisma.SortOrder
  aggregatorTransactionId?: Prisma.SortOrderInput | Prisma.SortOrder
  aggregatorFreespinId?: Prisma.SortOrderInput | Prisma.SortOrder
  aggregatorSessionId?: Prisma.SortOrderInput | Prisma.SortOrder
  isEndRound?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  gameId?: Prisma.SortOrderInput | Prisma.SortOrder
  transactionId?: Prisma.SortOrder
  _count?: Prisma.BonusDetailCountOrderByAggregateInput
  _avg?: Prisma.BonusDetailAvgOrderByAggregateInput
  _max?: Prisma.BonusDetailMaxOrderByAggregateInput
  _min?: Prisma.BonusDetailMinOrderByAggregateInput
  _sum?: Prisma.BonusDetailSumOrderByAggregateInput
}

export type BonusDetailScalarWhereWithAggregatesInput = {
  AND?: Prisma.BonusDetailScalarWhereWithAggregatesInput | Prisma.BonusDetailScalarWhereWithAggregatesInput[]
  OR?: Prisma.BonusDetailScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BonusDetailScalarWhereWithAggregatesInput | Prisma.BonusDetailScalarWhereWithAggregatesInput[]
  id?: Prisma.BigIntWithAggregatesFilter<"BonusDetail"> | bigint | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"BonusDetail"> | Date | string
  transactionTime?: Prisma.DateTimeWithAggregatesFilter<"BonusDetail"> | Date | string
  aggregatorType?: Prisma.EnumGameAggregatorTypeWithAggregatesFilter<"BonusDetail"> | $Enums.GameAggregatorType
  provider?: Prisma.EnumGameProviderWithAggregatesFilter<"BonusDetail"> | $Enums.GameProvider
  bonusType?: Prisma.EnumBonusTypeWithAggregatesFilter<"BonusDetail"> | $Enums.BonusType
  amount?: Prisma.DecimalWithAggregatesFilter<"BonusDetail"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  aggregatorPromotionId?: Prisma.StringNullableWithAggregatesFilter<"BonusDetail"> | string | null
  aggregatorRoundId?: Prisma.StringNullableWithAggregatesFilter<"BonusDetail"> | string | null
  aggregatorWagerId?: Prisma.StringNullableWithAggregatesFilter<"BonusDetail"> | string | null
  aggregatorTransactionId?: Prisma.StringNullableWithAggregatesFilter<"BonusDetail"> | string | null
  aggregatorFreespinId?: Prisma.StringNullableWithAggregatesFilter<"BonusDetail"> | string | null
  aggregatorSessionId?: Prisma.StringNullableWithAggregatesFilter<"BonusDetail"> | string | null
  isEndRound?: Prisma.BoolNullableWithAggregatesFilter<"BonusDetail"> | boolean | null
  description?: Prisma.StringNullableWithAggregatesFilter<"BonusDetail"> | string | null
  gameId?: Prisma.IntNullableWithAggregatesFilter<"BonusDetail"> | number | null
  transactionId?: Prisma.BigIntWithAggregatesFilter<"BonusDetail"> | bigint | number
}

export type BonusDetailCreateInput = {
  id?: bigint | number
  createdAt?: Date | string
  transactionTime: Date | string
  aggregatorType: $Enums.GameAggregatorType
  provider: $Enums.GameProvider
  bonusType: $Enums.BonusType
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  aggregatorPromotionId?: string | null
  aggregatorRoundId?: string | null
  aggregatorWagerId?: string | null
  aggregatorTransactionId?: string | null
  aggregatorFreespinId?: string | null
  aggregatorSessionId?: string | null
  isEndRound?: boolean | null
  description?: string | null
  game?: Prisma.GameCreateNestedOneWithoutBonusDetailsInput
  transaction: Prisma.TransactionCreateNestedOneWithoutBonusDetailInput
}

export type BonusDetailUncheckedCreateInput = {
  id?: bigint | number
  createdAt?: Date | string
  transactionTime: Date | string
  aggregatorType: $Enums.GameAggregatorType
  provider: $Enums.GameProvider
  bonusType: $Enums.BonusType
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  aggregatorPromotionId?: string | null
  aggregatorRoundId?: string | null
  aggregatorWagerId?: string | null
  aggregatorTransactionId?: string | null
  aggregatorFreespinId?: string | null
  aggregatorSessionId?: string | null
  isEndRound?: boolean | null
  description?: string | null
  gameId?: number | null
  transactionId: bigint | number
}

export type BonusDetailUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  transactionTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  aggregatorType?: Prisma.EnumGameAggregatorTypeFieldUpdateOperationsInput | $Enums.GameAggregatorType
  provider?: Prisma.EnumGameProviderFieldUpdateOperationsInput | $Enums.GameProvider
  bonusType?: Prisma.EnumBonusTypeFieldUpdateOperationsInput | $Enums.BonusType
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  aggregatorPromotionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorRoundId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorWagerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorTransactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorFreespinId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isEndRound?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  game?: Prisma.GameUpdateOneWithoutBonusDetailsNestedInput
  transaction?: Prisma.TransactionUpdateOneRequiredWithoutBonusDetailNestedInput
}

export type BonusDetailUncheckedUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  transactionTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  aggregatorType?: Prisma.EnumGameAggregatorTypeFieldUpdateOperationsInput | $Enums.GameAggregatorType
  provider?: Prisma.EnumGameProviderFieldUpdateOperationsInput | $Enums.GameProvider
  bonusType?: Prisma.EnumBonusTypeFieldUpdateOperationsInput | $Enums.BonusType
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  aggregatorPromotionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorRoundId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorWagerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorTransactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorFreespinId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isEndRound?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  gameId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  transactionId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type BonusDetailCreateManyInput = {
  id?: bigint | number
  createdAt?: Date | string
  transactionTime: Date | string
  aggregatorType: $Enums.GameAggregatorType
  provider: $Enums.GameProvider
  bonusType: $Enums.BonusType
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  aggregatorPromotionId?: string | null
  aggregatorRoundId?: string | null
  aggregatorWagerId?: string | null
  aggregatorTransactionId?: string | null
  aggregatorFreespinId?: string | null
  aggregatorSessionId?: string | null
  isEndRound?: boolean | null
  description?: string | null
  gameId?: number | null
  transactionId: bigint | number
}

export type BonusDetailUpdateManyMutationInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  transactionTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  aggregatorType?: Prisma.EnumGameAggregatorTypeFieldUpdateOperationsInput | $Enums.GameAggregatorType
  provider?: Prisma.EnumGameProviderFieldUpdateOperationsInput | $Enums.GameProvider
  bonusType?: Prisma.EnumBonusTypeFieldUpdateOperationsInput | $Enums.BonusType
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  aggregatorPromotionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorRoundId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorWagerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorTransactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorFreespinId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isEndRound?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type BonusDetailUncheckedUpdateManyInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  transactionTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  aggregatorType?: Prisma.EnumGameAggregatorTypeFieldUpdateOperationsInput | $Enums.GameAggregatorType
  provider?: Prisma.EnumGameProviderFieldUpdateOperationsInput | $Enums.GameProvider
  bonusType?: Prisma.EnumBonusTypeFieldUpdateOperationsInput | $Enums.BonusType
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  aggregatorPromotionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorRoundId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorWagerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorTransactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorFreespinId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isEndRound?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  gameId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  transactionId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type BonusDetailListRelationFilter = {
  every?: Prisma.BonusDetailWhereInput
  some?: Prisma.BonusDetailWhereInput
  none?: Prisma.BonusDetailWhereInput
}

export type BonusDetailOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BonusDetailNullableScalarRelationFilter = {
  is?: Prisma.BonusDetailWhereInput | null
  isNot?: Prisma.BonusDetailWhereInput | null
}

export type BonusDetailCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  transactionTime?: Prisma.SortOrder
  aggregatorType?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  bonusType?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  aggregatorPromotionId?: Prisma.SortOrder
  aggregatorRoundId?: Prisma.SortOrder
  aggregatorWagerId?: Prisma.SortOrder
  aggregatorTransactionId?: Prisma.SortOrder
  aggregatorFreespinId?: Prisma.SortOrder
  aggregatorSessionId?: Prisma.SortOrder
  isEndRound?: Prisma.SortOrder
  description?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  transactionId?: Prisma.SortOrder
}

export type BonusDetailAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  transactionId?: Prisma.SortOrder
}

export type BonusDetailMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  transactionTime?: Prisma.SortOrder
  aggregatorType?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  bonusType?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  aggregatorPromotionId?: Prisma.SortOrder
  aggregatorRoundId?: Prisma.SortOrder
  aggregatorWagerId?: Prisma.SortOrder
  aggregatorTransactionId?: Prisma.SortOrder
  aggregatorFreespinId?: Prisma.SortOrder
  aggregatorSessionId?: Prisma.SortOrder
  isEndRound?: Prisma.SortOrder
  description?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  transactionId?: Prisma.SortOrder
}

export type BonusDetailMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  transactionTime?: Prisma.SortOrder
  aggregatorType?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  bonusType?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  aggregatorPromotionId?: Prisma.SortOrder
  aggregatorRoundId?: Prisma.SortOrder
  aggregatorWagerId?: Prisma.SortOrder
  aggregatorTransactionId?: Prisma.SortOrder
  aggregatorFreespinId?: Prisma.SortOrder
  aggregatorSessionId?: Prisma.SortOrder
  isEndRound?: Prisma.SortOrder
  description?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  transactionId?: Prisma.SortOrder
}

export type BonusDetailSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  transactionId?: Prisma.SortOrder
}

export type BonusDetailCreateNestedManyWithoutGameInput = {
  create?: Prisma.XOR<Prisma.BonusDetailCreateWithoutGameInput, Prisma.BonusDetailUncheckedCreateWithoutGameInput> | Prisma.BonusDetailCreateWithoutGameInput[] | Prisma.BonusDetailUncheckedCreateWithoutGameInput[]
  connectOrCreate?: Prisma.BonusDetailCreateOrConnectWithoutGameInput | Prisma.BonusDetailCreateOrConnectWithoutGameInput[]
  createMany?: Prisma.BonusDetailCreateManyGameInputEnvelope
  connect?: Prisma.BonusDetailWhereUniqueInput | Prisma.BonusDetailWhereUniqueInput[]
}

export type BonusDetailUncheckedCreateNestedManyWithoutGameInput = {
  create?: Prisma.XOR<Prisma.BonusDetailCreateWithoutGameInput, Prisma.BonusDetailUncheckedCreateWithoutGameInput> | Prisma.BonusDetailCreateWithoutGameInput[] | Prisma.BonusDetailUncheckedCreateWithoutGameInput[]
  connectOrCreate?: Prisma.BonusDetailCreateOrConnectWithoutGameInput | Prisma.BonusDetailCreateOrConnectWithoutGameInput[]
  createMany?: Prisma.BonusDetailCreateManyGameInputEnvelope
  connect?: Prisma.BonusDetailWhereUniqueInput | Prisma.BonusDetailWhereUniqueInput[]
}

export type BonusDetailUpdateManyWithoutGameNestedInput = {
  create?: Prisma.XOR<Prisma.BonusDetailCreateWithoutGameInput, Prisma.BonusDetailUncheckedCreateWithoutGameInput> | Prisma.BonusDetailCreateWithoutGameInput[] | Prisma.BonusDetailUncheckedCreateWithoutGameInput[]
  connectOrCreate?: Prisma.BonusDetailCreateOrConnectWithoutGameInput | Prisma.BonusDetailCreateOrConnectWithoutGameInput[]
  upsert?: Prisma.BonusDetailUpsertWithWhereUniqueWithoutGameInput | Prisma.BonusDetailUpsertWithWhereUniqueWithoutGameInput[]
  createMany?: Prisma.BonusDetailCreateManyGameInputEnvelope
  set?: Prisma.BonusDetailWhereUniqueInput | Prisma.BonusDetailWhereUniqueInput[]
  disconnect?: Prisma.BonusDetailWhereUniqueInput | Prisma.BonusDetailWhereUniqueInput[]
  delete?: Prisma.BonusDetailWhereUniqueInput | Prisma.BonusDetailWhereUniqueInput[]
  connect?: Prisma.BonusDetailWhereUniqueInput | Prisma.BonusDetailWhereUniqueInput[]
  update?: Prisma.BonusDetailUpdateWithWhereUniqueWithoutGameInput | Prisma.BonusDetailUpdateWithWhereUniqueWithoutGameInput[]
  updateMany?: Prisma.BonusDetailUpdateManyWithWhereWithoutGameInput | Prisma.BonusDetailUpdateManyWithWhereWithoutGameInput[]
  deleteMany?: Prisma.BonusDetailScalarWhereInput | Prisma.BonusDetailScalarWhereInput[]
}

export type BonusDetailUncheckedUpdateManyWithoutGameNestedInput = {
  create?: Prisma.XOR<Prisma.BonusDetailCreateWithoutGameInput, Prisma.BonusDetailUncheckedCreateWithoutGameInput> | Prisma.BonusDetailCreateWithoutGameInput[] | Prisma.BonusDetailUncheckedCreateWithoutGameInput[]
  connectOrCreate?: Prisma.BonusDetailCreateOrConnectWithoutGameInput | Prisma.BonusDetailCreateOrConnectWithoutGameInput[]
  upsert?: Prisma.BonusDetailUpsertWithWhereUniqueWithoutGameInput | Prisma.BonusDetailUpsertWithWhereUniqueWithoutGameInput[]
  createMany?: Prisma.BonusDetailCreateManyGameInputEnvelope
  set?: Prisma.BonusDetailWhereUniqueInput | Prisma.BonusDetailWhereUniqueInput[]
  disconnect?: Prisma.BonusDetailWhereUniqueInput | Prisma.BonusDetailWhereUniqueInput[]
  delete?: Prisma.BonusDetailWhereUniqueInput | Prisma.BonusDetailWhereUniqueInput[]
  connect?: Prisma.BonusDetailWhereUniqueInput | Prisma.BonusDetailWhereUniqueInput[]
  update?: Prisma.BonusDetailUpdateWithWhereUniqueWithoutGameInput | Prisma.BonusDetailUpdateWithWhereUniqueWithoutGameInput[]
  updateMany?: Prisma.BonusDetailUpdateManyWithWhereWithoutGameInput | Prisma.BonusDetailUpdateManyWithWhereWithoutGameInput[]
  deleteMany?: Prisma.BonusDetailScalarWhereInput | Prisma.BonusDetailScalarWhereInput[]
}

export type BonusDetailCreateNestedOneWithoutTransactionInput = {
  create?: Prisma.XOR<Prisma.BonusDetailCreateWithoutTransactionInput, Prisma.BonusDetailUncheckedCreateWithoutTransactionInput>
  connectOrCreate?: Prisma.BonusDetailCreateOrConnectWithoutTransactionInput
  connect?: Prisma.BonusDetailWhereUniqueInput
}

export type BonusDetailUncheckedCreateNestedOneWithoutTransactionInput = {
  create?: Prisma.XOR<Prisma.BonusDetailCreateWithoutTransactionInput, Prisma.BonusDetailUncheckedCreateWithoutTransactionInput>
  connectOrCreate?: Prisma.BonusDetailCreateOrConnectWithoutTransactionInput
  connect?: Prisma.BonusDetailWhereUniqueInput
}

export type BonusDetailUpdateOneWithoutTransactionNestedInput = {
  create?: Prisma.XOR<Prisma.BonusDetailCreateWithoutTransactionInput, Prisma.BonusDetailUncheckedCreateWithoutTransactionInput>
  connectOrCreate?: Prisma.BonusDetailCreateOrConnectWithoutTransactionInput
  upsert?: Prisma.BonusDetailUpsertWithoutTransactionInput
  disconnect?: Prisma.BonusDetailWhereInput | boolean
  delete?: Prisma.BonusDetailWhereInput | boolean
  connect?: Prisma.BonusDetailWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BonusDetailUpdateToOneWithWhereWithoutTransactionInput, Prisma.BonusDetailUpdateWithoutTransactionInput>, Prisma.BonusDetailUncheckedUpdateWithoutTransactionInput>
}

export type BonusDetailUncheckedUpdateOneWithoutTransactionNestedInput = {
  create?: Prisma.XOR<Prisma.BonusDetailCreateWithoutTransactionInput, Prisma.BonusDetailUncheckedCreateWithoutTransactionInput>
  connectOrCreate?: Prisma.BonusDetailCreateOrConnectWithoutTransactionInput
  upsert?: Prisma.BonusDetailUpsertWithoutTransactionInput
  disconnect?: Prisma.BonusDetailWhereInput | boolean
  delete?: Prisma.BonusDetailWhereInput | boolean
  connect?: Prisma.BonusDetailWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BonusDetailUpdateToOneWithWhereWithoutTransactionInput, Prisma.BonusDetailUpdateWithoutTransactionInput>, Prisma.BonusDetailUncheckedUpdateWithoutTransactionInput>
}

export type EnumBonusTypeFieldUpdateOperationsInput = {
  set?: $Enums.BonusType
}

export type BonusDetailCreateWithoutGameInput = {
  id?: bigint | number
  createdAt?: Date | string
  transactionTime: Date | string
  aggregatorType: $Enums.GameAggregatorType
  provider: $Enums.GameProvider
  bonusType: $Enums.BonusType
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  aggregatorPromotionId?: string | null
  aggregatorRoundId?: string | null
  aggregatorWagerId?: string | null
  aggregatorTransactionId?: string | null
  aggregatorFreespinId?: string | null
  aggregatorSessionId?: string | null
  isEndRound?: boolean | null
  description?: string | null
  transaction: Prisma.TransactionCreateNestedOneWithoutBonusDetailInput
}

export type BonusDetailUncheckedCreateWithoutGameInput = {
  id?: bigint | number
  createdAt?: Date | string
  transactionTime: Date | string
  aggregatorType: $Enums.GameAggregatorType
  provider: $Enums.GameProvider
  bonusType: $Enums.BonusType
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  aggregatorPromotionId?: string | null
  aggregatorRoundId?: string | null
  aggregatorWagerId?: string | null
  aggregatorTransactionId?: string | null
  aggregatorFreespinId?: string | null
  aggregatorSessionId?: string | null
  isEndRound?: boolean | null
  description?: string | null
  transactionId: bigint | number
}

export type BonusDetailCreateOrConnectWithoutGameInput = {
  where: Prisma.BonusDetailWhereUniqueInput
  create: Prisma.XOR<Prisma.BonusDetailCreateWithoutGameInput, Prisma.BonusDetailUncheckedCreateWithoutGameInput>
}

export type BonusDetailCreateManyGameInputEnvelope = {
  data: Prisma.BonusDetailCreateManyGameInput | Prisma.BonusDetailCreateManyGameInput[]
  skipDuplicates?: boolean
}

export type BonusDetailUpsertWithWhereUniqueWithoutGameInput = {
  where: Prisma.BonusDetailWhereUniqueInput
  update: Prisma.XOR<Prisma.BonusDetailUpdateWithoutGameInput, Prisma.BonusDetailUncheckedUpdateWithoutGameInput>
  create: Prisma.XOR<Prisma.BonusDetailCreateWithoutGameInput, Prisma.BonusDetailUncheckedCreateWithoutGameInput>
}

export type BonusDetailUpdateWithWhereUniqueWithoutGameInput = {
  where: Prisma.BonusDetailWhereUniqueInput
  data: Prisma.XOR<Prisma.BonusDetailUpdateWithoutGameInput, Prisma.BonusDetailUncheckedUpdateWithoutGameInput>
}

export type BonusDetailUpdateManyWithWhereWithoutGameInput = {
  where: Prisma.BonusDetailScalarWhereInput
  data: Prisma.XOR<Prisma.BonusDetailUpdateManyMutationInput, Prisma.BonusDetailUncheckedUpdateManyWithoutGameInput>
}

export type BonusDetailScalarWhereInput = {
  AND?: Prisma.BonusDetailScalarWhereInput | Prisma.BonusDetailScalarWhereInput[]
  OR?: Prisma.BonusDetailScalarWhereInput[]
  NOT?: Prisma.BonusDetailScalarWhereInput | Prisma.BonusDetailScalarWhereInput[]
  id?: Prisma.BigIntFilter<"BonusDetail"> | bigint | number
  createdAt?: Prisma.DateTimeFilter<"BonusDetail"> | Date | string
  transactionTime?: Prisma.DateTimeFilter<"BonusDetail"> | Date | string
  aggregatorType?: Prisma.EnumGameAggregatorTypeFilter<"BonusDetail"> | $Enums.GameAggregatorType
  provider?: Prisma.EnumGameProviderFilter<"BonusDetail"> | $Enums.GameProvider
  bonusType?: Prisma.EnumBonusTypeFilter<"BonusDetail"> | $Enums.BonusType
  amount?: Prisma.DecimalFilter<"BonusDetail"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  aggregatorPromotionId?: Prisma.StringNullableFilter<"BonusDetail"> | string | null
  aggregatorRoundId?: Prisma.StringNullableFilter<"BonusDetail"> | string | null
  aggregatorWagerId?: Prisma.StringNullableFilter<"BonusDetail"> | string | null
  aggregatorTransactionId?: Prisma.StringNullableFilter<"BonusDetail"> | string | null
  aggregatorFreespinId?: Prisma.StringNullableFilter<"BonusDetail"> | string | null
  aggregatorSessionId?: Prisma.StringNullableFilter<"BonusDetail"> | string | null
  isEndRound?: Prisma.BoolNullableFilter<"BonusDetail"> | boolean | null
  description?: Prisma.StringNullableFilter<"BonusDetail"> | string | null
  gameId?: Prisma.IntNullableFilter<"BonusDetail"> | number | null
  transactionId?: Prisma.BigIntFilter<"BonusDetail"> | bigint | number
}

export type BonusDetailCreateWithoutTransactionInput = {
  id?: bigint | number
  createdAt?: Date | string
  transactionTime: Date | string
  aggregatorType: $Enums.GameAggregatorType
  provider: $Enums.GameProvider
  bonusType: $Enums.BonusType
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  aggregatorPromotionId?: string | null
  aggregatorRoundId?: string | null
  aggregatorWagerId?: string | null
  aggregatorTransactionId?: string | null
  aggregatorFreespinId?: string | null
  aggregatorSessionId?: string | null
  isEndRound?: boolean | null
  description?: string | null
  game?: Prisma.GameCreateNestedOneWithoutBonusDetailsInput
}

export type BonusDetailUncheckedCreateWithoutTransactionInput = {
  id?: bigint | number
  createdAt?: Date | string
  transactionTime: Date | string
  aggregatorType: $Enums.GameAggregatorType
  provider: $Enums.GameProvider
  bonusType: $Enums.BonusType
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  aggregatorPromotionId?: string | null
  aggregatorRoundId?: string | null
  aggregatorWagerId?: string | null
  aggregatorTransactionId?: string | null
  aggregatorFreespinId?: string | null
  aggregatorSessionId?: string | null
  isEndRound?: boolean | null
  description?: string | null
  gameId?: number | null
}

export type BonusDetailCreateOrConnectWithoutTransactionInput = {
  where: Prisma.BonusDetailWhereUniqueInput
  create: Prisma.XOR<Prisma.BonusDetailCreateWithoutTransactionInput, Prisma.BonusDetailUncheckedCreateWithoutTransactionInput>
}

export type BonusDetailUpsertWithoutTransactionInput = {
  update: Prisma.XOR<Prisma.BonusDetailUpdateWithoutTransactionInput, Prisma.BonusDetailUncheckedUpdateWithoutTransactionInput>
  create: Prisma.XOR<Prisma.BonusDetailCreateWithoutTransactionInput, Prisma.BonusDetailUncheckedCreateWithoutTransactionInput>
  where?: Prisma.BonusDetailWhereInput
}

export type BonusDetailUpdateToOneWithWhereWithoutTransactionInput = {
  where?: Prisma.BonusDetailWhereInput
  data: Prisma.XOR<Prisma.BonusDetailUpdateWithoutTransactionInput, Prisma.BonusDetailUncheckedUpdateWithoutTransactionInput>
}

export type BonusDetailUpdateWithoutTransactionInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  transactionTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  aggregatorType?: Prisma.EnumGameAggregatorTypeFieldUpdateOperationsInput | $Enums.GameAggregatorType
  provider?: Prisma.EnumGameProviderFieldUpdateOperationsInput | $Enums.GameProvider
  bonusType?: Prisma.EnumBonusTypeFieldUpdateOperationsInput | $Enums.BonusType
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  aggregatorPromotionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorRoundId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorWagerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorTransactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorFreespinId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isEndRound?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  game?: Prisma.GameUpdateOneWithoutBonusDetailsNestedInput
}

export type BonusDetailUncheckedUpdateWithoutTransactionInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  transactionTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  aggregatorType?: Prisma.EnumGameAggregatorTypeFieldUpdateOperationsInput | $Enums.GameAggregatorType
  provider?: Prisma.EnumGameProviderFieldUpdateOperationsInput | $Enums.GameProvider
  bonusType?: Prisma.EnumBonusTypeFieldUpdateOperationsInput | $Enums.BonusType
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  aggregatorPromotionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorRoundId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorWagerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorTransactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorFreespinId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isEndRound?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  gameId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type BonusDetailCreateManyGameInput = {
  id?: bigint | number
  createdAt?: Date | string
  transactionTime: Date | string
  aggregatorType: $Enums.GameAggregatorType
  provider: $Enums.GameProvider
  bonusType: $Enums.BonusType
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  aggregatorPromotionId?: string | null
  aggregatorRoundId?: string | null
  aggregatorWagerId?: string | null
  aggregatorTransactionId?: string | null
  aggregatorFreespinId?: string | null
  aggregatorSessionId?: string | null
  isEndRound?: boolean | null
  description?: string | null
  transactionId: bigint | number
}

export type BonusDetailUpdateWithoutGameInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  transactionTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  aggregatorType?: Prisma.EnumGameAggregatorTypeFieldUpdateOperationsInput | $Enums.GameAggregatorType
  provider?: Prisma.EnumGameProviderFieldUpdateOperationsInput | $Enums.GameProvider
  bonusType?: Prisma.EnumBonusTypeFieldUpdateOperationsInput | $Enums.BonusType
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  aggregatorPromotionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorRoundId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorWagerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorTransactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorFreespinId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isEndRound?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transaction?: Prisma.TransactionUpdateOneRequiredWithoutBonusDetailNestedInput
}

export type BonusDetailUncheckedUpdateWithoutGameInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  transactionTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  aggregatorType?: Prisma.EnumGameAggregatorTypeFieldUpdateOperationsInput | $Enums.GameAggregatorType
  provider?: Prisma.EnumGameProviderFieldUpdateOperationsInput | $Enums.GameProvider
  bonusType?: Prisma.EnumBonusTypeFieldUpdateOperationsInput | $Enums.BonusType
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  aggregatorPromotionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorRoundId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorWagerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorTransactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorFreespinId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isEndRound?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transactionId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type BonusDetailUncheckedUpdateManyWithoutGameInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  transactionTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  aggregatorType?: Prisma.EnumGameAggregatorTypeFieldUpdateOperationsInput | $Enums.GameAggregatorType
  provider?: Prisma.EnumGameProviderFieldUpdateOperationsInput | $Enums.GameProvider
  bonusType?: Prisma.EnumBonusTypeFieldUpdateOperationsInput | $Enums.BonusType
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  aggregatorPromotionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorRoundId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorWagerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorTransactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorFreespinId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aggregatorSessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isEndRound?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transactionId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}



export type BonusDetailSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  transactionTime?: boolean
  aggregatorType?: boolean
  provider?: boolean
  bonusType?: boolean
  amount?: boolean
  aggregatorPromotionId?: boolean
  aggregatorRoundId?: boolean
  aggregatorWagerId?: boolean
  aggregatorTransactionId?: boolean
  aggregatorFreespinId?: boolean
  aggregatorSessionId?: boolean
  isEndRound?: boolean
  description?: boolean
  gameId?: boolean
  transactionId?: boolean
  game?: boolean | Prisma.BonusDetail$gameArgs<ExtArgs>
  transaction?: boolean | Prisma.TransactionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bonusDetail"]>

export type BonusDetailSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  transactionTime?: boolean
  aggregatorType?: boolean
  provider?: boolean
  bonusType?: boolean
  amount?: boolean
  aggregatorPromotionId?: boolean
  aggregatorRoundId?: boolean
  aggregatorWagerId?: boolean
  aggregatorTransactionId?: boolean
  aggregatorFreespinId?: boolean
  aggregatorSessionId?: boolean
  isEndRound?: boolean
  description?: boolean
  gameId?: boolean
  transactionId?: boolean
  game?: boolean | Prisma.BonusDetail$gameArgs<ExtArgs>
  transaction?: boolean | Prisma.TransactionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bonusDetail"]>

export type BonusDetailSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  transactionTime?: boolean
  aggregatorType?: boolean
  provider?: boolean
  bonusType?: boolean
  amount?: boolean
  aggregatorPromotionId?: boolean
  aggregatorRoundId?: boolean
  aggregatorWagerId?: boolean
  aggregatorTransactionId?: boolean
  aggregatorFreespinId?: boolean
  aggregatorSessionId?: boolean
  isEndRound?: boolean
  description?: boolean
  gameId?: boolean
  transactionId?: boolean
  game?: boolean | Prisma.BonusDetail$gameArgs<ExtArgs>
  transaction?: boolean | Prisma.TransactionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bonusDetail"]>

export type BonusDetailSelectScalar = {
  id?: boolean
  createdAt?: boolean
  transactionTime?: boolean
  aggregatorType?: boolean
  provider?: boolean
  bonusType?: boolean
  amount?: boolean
  aggregatorPromotionId?: boolean
  aggregatorRoundId?: boolean
  aggregatorWagerId?: boolean
  aggregatorTransactionId?: boolean
  aggregatorFreespinId?: boolean
  aggregatorSessionId?: boolean
  isEndRound?: boolean
  description?: boolean
  gameId?: boolean
  transactionId?: boolean
}

export type BonusDetailOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "transactionTime" | "aggregatorType" | "provider" | "bonusType" | "amount" | "aggregatorPromotionId" | "aggregatorRoundId" | "aggregatorWagerId" | "aggregatorTransactionId" | "aggregatorFreespinId" | "aggregatorSessionId" | "isEndRound" | "description" | "gameId" | "transactionId", ExtArgs["result"]["bonusDetail"]>
export type BonusDetailInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  game?: boolean | Prisma.BonusDetail$gameArgs<ExtArgs>
  transaction?: boolean | Prisma.TransactionDefaultArgs<ExtArgs>
}
export type BonusDetailIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  game?: boolean | Prisma.BonusDetail$gameArgs<ExtArgs>
  transaction?: boolean | Prisma.TransactionDefaultArgs<ExtArgs>
}
export type BonusDetailIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  game?: boolean | Prisma.BonusDetail$gameArgs<ExtArgs>
  transaction?: boolean | Prisma.TransactionDefaultArgs<ExtArgs>
}

export type $BonusDetailPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BonusDetail"
  objects: {
    game: Prisma.$GamePayload<ExtArgs> | null
    transaction: Prisma.$TransactionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: bigint
    createdAt: Date
    transactionTime: Date
    aggregatorType: $Enums.GameAggregatorType
    provider: $Enums.GameProvider
    bonusType: $Enums.BonusType
    amount: runtime.Decimal
    aggregatorPromotionId: string | null
    aggregatorRoundId: string | null
    aggregatorWagerId: string | null
    aggregatorTransactionId: string | null
    aggregatorFreespinId: string | null
    aggregatorSessionId: string | null
    isEndRound: boolean | null
    description: string | null
    gameId: number | null
    transactionId: bigint
  }, ExtArgs["result"]["bonusDetail"]>
  composites: {}
}

export type BonusDetailGetPayload<S extends boolean | null | undefined | BonusDetailDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BonusDetailPayload, S>

export type BonusDetailCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BonusDetailFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BonusDetailCountAggregateInputType | true
  }

export interface BonusDetailDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BonusDetail'], meta: { name: 'BonusDetail' } }
  /**
   * Find zero or one BonusDetail that matches the filter.
   * @param {BonusDetailFindUniqueArgs} args - Arguments to find a BonusDetail
   * @example
   * // Get one BonusDetail
   * const bonusDetail = await prisma.bonusDetail.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BonusDetailFindUniqueArgs>(args: Prisma.SelectSubset<T, BonusDetailFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BonusDetailClient<runtime.Types.Result.GetResult<Prisma.$BonusDetailPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BonusDetail that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BonusDetailFindUniqueOrThrowArgs} args - Arguments to find a BonusDetail
   * @example
   * // Get one BonusDetail
   * const bonusDetail = await prisma.bonusDetail.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BonusDetailFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BonusDetailFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BonusDetailClient<runtime.Types.Result.GetResult<Prisma.$BonusDetailPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BonusDetail that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BonusDetailFindFirstArgs} args - Arguments to find a BonusDetail
   * @example
   * // Get one BonusDetail
   * const bonusDetail = await prisma.bonusDetail.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BonusDetailFindFirstArgs>(args?: Prisma.SelectSubset<T, BonusDetailFindFirstArgs<ExtArgs>>): Prisma.Prisma__BonusDetailClient<runtime.Types.Result.GetResult<Prisma.$BonusDetailPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BonusDetail that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BonusDetailFindFirstOrThrowArgs} args - Arguments to find a BonusDetail
   * @example
   * // Get one BonusDetail
   * const bonusDetail = await prisma.bonusDetail.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BonusDetailFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BonusDetailFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BonusDetailClient<runtime.Types.Result.GetResult<Prisma.$BonusDetailPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BonusDetails that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BonusDetailFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BonusDetails
   * const bonusDetails = await prisma.bonusDetail.findMany()
   * 
   * // Get first 10 BonusDetails
   * const bonusDetails = await prisma.bonusDetail.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const bonusDetailWithIdOnly = await prisma.bonusDetail.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BonusDetailFindManyArgs>(args?: Prisma.SelectSubset<T, BonusDetailFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BonusDetailPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BonusDetail.
   * @param {BonusDetailCreateArgs} args - Arguments to create a BonusDetail.
   * @example
   * // Create one BonusDetail
   * const BonusDetail = await prisma.bonusDetail.create({
   *   data: {
   *     // ... data to create a BonusDetail
   *   }
   * })
   * 
   */
  create<T extends BonusDetailCreateArgs>(args: Prisma.SelectSubset<T, BonusDetailCreateArgs<ExtArgs>>): Prisma.Prisma__BonusDetailClient<runtime.Types.Result.GetResult<Prisma.$BonusDetailPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BonusDetails.
   * @param {BonusDetailCreateManyArgs} args - Arguments to create many BonusDetails.
   * @example
   * // Create many BonusDetails
   * const bonusDetail = await prisma.bonusDetail.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BonusDetailCreateManyArgs>(args?: Prisma.SelectSubset<T, BonusDetailCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BonusDetails and returns the data saved in the database.
   * @param {BonusDetailCreateManyAndReturnArgs} args - Arguments to create many BonusDetails.
   * @example
   * // Create many BonusDetails
   * const bonusDetail = await prisma.bonusDetail.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BonusDetails and only return the `id`
   * const bonusDetailWithIdOnly = await prisma.bonusDetail.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BonusDetailCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BonusDetailCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BonusDetailPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BonusDetail.
   * @param {BonusDetailDeleteArgs} args - Arguments to delete one BonusDetail.
   * @example
   * // Delete one BonusDetail
   * const BonusDetail = await prisma.bonusDetail.delete({
   *   where: {
   *     // ... filter to delete one BonusDetail
   *   }
   * })
   * 
   */
  delete<T extends BonusDetailDeleteArgs>(args: Prisma.SelectSubset<T, BonusDetailDeleteArgs<ExtArgs>>): Prisma.Prisma__BonusDetailClient<runtime.Types.Result.GetResult<Prisma.$BonusDetailPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BonusDetail.
   * @param {BonusDetailUpdateArgs} args - Arguments to update one BonusDetail.
   * @example
   * // Update one BonusDetail
   * const bonusDetail = await prisma.bonusDetail.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BonusDetailUpdateArgs>(args: Prisma.SelectSubset<T, BonusDetailUpdateArgs<ExtArgs>>): Prisma.Prisma__BonusDetailClient<runtime.Types.Result.GetResult<Prisma.$BonusDetailPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BonusDetails.
   * @param {BonusDetailDeleteManyArgs} args - Arguments to filter BonusDetails to delete.
   * @example
   * // Delete a few BonusDetails
   * const { count } = await prisma.bonusDetail.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BonusDetailDeleteManyArgs>(args?: Prisma.SelectSubset<T, BonusDetailDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BonusDetails.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BonusDetailUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BonusDetails
   * const bonusDetail = await prisma.bonusDetail.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BonusDetailUpdateManyArgs>(args: Prisma.SelectSubset<T, BonusDetailUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BonusDetails and returns the data updated in the database.
   * @param {BonusDetailUpdateManyAndReturnArgs} args - Arguments to update many BonusDetails.
   * @example
   * // Update many BonusDetails
   * const bonusDetail = await prisma.bonusDetail.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BonusDetails and only return the `id`
   * const bonusDetailWithIdOnly = await prisma.bonusDetail.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BonusDetailUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BonusDetailUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BonusDetailPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BonusDetail.
   * @param {BonusDetailUpsertArgs} args - Arguments to update or create a BonusDetail.
   * @example
   * // Update or create a BonusDetail
   * const bonusDetail = await prisma.bonusDetail.upsert({
   *   create: {
   *     // ... data to create a BonusDetail
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BonusDetail we want to update
   *   }
   * })
   */
  upsert<T extends BonusDetailUpsertArgs>(args: Prisma.SelectSubset<T, BonusDetailUpsertArgs<ExtArgs>>): Prisma.Prisma__BonusDetailClient<runtime.Types.Result.GetResult<Prisma.$BonusDetailPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BonusDetails.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BonusDetailCountArgs} args - Arguments to filter BonusDetails to count.
   * @example
   * // Count the number of BonusDetails
   * const count = await prisma.bonusDetail.count({
   *   where: {
   *     // ... the filter for the BonusDetails we want to count
   *   }
   * })
  **/
  count<T extends BonusDetailCountArgs>(
    args?: Prisma.Subset<T, BonusDetailCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BonusDetailCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BonusDetail.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BonusDetailAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BonusDetailAggregateArgs>(args: Prisma.Subset<T, BonusDetailAggregateArgs>): Prisma.PrismaPromise<GetBonusDetailAggregateType<T>>

  /**
   * Group by BonusDetail.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BonusDetailGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BonusDetailGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BonusDetailGroupByArgs['orderBy'] }
      : { orderBy?: BonusDetailGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BonusDetailGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBonusDetailGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BonusDetail model
 */
readonly fields: BonusDetailFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BonusDetail.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BonusDetailClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  game<T extends Prisma.BonusDetail$gameArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BonusDetail$gameArgs<ExtArgs>>): Prisma.Prisma__GameClient<runtime.Types.Result.GetResult<Prisma.$GamePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  transaction<T extends Prisma.TransactionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TransactionDefaultArgs<ExtArgs>>): Prisma.Prisma__TransactionClient<runtime.Types.Result.GetResult<Prisma.$TransactionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BonusDetail model
 */
export interface BonusDetailFieldRefs {
  readonly id: Prisma.FieldRef<"BonusDetail", 'BigInt'>
  readonly createdAt: Prisma.FieldRef<"BonusDetail", 'DateTime'>
  readonly transactionTime: Prisma.FieldRef<"BonusDetail", 'DateTime'>
  readonly aggregatorType: Prisma.FieldRef<"BonusDetail", 'GameAggregatorType'>
  readonly provider: Prisma.FieldRef<"BonusDetail", 'GameProvider'>
  readonly bonusType: Prisma.FieldRef<"BonusDetail", 'BonusType'>
  readonly amount: Prisma.FieldRef<"BonusDetail", 'Decimal'>
  readonly aggregatorPromotionId: Prisma.FieldRef<"BonusDetail", 'String'>
  readonly aggregatorRoundId: Prisma.FieldRef<"BonusDetail", 'String'>
  readonly aggregatorWagerId: Prisma.FieldRef<"BonusDetail", 'String'>
  readonly aggregatorTransactionId: Prisma.FieldRef<"BonusDetail", 'String'>
  readonly aggregatorFreespinId: Prisma.FieldRef<"BonusDetail", 'String'>
  readonly aggregatorSessionId: Prisma.FieldRef<"BonusDetail", 'String'>
  readonly isEndRound: Prisma.FieldRef<"BonusDetail", 'Boolean'>
  readonly description: Prisma.FieldRef<"BonusDetail", 'String'>
  readonly gameId: Prisma.FieldRef<"BonusDetail", 'Int'>
  readonly transactionId: Prisma.FieldRef<"BonusDetail", 'BigInt'>
}
    

// Custom InputTypes
/**
 * BonusDetail findUnique
 */
export type BonusDetailFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BonusDetail
   */
  select?: Prisma.BonusDetailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BonusDetail
   */
  omit?: Prisma.BonusDetailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BonusDetailInclude<ExtArgs> | null
  /**
   * Filter, which BonusDetail to fetch.
   */
  where: Prisma.BonusDetailWhereUniqueInput
}

/**
 * BonusDetail findUniqueOrThrow
 */
export type BonusDetailFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BonusDetail
   */
  select?: Prisma.BonusDetailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BonusDetail
   */
  omit?: Prisma.BonusDetailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BonusDetailInclude<ExtArgs> | null
  /**
   * Filter, which BonusDetail to fetch.
   */
  where: Prisma.BonusDetailWhereUniqueInput
}

/**
 * BonusDetail findFirst
 */
export type BonusDetailFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BonusDetail
   */
  select?: Prisma.BonusDetailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BonusDetail
   */
  omit?: Prisma.BonusDetailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BonusDetailInclude<ExtArgs> | null
  /**
   * Filter, which BonusDetail to fetch.
   */
  where?: Prisma.BonusDetailWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BonusDetails to fetch.
   */
  orderBy?: Prisma.BonusDetailOrderByWithRelationInput | Prisma.BonusDetailOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BonusDetails.
   */
  cursor?: Prisma.BonusDetailWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BonusDetails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BonusDetails.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BonusDetails.
   */
  distinct?: Prisma.BonusDetailScalarFieldEnum | Prisma.BonusDetailScalarFieldEnum[]
}

/**
 * BonusDetail findFirstOrThrow
 */
export type BonusDetailFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BonusDetail
   */
  select?: Prisma.BonusDetailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BonusDetail
   */
  omit?: Prisma.BonusDetailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BonusDetailInclude<ExtArgs> | null
  /**
   * Filter, which BonusDetail to fetch.
   */
  where?: Prisma.BonusDetailWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BonusDetails to fetch.
   */
  orderBy?: Prisma.BonusDetailOrderByWithRelationInput | Prisma.BonusDetailOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BonusDetails.
   */
  cursor?: Prisma.BonusDetailWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BonusDetails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BonusDetails.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BonusDetails.
   */
  distinct?: Prisma.BonusDetailScalarFieldEnum | Prisma.BonusDetailScalarFieldEnum[]
}

/**
 * BonusDetail findMany
 */
export type BonusDetailFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BonusDetail
   */
  select?: Prisma.BonusDetailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BonusDetail
   */
  omit?: Prisma.BonusDetailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BonusDetailInclude<ExtArgs> | null
  /**
   * Filter, which BonusDetails to fetch.
   */
  where?: Prisma.BonusDetailWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BonusDetails to fetch.
   */
  orderBy?: Prisma.BonusDetailOrderByWithRelationInput | Prisma.BonusDetailOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BonusDetails.
   */
  cursor?: Prisma.BonusDetailWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BonusDetails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BonusDetails.
   */
  skip?: number
  distinct?: Prisma.BonusDetailScalarFieldEnum | Prisma.BonusDetailScalarFieldEnum[]
}

/**
 * BonusDetail create
 */
export type BonusDetailCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BonusDetail
   */
  select?: Prisma.BonusDetailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BonusDetail
   */
  omit?: Prisma.BonusDetailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BonusDetailInclude<ExtArgs> | null
  /**
   * The data needed to create a BonusDetail.
   */
  data: Prisma.XOR<Prisma.BonusDetailCreateInput, Prisma.BonusDetailUncheckedCreateInput>
}

/**
 * BonusDetail createMany
 */
export type BonusDetailCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BonusDetails.
   */
  data: Prisma.BonusDetailCreateManyInput | Prisma.BonusDetailCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BonusDetail createManyAndReturn
 */
export type BonusDetailCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BonusDetail
   */
  select?: Prisma.BonusDetailSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BonusDetail
   */
  omit?: Prisma.BonusDetailOmit<ExtArgs> | null
  /**
   * The data used to create many BonusDetails.
   */
  data: Prisma.BonusDetailCreateManyInput | Prisma.BonusDetailCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BonusDetailIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * BonusDetail update
 */
export type BonusDetailUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BonusDetail
   */
  select?: Prisma.BonusDetailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BonusDetail
   */
  omit?: Prisma.BonusDetailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BonusDetailInclude<ExtArgs> | null
  /**
   * The data needed to update a BonusDetail.
   */
  data: Prisma.XOR<Prisma.BonusDetailUpdateInput, Prisma.BonusDetailUncheckedUpdateInput>
  /**
   * Choose, which BonusDetail to update.
   */
  where: Prisma.BonusDetailWhereUniqueInput
}

/**
 * BonusDetail updateMany
 */
export type BonusDetailUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BonusDetails.
   */
  data: Prisma.XOR<Prisma.BonusDetailUpdateManyMutationInput, Prisma.BonusDetailUncheckedUpdateManyInput>
  /**
   * Filter which BonusDetails to update
   */
  where?: Prisma.BonusDetailWhereInput
  /**
   * Limit how many BonusDetails to update.
   */
  limit?: number
}

/**
 * BonusDetail updateManyAndReturn
 */
export type BonusDetailUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BonusDetail
   */
  select?: Prisma.BonusDetailSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BonusDetail
   */
  omit?: Prisma.BonusDetailOmit<ExtArgs> | null
  /**
   * The data used to update BonusDetails.
   */
  data: Prisma.XOR<Prisma.BonusDetailUpdateManyMutationInput, Prisma.BonusDetailUncheckedUpdateManyInput>
  /**
   * Filter which BonusDetails to update
   */
  where?: Prisma.BonusDetailWhereInput
  /**
   * Limit how many BonusDetails to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BonusDetailIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * BonusDetail upsert
 */
export type BonusDetailUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BonusDetail
   */
  select?: Prisma.BonusDetailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BonusDetail
   */
  omit?: Prisma.BonusDetailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BonusDetailInclude<ExtArgs> | null
  /**
   * The filter to search for the BonusDetail to update in case it exists.
   */
  where: Prisma.BonusDetailWhereUniqueInput
  /**
   * In case the BonusDetail found by the `where` argument doesn't exist, create a new BonusDetail with this data.
   */
  create: Prisma.XOR<Prisma.BonusDetailCreateInput, Prisma.BonusDetailUncheckedCreateInput>
  /**
   * In case the BonusDetail was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BonusDetailUpdateInput, Prisma.BonusDetailUncheckedUpdateInput>
}

/**
 * BonusDetail delete
 */
export type BonusDetailDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BonusDetail
   */
  select?: Prisma.BonusDetailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BonusDetail
   */
  omit?: Prisma.BonusDetailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BonusDetailInclude<ExtArgs> | null
  /**
   * Filter which BonusDetail to delete.
   */
  where: Prisma.BonusDetailWhereUniqueInput
}

/**
 * BonusDetail deleteMany
 */
export type BonusDetailDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BonusDetails to delete
   */
  where?: Prisma.BonusDetailWhereInput
  /**
   * Limit how many BonusDetails to delete.
   */
  limit?: number
}

/**
 * BonusDetail.game
 */
export type BonusDetail$gameArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Game
   */
  select?: Prisma.GameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Game
   */
  omit?: Prisma.GameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GameInclude<ExtArgs> | null
  where?: Prisma.GameWhereInput
}

/**
 * BonusDetail without action
 */
export type BonusDetailDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BonusDetail
   */
  select?: Prisma.BonusDetailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BonusDetail
   */
  omit?: Prisma.BonusDetailOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BonusDetailInclude<ExtArgs> | null
}
