
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DailyCompEarning` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model DailyCompEarning
 * 
 */
export type DailyCompEarningModel = runtime.Types.Result.DefaultSelection<Prisma.$DailyCompEarningPayload>

export type AggregateDailyCompEarning = {
  _count: DailyCompEarningCountAggregateOutputType | null
  _avg: DailyCompEarningAvgAggregateOutputType | null
  _sum: DailyCompEarningSumAggregateOutputType | null
  _min: DailyCompEarningMinAggregateOutputType | null
  _max: DailyCompEarningMaxAggregateOutputType | null
}

export type DailyCompEarningAvgAggregateOutputType = {
  id: number | null
  totalContribution: runtime.Decimal | null
  compEarned: runtime.Decimal | null
}

export type DailyCompEarningSumAggregateOutputType = {
  id: number | null
  totalContribution: runtime.Decimal | null
  compEarned: runtime.Decimal | null
}

export type DailyCompEarningMinAggregateOutputType = {
  id: number | null
  userId: string | null
  earningDate: Date | null
  totalContribution: runtime.Decimal | null
  compEarned: runtime.Decimal | null
  isProcessed: boolean | null
  processedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type DailyCompEarningMaxAggregateOutputType = {
  id: number | null
  userId: string | null
  earningDate: Date | null
  totalContribution: runtime.Decimal | null
  compEarned: runtime.Decimal | null
  isProcessed: boolean | null
  processedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type DailyCompEarningCountAggregateOutputType = {
  id: number
  userId: number
  earningDate: number
  totalContribution: number
  compEarned: number
  isProcessed: number
  processedAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type DailyCompEarningAvgAggregateInputType = {
  id?: true
  totalContribution?: true
  compEarned?: true
}

export type DailyCompEarningSumAggregateInputType = {
  id?: true
  totalContribution?: true
  compEarned?: true
}

export type DailyCompEarningMinAggregateInputType = {
  id?: true
  userId?: true
  earningDate?: true
  totalContribution?: true
  compEarned?: true
  isProcessed?: true
  processedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type DailyCompEarningMaxAggregateInputType = {
  id?: true
  userId?: true
  earningDate?: true
  totalContribution?: true
  compEarned?: true
  isProcessed?: true
  processedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type DailyCompEarningCountAggregateInputType = {
  id?: true
  userId?: true
  earningDate?: true
  totalContribution?: true
  compEarned?: true
  isProcessed?: true
  processedAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type DailyCompEarningAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DailyCompEarning to aggregate.
   */
  where?: Prisma.DailyCompEarningWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DailyCompEarnings to fetch.
   */
  orderBy?: Prisma.DailyCompEarningOrderByWithRelationInput | Prisma.DailyCompEarningOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DailyCompEarningWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DailyCompEarnings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DailyCompEarnings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DailyCompEarnings
  **/
  _count?: true | DailyCompEarningCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DailyCompEarningAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DailyCompEarningSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DailyCompEarningMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DailyCompEarningMaxAggregateInputType
}

export type GetDailyCompEarningAggregateType<T extends DailyCompEarningAggregateArgs> = {
      [P in keyof T & keyof AggregateDailyCompEarning]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDailyCompEarning[P]>
    : Prisma.GetScalarType<T[P], AggregateDailyCompEarning[P]>
}




export type DailyCompEarningGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DailyCompEarningWhereInput
  orderBy?: Prisma.DailyCompEarningOrderByWithAggregationInput | Prisma.DailyCompEarningOrderByWithAggregationInput[]
  by: Prisma.DailyCompEarningScalarFieldEnum[] | Prisma.DailyCompEarningScalarFieldEnum
  having?: Prisma.DailyCompEarningScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DailyCompEarningCountAggregateInputType | true
  _avg?: DailyCompEarningAvgAggregateInputType
  _sum?: DailyCompEarningSumAggregateInputType
  _min?: DailyCompEarningMinAggregateInputType
  _max?: DailyCompEarningMaxAggregateInputType
}

export type DailyCompEarningGroupByOutputType = {
  id: number
  userId: string
  earningDate: Date
  totalContribution: runtime.Decimal
  compEarned: runtime.Decimal
  isProcessed: boolean
  processedAt: Date | null
  createdAt: Date
  updatedAt: Date
  _count: DailyCompEarningCountAggregateOutputType | null
  _avg: DailyCompEarningAvgAggregateOutputType | null
  _sum: DailyCompEarningSumAggregateOutputType | null
  _min: DailyCompEarningMinAggregateOutputType | null
  _max: DailyCompEarningMaxAggregateOutputType | null
}

type GetDailyCompEarningGroupByPayload<T extends DailyCompEarningGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DailyCompEarningGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DailyCompEarningGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DailyCompEarningGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DailyCompEarningGroupByOutputType[P]>
      }
    >
  >



export type DailyCompEarningWhereInput = {
  AND?: Prisma.DailyCompEarningWhereInput | Prisma.DailyCompEarningWhereInput[]
  OR?: Prisma.DailyCompEarningWhereInput[]
  NOT?: Prisma.DailyCompEarningWhereInput | Prisma.DailyCompEarningWhereInput[]
  id?: Prisma.IntFilter<"DailyCompEarning"> | number
  userId?: Prisma.StringFilter<"DailyCompEarning"> | string
  earningDate?: Prisma.DateTimeFilter<"DailyCompEarning"> | Date | string
  totalContribution?: Prisma.DecimalFilter<"DailyCompEarning"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  compEarned?: Prisma.DecimalFilter<"DailyCompEarning"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  isProcessed?: Prisma.BoolFilter<"DailyCompEarning"> | boolean
  processedAt?: Prisma.DateTimeNullableFilter<"DailyCompEarning"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"DailyCompEarning"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DailyCompEarning"> | Date | string
  CompTransaction?: Prisma.CompTransactionListRelationFilter
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type DailyCompEarningOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  earningDate?: Prisma.SortOrder
  totalContribution?: Prisma.SortOrder
  compEarned?: Prisma.SortOrder
  isProcessed?: Prisma.SortOrder
  processedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  CompTransaction?: Prisma.CompTransactionOrderByRelationAggregateInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type DailyCompEarningWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  userId_earningDate?: Prisma.DailyCompEarningUserIdEarningDateCompoundUniqueInput
  AND?: Prisma.DailyCompEarningWhereInput | Prisma.DailyCompEarningWhereInput[]
  OR?: Prisma.DailyCompEarningWhereInput[]
  NOT?: Prisma.DailyCompEarningWhereInput | Prisma.DailyCompEarningWhereInput[]
  userId?: Prisma.StringFilter<"DailyCompEarning"> | string
  earningDate?: Prisma.DateTimeFilter<"DailyCompEarning"> | Date | string
  totalContribution?: Prisma.DecimalFilter<"DailyCompEarning"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  compEarned?: Prisma.DecimalFilter<"DailyCompEarning"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  isProcessed?: Prisma.BoolFilter<"DailyCompEarning"> | boolean
  processedAt?: Prisma.DateTimeNullableFilter<"DailyCompEarning"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"DailyCompEarning"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DailyCompEarning"> | Date | string
  CompTransaction?: Prisma.CompTransactionListRelationFilter
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "userId_earningDate">

export type DailyCompEarningOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  earningDate?: Prisma.SortOrder
  totalContribution?: Prisma.SortOrder
  compEarned?: Prisma.SortOrder
  isProcessed?: Prisma.SortOrder
  processedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.DailyCompEarningCountOrderByAggregateInput
  _avg?: Prisma.DailyCompEarningAvgOrderByAggregateInput
  _max?: Prisma.DailyCompEarningMaxOrderByAggregateInput
  _min?: Prisma.DailyCompEarningMinOrderByAggregateInput
  _sum?: Prisma.DailyCompEarningSumOrderByAggregateInput
}

export type DailyCompEarningScalarWhereWithAggregatesInput = {
  AND?: Prisma.DailyCompEarningScalarWhereWithAggregatesInput | Prisma.DailyCompEarningScalarWhereWithAggregatesInput[]
  OR?: Prisma.DailyCompEarningScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DailyCompEarningScalarWhereWithAggregatesInput | Prisma.DailyCompEarningScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"DailyCompEarning"> | number
  userId?: Prisma.StringWithAggregatesFilter<"DailyCompEarning"> | string
  earningDate?: Prisma.DateTimeWithAggregatesFilter<"DailyCompEarning"> | Date | string
  totalContribution?: Prisma.DecimalWithAggregatesFilter<"DailyCompEarning"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  compEarned?: Prisma.DecimalWithAggregatesFilter<"DailyCompEarning"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  isProcessed?: Prisma.BoolWithAggregatesFilter<"DailyCompEarning"> | boolean
  processedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"DailyCompEarning"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"DailyCompEarning"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"DailyCompEarning"> | Date | string
}

export type DailyCompEarningCreateInput = {
  earningDate: Date | string
  totalContribution: runtime.Decimal | runtime.DecimalJsLike | number | string
  compEarned: runtime.Decimal | runtime.DecimalJsLike | number | string
  isProcessed?: boolean
  processedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  CompTransaction?: Prisma.CompTransactionCreateNestedManyWithoutDailyCompEarningInput
  user: Prisma.UserCreateNestedOneWithoutDailyCompEarningInput
}

export type DailyCompEarningUncheckedCreateInput = {
  id?: number
  userId: string
  earningDate: Date | string
  totalContribution: runtime.Decimal | runtime.DecimalJsLike | number | string
  compEarned: runtime.Decimal | runtime.DecimalJsLike | number | string
  isProcessed?: boolean
  processedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  CompTransaction?: Prisma.CompTransactionUncheckedCreateNestedManyWithoutDailyCompEarningInput
}

export type DailyCompEarningUpdateInput = {
  earningDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  totalContribution?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  compEarned?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  isProcessed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  CompTransaction?: Prisma.CompTransactionUpdateManyWithoutDailyCompEarningNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutDailyCompEarningNestedInput
}

export type DailyCompEarningUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  earningDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  totalContribution?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  compEarned?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  isProcessed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  CompTransaction?: Prisma.CompTransactionUncheckedUpdateManyWithoutDailyCompEarningNestedInput
}

export type DailyCompEarningCreateManyInput = {
  id?: number
  userId: string
  earningDate: Date | string
  totalContribution: runtime.Decimal | runtime.DecimalJsLike | number | string
  compEarned: runtime.Decimal | runtime.DecimalJsLike | number | string
  isProcessed?: boolean
  processedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DailyCompEarningUpdateManyMutationInput = {
  earningDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  totalContribution?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  compEarned?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  isProcessed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DailyCompEarningUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  earningDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  totalContribution?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  compEarned?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  isProcessed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DailyCompEarningListRelationFilter = {
  every?: Prisma.DailyCompEarningWhereInput
  some?: Prisma.DailyCompEarningWhereInput
  none?: Prisma.DailyCompEarningWhereInput
}

export type DailyCompEarningOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DailyCompEarningScalarRelationFilter = {
  is?: Prisma.DailyCompEarningWhereInput
  isNot?: Prisma.DailyCompEarningWhereInput
}

export type DailyCompEarningUserIdEarningDateCompoundUniqueInput = {
  userId: string
  earningDate: Date | string
}

export type DailyCompEarningCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  earningDate?: Prisma.SortOrder
  totalContribution?: Prisma.SortOrder
  compEarned?: Prisma.SortOrder
  isProcessed?: Prisma.SortOrder
  processedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DailyCompEarningAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  totalContribution?: Prisma.SortOrder
  compEarned?: Prisma.SortOrder
}

export type DailyCompEarningMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  earningDate?: Prisma.SortOrder
  totalContribution?: Prisma.SortOrder
  compEarned?: Prisma.SortOrder
  isProcessed?: Prisma.SortOrder
  processedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DailyCompEarningMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  earningDate?: Prisma.SortOrder
  totalContribution?: Prisma.SortOrder
  compEarned?: Prisma.SortOrder
  isProcessed?: Prisma.SortOrder
  processedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DailyCompEarningSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  totalContribution?: Prisma.SortOrder
  compEarned?: Prisma.SortOrder
}

export type DailyCompEarningCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.DailyCompEarningCreateWithoutUserInput, Prisma.DailyCompEarningUncheckedCreateWithoutUserInput> | Prisma.DailyCompEarningCreateWithoutUserInput[] | Prisma.DailyCompEarningUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.DailyCompEarningCreateOrConnectWithoutUserInput | Prisma.DailyCompEarningCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.DailyCompEarningCreateManyUserInputEnvelope
  connect?: Prisma.DailyCompEarningWhereUniqueInput | Prisma.DailyCompEarningWhereUniqueInput[]
}

export type DailyCompEarningUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.DailyCompEarningCreateWithoutUserInput, Prisma.DailyCompEarningUncheckedCreateWithoutUserInput> | Prisma.DailyCompEarningCreateWithoutUserInput[] | Prisma.DailyCompEarningUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.DailyCompEarningCreateOrConnectWithoutUserInput | Prisma.DailyCompEarningCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.DailyCompEarningCreateManyUserInputEnvelope
  connect?: Prisma.DailyCompEarningWhereUniqueInput | Prisma.DailyCompEarningWhereUniqueInput[]
}

export type DailyCompEarningUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.DailyCompEarningCreateWithoutUserInput, Prisma.DailyCompEarningUncheckedCreateWithoutUserInput> | Prisma.DailyCompEarningCreateWithoutUserInput[] | Prisma.DailyCompEarningUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.DailyCompEarningCreateOrConnectWithoutUserInput | Prisma.DailyCompEarningCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.DailyCompEarningUpsertWithWhereUniqueWithoutUserInput | Prisma.DailyCompEarningUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.DailyCompEarningCreateManyUserInputEnvelope
  set?: Prisma.DailyCompEarningWhereUniqueInput | Prisma.DailyCompEarningWhereUniqueInput[]
  disconnect?: Prisma.DailyCompEarningWhereUniqueInput | Prisma.DailyCompEarningWhereUniqueInput[]
  delete?: Prisma.DailyCompEarningWhereUniqueInput | Prisma.DailyCompEarningWhereUniqueInput[]
  connect?: Prisma.DailyCompEarningWhereUniqueInput | Prisma.DailyCompEarningWhereUniqueInput[]
  update?: Prisma.DailyCompEarningUpdateWithWhereUniqueWithoutUserInput | Prisma.DailyCompEarningUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.DailyCompEarningUpdateManyWithWhereWithoutUserInput | Prisma.DailyCompEarningUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.DailyCompEarningScalarWhereInput | Prisma.DailyCompEarningScalarWhereInput[]
}

export type DailyCompEarningUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.DailyCompEarningCreateWithoutUserInput, Prisma.DailyCompEarningUncheckedCreateWithoutUserInput> | Prisma.DailyCompEarningCreateWithoutUserInput[] | Prisma.DailyCompEarningUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.DailyCompEarningCreateOrConnectWithoutUserInput | Prisma.DailyCompEarningCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.DailyCompEarningUpsertWithWhereUniqueWithoutUserInput | Prisma.DailyCompEarningUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.DailyCompEarningCreateManyUserInputEnvelope
  set?: Prisma.DailyCompEarningWhereUniqueInput | Prisma.DailyCompEarningWhereUniqueInput[]
  disconnect?: Prisma.DailyCompEarningWhereUniqueInput | Prisma.DailyCompEarningWhereUniqueInput[]
  delete?: Prisma.DailyCompEarningWhereUniqueInput | Prisma.DailyCompEarningWhereUniqueInput[]
  connect?: Prisma.DailyCompEarningWhereUniqueInput | Prisma.DailyCompEarningWhereUniqueInput[]
  update?: Prisma.DailyCompEarningUpdateWithWhereUniqueWithoutUserInput | Prisma.DailyCompEarningUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.DailyCompEarningUpdateManyWithWhereWithoutUserInput | Prisma.DailyCompEarningUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.DailyCompEarningScalarWhereInput | Prisma.DailyCompEarningScalarWhereInput[]
}

export type DailyCompEarningCreateNestedOneWithoutCompTransactionInput = {
  create?: Prisma.XOR<Prisma.DailyCompEarningCreateWithoutCompTransactionInput, Prisma.DailyCompEarningUncheckedCreateWithoutCompTransactionInput>
  connectOrCreate?: Prisma.DailyCompEarningCreateOrConnectWithoutCompTransactionInput
  connect?: Prisma.DailyCompEarningWhereUniqueInput
}

export type DailyCompEarningUpdateOneRequiredWithoutCompTransactionNestedInput = {
  create?: Prisma.XOR<Prisma.DailyCompEarningCreateWithoutCompTransactionInput, Prisma.DailyCompEarningUncheckedCreateWithoutCompTransactionInput>
  connectOrCreate?: Prisma.DailyCompEarningCreateOrConnectWithoutCompTransactionInput
  upsert?: Prisma.DailyCompEarningUpsertWithoutCompTransactionInput
  connect?: Prisma.DailyCompEarningWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DailyCompEarningUpdateToOneWithWhereWithoutCompTransactionInput, Prisma.DailyCompEarningUpdateWithoutCompTransactionInput>, Prisma.DailyCompEarningUncheckedUpdateWithoutCompTransactionInput>
}

export type DailyCompEarningCreateWithoutUserInput = {
  earningDate: Date | string
  totalContribution: runtime.Decimal | runtime.DecimalJsLike | number | string
  compEarned: runtime.Decimal | runtime.DecimalJsLike | number | string
  isProcessed?: boolean
  processedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  CompTransaction?: Prisma.CompTransactionCreateNestedManyWithoutDailyCompEarningInput
}

export type DailyCompEarningUncheckedCreateWithoutUserInput = {
  id?: number
  earningDate: Date | string
  totalContribution: runtime.Decimal | runtime.DecimalJsLike | number | string
  compEarned: runtime.Decimal | runtime.DecimalJsLike | number | string
  isProcessed?: boolean
  processedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  CompTransaction?: Prisma.CompTransactionUncheckedCreateNestedManyWithoutDailyCompEarningInput
}

export type DailyCompEarningCreateOrConnectWithoutUserInput = {
  where: Prisma.DailyCompEarningWhereUniqueInput
  create: Prisma.XOR<Prisma.DailyCompEarningCreateWithoutUserInput, Prisma.DailyCompEarningUncheckedCreateWithoutUserInput>
}

export type DailyCompEarningCreateManyUserInputEnvelope = {
  data: Prisma.DailyCompEarningCreateManyUserInput | Prisma.DailyCompEarningCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type DailyCompEarningUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.DailyCompEarningWhereUniqueInput
  update: Prisma.XOR<Prisma.DailyCompEarningUpdateWithoutUserInput, Prisma.DailyCompEarningUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.DailyCompEarningCreateWithoutUserInput, Prisma.DailyCompEarningUncheckedCreateWithoutUserInput>
}

export type DailyCompEarningUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.DailyCompEarningWhereUniqueInput
  data: Prisma.XOR<Prisma.DailyCompEarningUpdateWithoutUserInput, Prisma.DailyCompEarningUncheckedUpdateWithoutUserInput>
}

export type DailyCompEarningUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.DailyCompEarningScalarWhereInput
  data: Prisma.XOR<Prisma.DailyCompEarningUpdateManyMutationInput, Prisma.DailyCompEarningUncheckedUpdateManyWithoutUserInput>
}

export type DailyCompEarningScalarWhereInput = {
  AND?: Prisma.DailyCompEarningScalarWhereInput | Prisma.DailyCompEarningScalarWhereInput[]
  OR?: Prisma.DailyCompEarningScalarWhereInput[]
  NOT?: Prisma.DailyCompEarningScalarWhereInput | Prisma.DailyCompEarningScalarWhereInput[]
  id?: Prisma.IntFilter<"DailyCompEarning"> | number
  userId?: Prisma.StringFilter<"DailyCompEarning"> | string
  earningDate?: Prisma.DateTimeFilter<"DailyCompEarning"> | Date | string
  totalContribution?: Prisma.DecimalFilter<"DailyCompEarning"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  compEarned?: Prisma.DecimalFilter<"DailyCompEarning"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  isProcessed?: Prisma.BoolFilter<"DailyCompEarning"> | boolean
  processedAt?: Prisma.DateTimeNullableFilter<"DailyCompEarning"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"DailyCompEarning"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DailyCompEarning"> | Date | string
}

export type DailyCompEarningCreateWithoutCompTransactionInput = {
  earningDate: Date | string
  totalContribution: runtime.Decimal | runtime.DecimalJsLike | number | string
  compEarned: runtime.Decimal | runtime.DecimalJsLike | number | string
  isProcessed?: boolean
  processedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutDailyCompEarningInput
}

export type DailyCompEarningUncheckedCreateWithoutCompTransactionInput = {
  id?: number
  userId: string
  earningDate: Date | string
  totalContribution: runtime.Decimal | runtime.DecimalJsLike | number | string
  compEarned: runtime.Decimal | runtime.DecimalJsLike | number | string
  isProcessed?: boolean
  processedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DailyCompEarningCreateOrConnectWithoutCompTransactionInput = {
  where: Prisma.DailyCompEarningWhereUniqueInput
  create: Prisma.XOR<Prisma.DailyCompEarningCreateWithoutCompTransactionInput, Prisma.DailyCompEarningUncheckedCreateWithoutCompTransactionInput>
}

export type DailyCompEarningUpsertWithoutCompTransactionInput = {
  update: Prisma.XOR<Prisma.DailyCompEarningUpdateWithoutCompTransactionInput, Prisma.DailyCompEarningUncheckedUpdateWithoutCompTransactionInput>
  create: Prisma.XOR<Prisma.DailyCompEarningCreateWithoutCompTransactionInput, Prisma.DailyCompEarningUncheckedCreateWithoutCompTransactionInput>
  where?: Prisma.DailyCompEarningWhereInput
}

export type DailyCompEarningUpdateToOneWithWhereWithoutCompTransactionInput = {
  where?: Prisma.DailyCompEarningWhereInput
  data: Prisma.XOR<Prisma.DailyCompEarningUpdateWithoutCompTransactionInput, Prisma.DailyCompEarningUncheckedUpdateWithoutCompTransactionInput>
}

export type DailyCompEarningUpdateWithoutCompTransactionInput = {
  earningDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  totalContribution?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  compEarned?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  isProcessed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutDailyCompEarningNestedInput
}

export type DailyCompEarningUncheckedUpdateWithoutCompTransactionInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  earningDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  totalContribution?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  compEarned?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  isProcessed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DailyCompEarningCreateManyUserInput = {
  id?: number
  earningDate: Date | string
  totalContribution: runtime.Decimal | runtime.DecimalJsLike | number | string
  compEarned: runtime.Decimal | runtime.DecimalJsLike | number | string
  isProcessed?: boolean
  processedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DailyCompEarningUpdateWithoutUserInput = {
  earningDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  totalContribution?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  compEarned?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  isProcessed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  CompTransaction?: Prisma.CompTransactionUpdateManyWithoutDailyCompEarningNestedInput
}

export type DailyCompEarningUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  earningDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  totalContribution?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  compEarned?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  isProcessed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  CompTransaction?: Prisma.CompTransactionUncheckedUpdateManyWithoutDailyCompEarningNestedInput
}

export type DailyCompEarningUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  earningDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  totalContribution?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  compEarned?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  isProcessed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type DailyCompEarningCountOutputType
 */

export type DailyCompEarningCountOutputType = {
  CompTransaction: number
}

export type DailyCompEarningCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  CompTransaction?: boolean | DailyCompEarningCountOutputTypeCountCompTransactionArgs
}

/**
 * DailyCompEarningCountOutputType without action
 */
export type DailyCompEarningCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DailyCompEarningCountOutputType
   */
  select?: Prisma.DailyCompEarningCountOutputTypeSelect<ExtArgs> | null
}

/**
 * DailyCompEarningCountOutputType without action
 */
export type DailyCompEarningCountOutputTypeCountCompTransactionArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CompTransactionWhereInput
}


export type DailyCompEarningSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  earningDate?: boolean
  totalContribution?: boolean
  compEarned?: boolean
  isProcessed?: boolean
  processedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  CompTransaction?: boolean | Prisma.DailyCompEarning$CompTransactionArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.DailyCompEarningCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dailyCompEarning"]>

export type DailyCompEarningSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  earningDate?: boolean
  totalContribution?: boolean
  compEarned?: boolean
  isProcessed?: boolean
  processedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dailyCompEarning"]>

export type DailyCompEarningSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  earningDate?: boolean
  totalContribution?: boolean
  compEarned?: boolean
  isProcessed?: boolean
  processedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dailyCompEarning"]>

export type DailyCompEarningSelectScalar = {
  id?: boolean
  userId?: boolean
  earningDate?: boolean
  totalContribution?: boolean
  compEarned?: boolean
  isProcessed?: boolean
  processedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type DailyCompEarningOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "earningDate" | "totalContribution" | "compEarned" | "isProcessed" | "processedAt" | "createdAt" | "updatedAt", ExtArgs["result"]["dailyCompEarning"]>
export type DailyCompEarningInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  CompTransaction?: boolean | Prisma.DailyCompEarning$CompTransactionArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.DailyCompEarningCountOutputTypeDefaultArgs<ExtArgs>
}
export type DailyCompEarningIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type DailyCompEarningIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $DailyCompEarningPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DailyCompEarning"
  objects: {
    CompTransaction: Prisma.$CompTransactionPayload<ExtArgs>[]
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    userId: string
    earningDate: Date
    totalContribution: runtime.Decimal
    compEarned: runtime.Decimal
    isProcessed: boolean
    processedAt: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["dailyCompEarning"]>
  composites: {}
}

export type DailyCompEarningGetPayload<S extends boolean | null | undefined | DailyCompEarningDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DailyCompEarningPayload, S>

export type DailyCompEarningCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DailyCompEarningFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DailyCompEarningCountAggregateInputType | true
  }

export interface DailyCompEarningDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DailyCompEarning'], meta: { name: 'DailyCompEarning' } }
  /**
   * Find zero or one DailyCompEarning that matches the filter.
   * @param {DailyCompEarningFindUniqueArgs} args - Arguments to find a DailyCompEarning
   * @example
   * // Get one DailyCompEarning
   * const dailyCompEarning = await prisma.dailyCompEarning.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DailyCompEarningFindUniqueArgs>(args: Prisma.SelectSubset<T, DailyCompEarningFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DailyCompEarningClient<runtime.Types.Result.GetResult<Prisma.$DailyCompEarningPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DailyCompEarning that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DailyCompEarningFindUniqueOrThrowArgs} args - Arguments to find a DailyCompEarning
   * @example
   * // Get one DailyCompEarning
   * const dailyCompEarning = await prisma.dailyCompEarning.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DailyCompEarningFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DailyCompEarningFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DailyCompEarningClient<runtime.Types.Result.GetResult<Prisma.$DailyCompEarningPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DailyCompEarning that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DailyCompEarningFindFirstArgs} args - Arguments to find a DailyCompEarning
   * @example
   * // Get one DailyCompEarning
   * const dailyCompEarning = await prisma.dailyCompEarning.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DailyCompEarningFindFirstArgs>(args?: Prisma.SelectSubset<T, DailyCompEarningFindFirstArgs<ExtArgs>>): Prisma.Prisma__DailyCompEarningClient<runtime.Types.Result.GetResult<Prisma.$DailyCompEarningPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DailyCompEarning that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DailyCompEarningFindFirstOrThrowArgs} args - Arguments to find a DailyCompEarning
   * @example
   * // Get one DailyCompEarning
   * const dailyCompEarning = await prisma.dailyCompEarning.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DailyCompEarningFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DailyCompEarningFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DailyCompEarningClient<runtime.Types.Result.GetResult<Prisma.$DailyCompEarningPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DailyCompEarnings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DailyCompEarningFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DailyCompEarnings
   * const dailyCompEarnings = await prisma.dailyCompEarning.findMany()
   * 
   * // Get first 10 DailyCompEarnings
   * const dailyCompEarnings = await prisma.dailyCompEarning.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const dailyCompEarningWithIdOnly = await prisma.dailyCompEarning.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DailyCompEarningFindManyArgs>(args?: Prisma.SelectSubset<T, DailyCompEarningFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DailyCompEarningPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DailyCompEarning.
   * @param {DailyCompEarningCreateArgs} args - Arguments to create a DailyCompEarning.
   * @example
   * // Create one DailyCompEarning
   * const DailyCompEarning = await prisma.dailyCompEarning.create({
   *   data: {
   *     // ... data to create a DailyCompEarning
   *   }
   * })
   * 
   */
  create<T extends DailyCompEarningCreateArgs>(args: Prisma.SelectSubset<T, DailyCompEarningCreateArgs<ExtArgs>>): Prisma.Prisma__DailyCompEarningClient<runtime.Types.Result.GetResult<Prisma.$DailyCompEarningPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DailyCompEarnings.
   * @param {DailyCompEarningCreateManyArgs} args - Arguments to create many DailyCompEarnings.
   * @example
   * // Create many DailyCompEarnings
   * const dailyCompEarning = await prisma.dailyCompEarning.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DailyCompEarningCreateManyArgs>(args?: Prisma.SelectSubset<T, DailyCompEarningCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DailyCompEarnings and returns the data saved in the database.
   * @param {DailyCompEarningCreateManyAndReturnArgs} args - Arguments to create many DailyCompEarnings.
   * @example
   * // Create many DailyCompEarnings
   * const dailyCompEarning = await prisma.dailyCompEarning.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DailyCompEarnings and only return the `id`
   * const dailyCompEarningWithIdOnly = await prisma.dailyCompEarning.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DailyCompEarningCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DailyCompEarningCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DailyCompEarningPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DailyCompEarning.
   * @param {DailyCompEarningDeleteArgs} args - Arguments to delete one DailyCompEarning.
   * @example
   * // Delete one DailyCompEarning
   * const DailyCompEarning = await prisma.dailyCompEarning.delete({
   *   where: {
   *     // ... filter to delete one DailyCompEarning
   *   }
   * })
   * 
   */
  delete<T extends DailyCompEarningDeleteArgs>(args: Prisma.SelectSubset<T, DailyCompEarningDeleteArgs<ExtArgs>>): Prisma.Prisma__DailyCompEarningClient<runtime.Types.Result.GetResult<Prisma.$DailyCompEarningPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DailyCompEarning.
   * @param {DailyCompEarningUpdateArgs} args - Arguments to update one DailyCompEarning.
   * @example
   * // Update one DailyCompEarning
   * const dailyCompEarning = await prisma.dailyCompEarning.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DailyCompEarningUpdateArgs>(args: Prisma.SelectSubset<T, DailyCompEarningUpdateArgs<ExtArgs>>): Prisma.Prisma__DailyCompEarningClient<runtime.Types.Result.GetResult<Prisma.$DailyCompEarningPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DailyCompEarnings.
   * @param {DailyCompEarningDeleteManyArgs} args - Arguments to filter DailyCompEarnings to delete.
   * @example
   * // Delete a few DailyCompEarnings
   * const { count } = await prisma.dailyCompEarning.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DailyCompEarningDeleteManyArgs>(args?: Prisma.SelectSubset<T, DailyCompEarningDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DailyCompEarnings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DailyCompEarningUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DailyCompEarnings
   * const dailyCompEarning = await prisma.dailyCompEarning.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DailyCompEarningUpdateManyArgs>(args: Prisma.SelectSubset<T, DailyCompEarningUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DailyCompEarnings and returns the data updated in the database.
   * @param {DailyCompEarningUpdateManyAndReturnArgs} args - Arguments to update many DailyCompEarnings.
   * @example
   * // Update many DailyCompEarnings
   * const dailyCompEarning = await prisma.dailyCompEarning.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DailyCompEarnings and only return the `id`
   * const dailyCompEarningWithIdOnly = await prisma.dailyCompEarning.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DailyCompEarningUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DailyCompEarningUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DailyCompEarningPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DailyCompEarning.
   * @param {DailyCompEarningUpsertArgs} args - Arguments to update or create a DailyCompEarning.
   * @example
   * // Update or create a DailyCompEarning
   * const dailyCompEarning = await prisma.dailyCompEarning.upsert({
   *   create: {
   *     // ... data to create a DailyCompEarning
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DailyCompEarning we want to update
   *   }
   * })
   */
  upsert<T extends DailyCompEarningUpsertArgs>(args: Prisma.SelectSubset<T, DailyCompEarningUpsertArgs<ExtArgs>>): Prisma.Prisma__DailyCompEarningClient<runtime.Types.Result.GetResult<Prisma.$DailyCompEarningPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DailyCompEarnings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DailyCompEarningCountArgs} args - Arguments to filter DailyCompEarnings to count.
   * @example
   * // Count the number of DailyCompEarnings
   * const count = await prisma.dailyCompEarning.count({
   *   where: {
   *     // ... the filter for the DailyCompEarnings we want to count
   *   }
   * })
  **/
  count<T extends DailyCompEarningCountArgs>(
    args?: Prisma.Subset<T, DailyCompEarningCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DailyCompEarningCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DailyCompEarning.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DailyCompEarningAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DailyCompEarningAggregateArgs>(args: Prisma.Subset<T, DailyCompEarningAggregateArgs>): Prisma.PrismaPromise<GetDailyCompEarningAggregateType<T>>

  /**
   * Group by DailyCompEarning.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DailyCompEarningGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DailyCompEarningGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DailyCompEarningGroupByArgs['orderBy'] }
      : { orderBy?: DailyCompEarningGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DailyCompEarningGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDailyCompEarningGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DailyCompEarning model
 */
readonly fields: DailyCompEarningFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DailyCompEarning.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DailyCompEarningClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  CompTransaction<T extends Prisma.DailyCompEarning$CompTransactionArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DailyCompEarning$CompTransactionArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CompTransactionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DailyCompEarning model
 */
export interface DailyCompEarningFieldRefs {
  readonly id: Prisma.FieldRef<"DailyCompEarning", 'Int'>
  readonly userId: Prisma.FieldRef<"DailyCompEarning", 'String'>
  readonly earningDate: Prisma.FieldRef<"DailyCompEarning", 'DateTime'>
  readonly totalContribution: Prisma.FieldRef<"DailyCompEarning", 'Decimal'>
  readonly compEarned: Prisma.FieldRef<"DailyCompEarning", 'Decimal'>
  readonly isProcessed: Prisma.FieldRef<"DailyCompEarning", 'Boolean'>
  readonly processedAt: Prisma.FieldRef<"DailyCompEarning", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"DailyCompEarning", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"DailyCompEarning", 'DateTime'>
}
    

// Custom InputTypes
/**
 * DailyCompEarning findUnique
 */
export type DailyCompEarningFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DailyCompEarning
   */
  select?: Prisma.DailyCompEarningSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DailyCompEarning
   */
  omit?: Prisma.DailyCompEarningOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DailyCompEarningInclude<ExtArgs> | null
  /**
   * Filter, which DailyCompEarning to fetch.
   */
  where: Prisma.DailyCompEarningWhereUniqueInput
}

/**
 * DailyCompEarning findUniqueOrThrow
 */
export type DailyCompEarningFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DailyCompEarning
   */
  select?: Prisma.DailyCompEarningSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DailyCompEarning
   */
  omit?: Prisma.DailyCompEarningOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DailyCompEarningInclude<ExtArgs> | null
  /**
   * Filter, which DailyCompEarning to fetch.
   */
  where: Prisma.DailyCompEarningWhereUniqueInput
}

/**
 * DailyCompEarning findFirst
 */
export type DailyCompEarningFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DailyCompEarning
   */
  select?: Prisma.DailyCompEarningSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DailyCompEarning
   */
  omit?: Prisma.DailyCompEarningOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DailyCompEarningInclude<ExtArgs> | null
  /**
   * Filter, which DailyCompEarning to fetch.
   */
  where?: Prisma.DailyCompEarningWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DailyCompEarnings to fetch.
   */
  orderBy?: Prisma.DailyCompEarningOrderByWithRelationInput | Prisma.DailyCompEarningOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DailyCompEarnings.
   */
  cursor?: Prisma.DailyCompEarningWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DailyCompEarnings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DailyCompEarnings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DailyCompEarnings.
   */
  distinct?: Prisma.DailyCompEarningScalarFieldEnum | Prisma.DailyCompEarningScalarFieldEnum[]
}

/**
 * DailyCompEarning findFirstOrThrow
 */
export type DailyCompEarningFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DailyCompEarning
   */
  select?: Prisma.DailyCompEarningSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DailyCompEarning
   */
  omit?: Prisma.DailyCompEarningOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DailyCompEarningInclude<ExtArgs> | null
  /**
   * Filter, which DailyCompEarning to fetch.
   */
  where?: Prisma.DailyCompEarningWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DailyCompEarnings to fetch.
   */
  orderBy?: Prisma.DailyCompEarningOrderByWithRelationInput | Prisma.DailyCompEarningOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DailyCompEarnings.
   */
  cursor?: Prisma.DailyCompEarningWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DailyCompEarnings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DailyCompEarnings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DailyCompEarnings.
   */
  distinct?: Prisma.DailyCompEarningScalarFieldEnum | Prisma.DailyCompEarningScalarFieldEnum[]
}

/**
 * DailyCompEarning findMany
 */
export type DailyCompEarningFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DailyCompEarning
   */
  select?: Prisma.DailyCompEarningSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DailyCompEarning
   */
  omit?: Prisma.DailyCompEarningOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DailyCompEarningInclude<ExtArgs> | null
  /**
   * Filter, which DailyCompEarnings to fetch.
   */
  where?: Prisma.DailyCompEarningWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DailyCompEarnings to fetch.
   */
  orderBy?: Prisma.DailyCompEarningOrderByWithRelationInput | Prisma.DailyCompEarningOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DailyCompEarnings.
   */
  cursor?: Prisma.DailyCompEarningWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DailyCompEarnings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DailyCompEarnings.
   */
  skip?: number
  distinct?: Prisma.DailyCompEarningScalarFieldEnum | Prisma.DailyCompEarningScalarFieldEnum[]
}

/**
 * DailyCompEarning create
 */
export type DailyCompEarningCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DailyCompEarning
   */
  select?: Prisma.DailyCompEarningSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DailyCompEarning
   */
  omit?: Prisma.DailyCompEarningOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DailyCompEarningInclude<ExtArgs> | null
  /**
   * The data needed to create a DailyCompEarning.
   */
  data: Prisma.XOR<Prisma.DailyCompEarningCreateInput, Prisma.DailyCompEarningUncheckedCreateInput>
}

/**
 * DailyCompEarning createMany
 */
export type DailyCompEarningCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DailyCompEarnings.
   */
  data: Prisma.DailyCompEarningCreateManyInput | Prisma.DailyCompEarningCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DailyCompEarning createManyAndReturn
 */
export type DailyCompEarningCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DailyCompEarning
   */
  select?: Prisma.DailyCompEarningSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DailyCompEarning
   */
  omit?: Prisma.DailyCompEarningOmit<ExtArgs> | null
  /**
   * The data used to create many DailyCompEarnings.
   */
  data: Prisma.DailyCompEarningCreateManyInput | Prisma.DailyCompEarningCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DailyCompEarningIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * DailyCompEarning update
 */
export type DailyCompEarningUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DailyCompEarning
   */
  select?: Prisma.DailyCompEarningSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DailyCompEarning
   */
  omit?: Prisma.DailyCompEarningOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DailyCompEarningInclude<ExtArgs> | null
  /**
   * The data needed to update a DailyCompEarning.
   */
  data: Prisma.XOR<Prisma.DailyCompEarningUpdateInput, Prisma.DailyCompEarningUncheckedUpdateInput>
  /**
   * Choose, which DailyCompEarning to update.
   */
  where: Prisma.DailyCompEarningWhereUniqueInput
}

/**
 * DailyCompEarning updateMany
 */
export type DailyCompEarningUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DailyCompEarnings.
   */
  data: Prisma.XOR<Prisma.DailyCompEarningUpdateManyMutationInput, Prisma.DailyCompEarningUncheckedUpdateManyInput>
  /**
   * Filter which DailyCompEarnings to update
   */
  where?: Prisma.DailyCompEarningWhereInput
  /**
   * Limit how many DailyCompEarnings to update.
   */
  limit?: number
}

/**
 * DailyCompEarning updateManyAndReturn
 */
export type DailyCompEarningUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DailyCompEarning
   */
  select?: Prisma.DailyCompEarningSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DailyCompEarning
   */
  omit?: Prisma.DailyCompEarningOmit<ExtArgs> | null
  /**
   * The data used to update DailyCompEarnings.
   */
  data: Prisma.XOR<Prisma.DailyCompEarningUpdateManyMutationInput, Prisma.DailyCompEarningUncheckedUpdateManyInput>
  /**
   * Filter which DailyCompEarnings to update
   */
  where?: Prisma.DailyCompEarningWhereInput
  /**
   * Limit how many DailyCompEarnings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DailyCompEarningIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * DailyCompEarning upsert
 */
export type DailyCompEarningUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DailyCompEarning
   */
  select?: Prisma.DailyCompEarningSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DailyCompEarning
   */
  omit?: Prisma.DailyCompEarningOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DailyCompEarningInclude<ExtArgs> | null
  /**
   * The filter to search for the DailyCompEarning to update in case it exists.
   */
  where: Prisma.DailyCompEarningWhereUniqueInput
  /**
   * In case the DailyCompEarning found by the `where` argument doesn't exist, create a new DailyCompEarning with this data.
   */
  create: Prisma.XOR<Prisma.DailyCompEarningCreateInput, Prisma.DailyCompEarningUncheckedCreateInput>
  /**
   * In case the DailyCompEarning was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DailyCompEarningUpdateInput, Prisma.DailyCompEarningUncheckedUpdateInput>
}

/**
 * DailyCompEarning delete
 */
export type DailyCompEarningDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DailyCompEarning
   */
  select?: Prisma.DailyCompEarningSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DailyCompEarning
   */
  omit?: Prisma.DailyCompEarningOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DailyCompEarningInclude<ExtArgs> | null
  /**
   * Filter which DailyCompEarning to delete.
   */
  where: Prisma.DailyCompEarningWhereUniqueInput
}

/**
 * DailyCompEarning deleteMany
 */
export type DailyCompEarningDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DailyCompEarnings to delete
   */
  where?: Prisma.DailyCompEarningWhereInput
  /**
   * Limit how many DailyCompEarnings to delete.
   */
  limit?: number
}

/**
 * DailyCompEarning.CompTransaction
 */
export type DailyCompEarning$CompTransactionArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CompTransaction
   */
  select?: Prisma.CompTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CompTransaction
   */
  omit?: Prisma.CompTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompTransactionInclude<ExtArgs> | null
  where?: Prisma.CompTransactionWhereInput
  orderBy?: Prisma.CompTransactionOrderByWithRelationInput | Prisma.CompTransactionOrderByWithRelationInput[]
  cursor?: Prisma.CompTransactionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CompTransactionScalarFieldEnum | Prisma.CompTransactionScalarFieldEnum[]
}

/**
 * DailyCompEarning without action
 */
export type DailyCompEarningDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DailyCompEarning
   */
  select?: Prisma.DailyCompEarningSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DailyCompEarning
   */
  omit?: Prisma.DailyCompEarningOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DailyCompEarningInclude<ExtArgs> | null
}
