
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `NowPaymentCallbackLog` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model NowPaymentCallbackLog
 * 
 */
export type NowPaymentCallbackLogModel = runtime.Types.Result.DefaultSelection<Prisma.$NowPaymentCallbackLogPayload>

export type AggregateNowPaymentCallbackLog = {
  _count: NowPaymentCallbackLogCountAggregateOutputType | null
  _avg: NowPaymentCallbackLogAvgAggregateOutputType | null
  _sum: NowPaymentCallbackLogSumAggregateOutputType | null
  _min: NowPaymentCallbackLogMinAggregateOutputType | null
  _max: NowPaymentCallbackLogMaxAggregateOutputType | null
}

export type NowPaymentCallbackLogAvgAggregateOutputType = {
  id: number | null
  responseStatus: number | null
}

export type NowPaymentCallbackLogSumAggregateOutputType = {
  id: bigint | null
  responseStatus: number | null
}

export type NowPaymentCallbackLogMinAggregateOutputType = {
  id: bigint | null
  responseStatus: number | null
  processed: boolean | null
  processingError: string | null
  processedAt: Date | null
  createdAt: Date | null
}

export type NowPaymentCallbackLogMaxAggregateOutputType = {
  id: bigint | null
  responseStatus: number | null
  processed: boolean | null
  processingError: string | null
  processedAt: Date | null
  createdAt: Date | null
}

export type NowPaymentCallbackLogCountAggregateOutputType = {
  id: number
  requestHeaders: number
  requestBody: number
  responseStatus: number
  responseBody: number
  processed: number
  processingError: number
  processedAt: number
  createdAt: number
  _all: number
}


export type NowPaymentCallbackLogAvgAggregateInputType = {
  id?: true
  responseStatus?: true
}

export type NowPaymentCallbackLogSumAggregateInputType = {
  id?: true
  responseStatus?: true
}

export type NowPaymentCallbackLogMinAggregateInputType = {
  id?: true
  responseStatus?: true
  processed?: true
  processingError?: true
  processedAt?: true
  createdAt?: true
}

export type NowPaymentCallbackLogMaxAggregateInputType = {
  id?: true
  responseStatus?: true
  processed?: true
  processingError?: true
  processedAt?: true
  createdAt?: true
}

export type NowPaymentCallbackLogCountAggregateInputType = {
  id?: true
  requestHeaders?: true
  requestBody?: true
  responseStatus?: true
  responseBody?: true
  processed?: true
  processingError?: true
  processedAt?: true
  createdAt?: true
  _all?: true
}

export type NowPaymentCallbackLogAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NowPaymentCallbackLog to aggregate.
   */
  where?: Prisma.NowPaymentCallbackLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NowPaymentCallbackLogs to fetch.
   */
  orderBy?: Prisma.NowPaymentCallbackLogOrderByWithRelationInput | Prisma.NowPaymentCallbackLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.NowPaymentCallbackLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NowPaymentCallbackLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NowPaymentCallbackLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned NowPaymentCallbackLogs
  **/
  _count?: true | NowPaymentCallbackLogCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: NowPaymentCallbackLogAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: NowPaymentCallbackLogSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: NowPaymentCallbackLogMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: NowPaymentCallbackLogMaxAggregateInputType
}

export type GetNowPaymentCallbackLogAggregateType<T extends NowPaymentCallbackLogAggregateArgs> = {
      [P in keyof T & keyof AggregateNowPaymentCallbackLog]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateNowPaymentCallbackLog[P]>
    : Prisma.GetScalarType<T[P], AggregateNowPaymentCallbackLog[P]>
}




export type NowPaymentCallbackLogGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NowPaymentCallbackLogWhereInput
  orderBy?: Prisma.NowPaymentCallbackLogOrderByWithAggregationInput | Prisma.NowPaymentCallbackLogOrderByWithAggregationInput[]
  by: Prisma.NowPaymentCallbackLogScalarFieldEnum[] | Prisma.NowPaymentCallbackLogScalarFieldEnum
  having?: Prisma.NowPaymentCallbackLogScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: NowPaymentCallbackLogCountAggregateInputType | true
  _avg?: NowPaymentCallbackLogAvgAggregateInputType
  _sum?: NowPaymentCallbackLogSumAggregateInputType
  _min?: NowPaymentCallbackLogMinAggregateInputType
  _max?: NowPaymentCallbackLogMaxAggregateInputType
}

export type NowPaymentCallbackLogGroupByOutputType = {
  id: bigint
  requestHeaders: runtime.JsonValue | null
  requestBody: runtime.JsonValue
  responseStatus: number | null
  responseBody: runtime.JsonValue | null
  processed: boolean
  processingError: string | null
  processedAt: Date | null
  createdAt: Date
  _count: NowPaymentCallbackLogCountAggregateOutputType | null
  _avg: NowPaymentCallbackLogAvgAggregateOutputType | null
  _sum: NowPaymentCallbackLogSumAggregateOutputType | null
  _min: NowPaymentCallbackLogMinAggregateOutputType | null
  _max: NowPaymentCallbackLogMaxAggregateOutputType | null
}

type GetNowPaymentCallbackLogGroupByPayload<T extends NowPaymentCallbackLogGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<NowPaymentCallbackLogGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof NowPaymentCallbackLogGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], NowPaymentCallbackLogGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], NowPaymentCallbackLogGroupByOutputType[P]>
      }
    >
  >



export type NowPaymentCallbackLogWhereInput = {
  AND?: Prisma.NowPaymentCallbackLogWhereInput | Prisma.NowPaymentCallbackLogWhereInput[]
  OR?: Prisma.NowPaymentCallbackLogWhereInput[]
  NOT?: Prisma.NowPaymentCallbackLogWhereInput | Prisma.NowPaymentCallbackLogWhereInput[]
  id?: Prisma.BigIntFilter<"NowPaymentCallbackLog"> | bigint | number
  requestHeaders?: Prisma.JsonNullableFilter<"NowPaymentCallbackLog">
  requestBody?: Prisma.JsonFilter<"NowPaymentCallbackLog">
  responseStatus?: Prisma.IntNullableFilter<"NowPaymentCallbackLog"> | number | null
  responseBody?: Prisma.JsonNullableFilter<"NowPaymentCallbackLog">
  processed?: Prisma.BoolFilter<"NowPaymentCallbackLog"> | boolean
  processingError?: Prisma.StringNullableFilter<"NowPaymentCallbackLog"> | string | null
  processedAt?: Prisma.DateTimeNullableFilter<"NowPaymentCallbackLog"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"NowPaymentCallbackLog"> | Date | string
}

export type NowPaymentCallbackLogOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  requestHeaders?: Prisma.SortOrderInput | Prisma.SortOrder
  requestBody?: Prisma.SortOrder
  responseStatus?: Prisma.SortOrderInput | Prisma.SortOrder
  responseBody?: Prisma.SortOrderInput | Prisma.SortOrder
  processed?: Prisma.SortOrder
  processingError?: Prisma.SortOrderInput | Prisma.SortOrder
  processedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type NowPaymentCallbackLogWhereUniqueInput = Prisma.AtLeast<{
  id?: bigint | number
  AND?: Prisma.NowPaymentCallbackLogWhereInput | Prisma.NowPaymentCallbackLogWhereInput[]
  OR?: Prisma.NowPaymentCallbackLogWhereInput[]
  NOT?: Prisma.NowPaymentCallbackLogWhereInput | Prisma.NowPaymentCallbackLogWhereInput[]
  requestHeaders?: Prisma.JsonNullableFilter<"NowPaymentCallbackLog">
  requestBody?: Prisma.JsonFilter<"NowPaymentCallbackLog">
  responseStatus?: Prisma.IntNullableFilter<"NowPaymentCallbackLog"> | number | null
  responseBody?: Prisma.JsonNullableFilter<"NowPaymentCallbackLog">
  processed?: Prisma.BoolFilter<"NowPaymentCallbackLog"> | boolean
  processingError?: Prisma.StringNullableFilter<"NowPaymentCallbackLog"> | string | null
  processedAt?: Prisma.DateTimeNullableFilter<"NowPaymentCallbackLog"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"NowPaymentCallbackLog"> | Date | string
}, "id">

export type NowPaymentCallbackLogOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  requestHeaders?: Prisma.SortOrderInput | Prisma.SortOrder
  requestBody?: Prisma.SortOrder
  responseStatus?: Prisma.SortOrderInput | Prisma.SortOrder
  responseBody?: Prisma.SortOrderInput | Prisma.SortOrder
  processed?: Prisma.SortOrder
  processingError?: Prisma.SortOrderInput | Prisma.SortOrder
  processedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.NowPaymentCallbackLogCountOrderByAggregateInput
  _avg?: Prisma.NowPaymentCallbackLogAvgOrderByAggregateInput
  _max?: Prisma.NowPaymentCallbackLogMaxOrderByAggregateInput
  _min?: Prisma.NowPaymentCallbackLogMinOrderByAggregateInput
  _sum?: Prisma.NowPaymentCallbackLogSumOrderByAggregateInput
}

export type NowPaymentCallbackLogScalarWhereWithAggregatesInput = {
  AND?: Prisma.NowPaymentCallbackLogScalarWhereWithAggregatesInput | Prisma.NowPaymentCallbackLogScalarWhereWithAggregatesInput[]
  OR?: Prisma.NowPaymentCallbackLogScalarWhereWithAggregatesInput[]
  NOT?: Prisma.NowPaymentCallbackLogScalarWhereWithAggregatesInput | Prisma.NowPaymentCallbackLogScalarWhereWithAggregatesInput[]
  id?: Prisma.BigIntWithAggregatesFilter<"NowPaymentCallbackLog"> | bigint | number
  requestHeaders?: Prisma.JsonNullableWithAggregatesFilter<"NowPaymentCallbackLog">
  requestBody?: Prisma.JsonWithAggregatesFilter<"NowPaymentCallbackLog">
  responseStatus?: Prisma.IntNullableWithAggregatesFilter<"NowPaymentCallbackLog"> | number | null
  responseBody?: Prisma.JsonNullableWithAggregatesFilter<"NowPaymentCallbackLog">
  processed?: Prisma.BoolWithAggregatesFilter<"NowPaymentCallbackLog"> | boolean
  processingError?: Prisma.StringNullableWithAggregatesFilter<"NowPaymentCallbackLog"> | string | null
  processedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"NowPaymentCallbackLog"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"NowPaymentCallbackLog"> | Date | string
}

export type NowPaymentCallbackLogCreateInput = {
  id?: bigint | number
  requestHeaders?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  requestBody: Prisma.JsonNullValueInput | runtime.InputJsonValue
  responseStatus?: number | null
  responseBody?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  processed?: boolean
  processingError?: string | null
  processedAt?: Date | string | null
  createdAt?: Date | string
}

export type NowPaymentCallbackLogUncheckedCreateInput = {
  id?: bigint | number
  requestHeaders?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  requestBody: Prisma.JsonNullValueInput | runtime.InputJsonValue
  responseStatus?: number | null
  responseBody?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  processed?: boolean
  processingError?: string | null
  processedAt?: Date | string | null
  createdAt?: Date | string
}

export type NowPaymentCallbackLogUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  requestHeaders?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  requestBody?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  responseStatus?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  responseBody?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  processed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  processingError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NowPaymentCallbackLogUncheckedUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  requestHeaders?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  requestBody?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  responseStatus?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  responseBody?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  processed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  processingError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NowPaymentCallbackLogCreateManyInput = {
  id?: bigint | number
  requestHeaders?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  requestBody: Prisma.JsonNullValueInput | runtime.InputJsonValue
  responseStatus?: number | null
  responseBody?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  processed?: boolean
  processingError?: string | null
  processedAt?: Date | string | null
  createdAt?: Date | string
}

export type NowPaymentCallbackLogUpdateManyMutationInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  requestHeaders?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  requestBody?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  responseStatus?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  responseBody?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  processed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  processingError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NowPaymentCallbackLogUncheckedUpdateManyInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  requestHeaders?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  requestBody?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  responseStatus?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  responseBody?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  processed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  processingError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NowPaymentCallbackLogCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  requestHeaders?: Prisma.SortOrder
  requestBody?: Prisma.SortOrder
  responseStatus?: Prisma.SortOrder
  responseBody?: Prisma.SortOrder
  processed?: Prisma.SortOrder
  processingError?: Prisma.SortOrder
  processedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type NowPaymentCallbackLogAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  responseStatus?: Prisma.SortOrder
}

export type NowPaymentCallbackLogMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  responseStatus?: Prisma.SortOrder
  processed?: Prisma.SortOrder
  processingError?: Prisma.SortOrder
  processedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type NowPaymentCallbackLogMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  responseStatus?: Prisma.SortOrder
  processed?: Prisma.SortOrder
  processingError?: Prisma.SortOrder
  processedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type NowPaymentCallbackLogSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  responseStatus?: Prisma.SortOrder
}



export type NowPaymentCallbackLogSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  requestHeaders?: boolean
  requestBody?: boolean
  responseStatus?: boolean
  responseBody?: boolean
  processed?: boolean
  processingError?: boolean
  processedAt?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["nowPaymentCallbackLog"]>

export type NowPaymentCallbackLogSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  requestHeaders?: boolean
  requestBody?: boolean
  responseStatus?: boolean
  responseBody?: boolean
  processed?: boolean
  processingError?: boolean
  processedAt?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["nowPaymentCallbackLog"]>

export type NowPaymentCallbackLogSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  requestHeaders?: boolean
  requestBody?: boolean
  responseStatus?: boolean
  responseBody?: boolean
  processed?: boolean
  processingError?: boolean
  processedAt?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["nowPaymentCallbackLog"]>

export type NowPaymentCallbackLogSelectScalar = {
  id?: boolean
  requestHeaders?: boolean
  requestBody?: boolean
  responseStatus?: boolean
  responseBody?: boolean
  processed?: boolean
  processingError?: boolean
  processedAt?: boolean
  createdAt?: boolean
}

export type NowPaymentCallbackLogOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "requestHeaders" | "requestBody" | "responseStatus" | "responseBody" | "processed" | "processingError" | "processedAt" | "createdAt", ExtArgs["result"]["nowPaymentCallbackLog"]>

export type $NowPaymentCallbackLogPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "NowPaymentCallbackLog"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: bigint
    requestHeaders: runtime.JsonValue | null
    requestBody: runtime.JsonValue
    responseStatus: number | null
    responseBody: runtime.JsonValue | null
    processed: boolean
    processingError: string | null
    processedAt: Date | null
    createdAt: Date
  }, ExtArgs["result"]["nowPaymentCallbackLog"]>
  composites: {}
}

export type NowPaymentCallbackLogGetPayload<S extends boolean | null | undefined | NowPaymentCallbackLogDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$NowPaymentCallbackLogPayload, S>

export type NowPaymentCallbackLogCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<NowPaymentCallbackLogFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: NowPaymentCallbackLogCountAggregateInputType | true
  }

export interface NowPaymentCallbackLogDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['NowPaymentCallbackLog'], meta: { name: 'NowPaymentCallbackLog' } }
  /**
   * Find zero or one NowPaymentCallbackLog that matches the filter.
   * @param {NowPaymentCallbackLogFindUniqueArgs} args - Arguments to find a NowPaymentCallbackLog
   * @example
   * // Get one NowPaymentCallbackLog
   * const nowPaymentCallbackLog = await prisma.nowPaymentCallbackLog.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends NowPaymentCallbackLogFindUniqueArgs>(args: Prisma.SelectSubset<T, NowPaymentCallbackLogFindUniqueArgs<ExtArgs>>): Prisma.Prisma__NowPaymentCallbackLogClient<runtime.Types.Result.GetResult<Prisma.$NowPaymentCallbackLogPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one NowPaymentCallbackLog that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {NowPaymentCallbackLogFindUniqueOrThrowArgs} args - Arguments to find a NowPaymentCallbackLog
   * @example
   * // Get one NowPaymentCallbackLog
   * const nowPaymentCallbackLog = await prisma.nowPaymentCallbackLog.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends NowPaymentCallbackLogFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, NowPaymentCallbackLogFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__NowPaymentCallbackLogClient<runtime.Types.Result.GetResult<Prisma.$NowPaymentCallbackLogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NowPaymentCallbackLog that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NowPaymentCallbackLogFindFirstArgs} args - Arguments to find a NowPaymentCallbackLog
   * @example
   * // Get one NowPaymentCallbackLog
   * const nowPaymentCallbackLog = await prisma.nowPaymentCallbackLog.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends NowPaymentCallbackLogFindFirstArgs>(args?: Prisma.SelectSubset<T, NowPaymentCallbackLogFindFirstArgs<ExtArgs>>): Prisma.Prisma__NowPaymentCallbackLogClient<runtime.Types.Result.GetResult<Prisma.$NowPaymentCallbackLogPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NowPaymentCallbackLog that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NowPaymentCallbackLogFindFirstOrThrowArgs} args - Arguments to find a NowPaymentCallbackLog
   * @example
   * // Get one NowPaymentCallbackLog
   * const nowPaymentCallbackLog = await prisma.nowPaymentCallbackLog.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends NowPaymentCallbackLogFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, NowPaymentCallbackLogFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__NowPaymentCallbackLogClient<runtime.Types.Result.GetResult<Prisma.$NowPaymentCallbackLogPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more NowPaymentCallbackLogs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NowPaymentCallbackLogFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all NowPaymentCallbackLogs
   * const nowPaymentCallbackLogs = await prisma.nowPaymentCallbackLog.findMany()
   * 
   * // Get first 10 NowPaymentCallbackLogs
   * const nowPaymentCallbackLogs = await prisma.nowPaymentCallbackLog.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const nowPaymentCallbackLogWithIdOnly = await prisma.nowPaymentCallbackLog.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends NowPaymentCallbackLogFindManyArgs>(args?: Prisma.SelectSubset<T, NowPaymentCallbackLogFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NowPaymentCallbackLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a NowPaymentCallbackLog.
   * @param {NowPaymentCallbackLogCreateArgs} args - Arguments to create a NowPaymentCallbackLog.
   * @example
   * // Create one NowPaymentCallbackLog
   * const NowPaymentCallbackLog = await prisma.nowPaymentCallbackLog.create({
   *   data: {
   *     // ... data to create a NowPaymentCallbackLog
   *   }
   * })
   * 
   */
  create<T extends NowPaymentCallbackLogCreateArgs>(args: Prisma.SelectSubset<T, NowPaymentCallbackLogCreateArgs<ExtArgs>>): Prisma.Prisma__NowPaymentCallbackLogClient<runtime.Types.Result.GetResult<Prisma.$NowPaymentCallbackLogPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many NowPaymentCallbackLogs.
   * @param {NowPaymentCallbackLogCreateManyArgs} args - Arguments to create many NowPaymentCallbackLogs.
   * @example
   * // Create many NowPaymentCallbackLogs
   * const nowPaymentCallbackLog = await prisma.nowPaymentCallbackLog.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends NowPaymentCallbackLogCreateManyArgs>(args?: Prisma.SelectSubset<T, NowPaymentCallbackLogCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many NowPaymentCallbackLogs and returns the data saved in the database.
   * @param {NowPaymentCallbackLogCreateManyAndReturnArgs} args - Arguments to create many NowPaymentCallbackLogs.
   * @example
   * // Create many NowPaymentCallbackLogs
   * const nowPaymentCallbackLog = await prisma.nowPaymentCallbackLog.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many NowPaymentCallbackLogs and only return the `id`
   * const nowPaymentCallbackLogWithIdOnly = await prisma.nowPaymentCallbackLog.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends NowPaymentCallbackLogCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, NowPaymentCallbackLogCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NowPaymentCallbackLogPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a NowPaymentCallbackLog.
   * @param {NowPaymentCallbackLogDeleteArgs} args - Arguments to delete one NowPaymentCallbackLog.
   * @example
   * // Delete one NowPaymentCallbackLog
   * const NowPaymentCallbackLog = await prisma.nowPaymentCallbackLog.delete({
   *   where: {
   *     // ... filter to delete one NowPaymentCallbackLog
   *   }
   * })
   * 
   */
  delete<T extends NowPaymentCallbackLogDeleteArgs>(args: Prisma.SelectSubset<T, NowPaymentCallbackLogDeleteArgs<ExtArgs>>): Prisma.Prisma__NowPaymentCallbackLogClient<runtime.Types.Result.GetResult<Prisma.$NowPaymentCallbackLogPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one NowPaymentCallbackLog.
   * @param {NowPaymentCallbackLogUpdateArgs} args - Arguments to update one NowPaymentCallbackLog.
   * @example
   * // Update one NowPaymentCallbackLog
   * const nowPaymentCallbackLog = await prisma.nowPaymentCallbackLog.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends NowPaymentCallbackLogUpdateArgs>(args: Prisma.SelectSubset<T, NowPaymentCallbackLogUpdateArgs<ExtArgs>>): Prisma.Prisma__NowPaymentCallbackLogClient<runtime.Types.Result.GetResult<Prisma.$NowPaymentCallbackLogPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more NowPaymentCallbackLogs.
   * @param {NowPaymentCallbackLogDeleteManyArgs} args - Arguments to filter NowPaymentCallbackLogs to delete.
   * @example
   * // Delete a few NowPaymentCallbackLogs
   * const { count } = await prisma.nowPaymentCallbackLog.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends NowPaymentCallbackLogDeleteManyArgs>(args?: Prisma.SelectSubset<T, NowPaymentCallbackLogDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NowPaymentCallbackLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NowPaymentCallbackLogUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many NowPaymentCallbackLogs
   * const nowPaymentCallbackLog = await prisma.nowPaymentCallbackLog.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends NowPaymentCallbackLogUpdateManyArgs>(args: Prisma.SelectSubset<T, NowPaymentCallbackLogUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NowPaymentCallbackLogs and returns the data updated in the database.
   * @param {NowPaymentCallbackLogUpdateManyAndReturnArgs} args - Arguments to update many NowPaymentCallbackLogs.
   * @example
   * // Update many NowPaymentCallbackLogs
   * const nowPaymentCallbackLog = await prisma.nowPaymentCallbackLog.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more NowPaymentCallbackLogs and only return the `id`
   * const nowPaymentCallbackLogWithIdOnly = await prisma.nowPaymentCallbackLog.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends NowPaymentCallbackLogUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, NowPaymentCallbackLogUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NowPaymentCallbackLogPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one NowPaymentCallbackLog.
   * @param {NowPaymentCallbackLogUpsertArgs} args - Arguments to update or create a NowPaymentCallbackLog.
   * @example
   * // Update or create a NowPaymentCallbackLog
   * const nowPaymentCallbackLog = await prisma.nowPaymentCallbackLog.upsert({
   *   create: {
   *     // ... data to create a NowPaymentCallbackLog
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the NowPaymentCallbackLog we want to update
   *   }
   * })
   */
  upsert<T extends NowPaymentCallbackLogUpsertArgs>(args: Prisma.SelectSubset<T, NowPaymentCallbackLogUpsertArgs<ExtArgs>>): Prisma.Prisma__NowPaymentCallbackLogClient<runtime.Types.Result.GetResult<Prisma.$NowPaymentCallbackLogPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of NowPaymentCallbackLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NowPaymentCallbackLogCountArgs} args - Arguments to filter NowPaymentCallbackLogs to count.
   * @example
   * // Count the number of NowPaymentCallbackLogs
   * const count = await prisma.nowPaymentCallbackLog.count({
   *   where: {
   *     // ... the filter for the NowPaymentCallbackLogs we want to count
   *   }
   * })
  **/
  count<T extends NowPaymentCallbackLogCountArgs>(
    args?: Prisma.Subset<T, NowPaymentCallbackLogCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], NowPaymentCallbackLogCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a NowPaymentCallbackLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NowPaymentCallbackLogAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends NowPaymentCallbackLogAggregateArgs>(args: Prisma.Subset<T, NowPaymentCallbackLogAggregateArgs>): Prisma.PrismaPromise<GetNowPaymentCallbackLogAggregateType<T>>

  /**
   * Group by NowPaymentCallbackLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NowPaymentCallbackLogGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends NowPaymentCallbackLogGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: NowPaymentCallbackLogGroupByArgs['orderBy'] }
      : { orderBy?: NowPaymentCallbackLogGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, NowPaymentCallbackLogGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetNowPaymentCallbackLogGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the NowPaymentCallbackLog model
 */
readonly fields: NowPaymentCallbackLogFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for NowPaymentCallbackLog.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__NowPaymentCallbackLogClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the NowPaymentCallbackLog model
 */
export interface NowPaymentCallbackLogFieldRefs {
  readonly id: Prisma.FieldRef<"NowPaymentCallbackLog", 'BigInt'>
  readonly requestHeaders: Prisma.FieldRef<"NowPaymentCallbackLog", 'Json'>
  readonly requestBody: Prisma.FieldRef<"NowPaymentCallbackLog", 'Json'>
  readonly responseStatus: Prisma.FieldRef<"NowPaymentCallbackLog", 'Int'>
  readonly responseBody: Prisma.FieldRef<"NowPaymentCallbackLog", 'Json'>
  readonly processed: Prisma.FieldRef<"NowPaymentCallbackLog", 'Boolean'>
  readonly processingError: Prisma.FieldRef<"NowPaymentCallbackLog", 'String'>
  readonly processedAt: Prisma.FieldRef<"NowPaymentCallbackLog", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"NowPaymentCallbackLog", 'DateTime'>
}
    

// Custom InputTypes
/**
 * NowPaymentCallbackLog findUnique
 */
export type NowPaymentCallbackLogFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NowPaymentCallbackLog
   */
  select?: Prisma.NowPaymentCallbackLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NowPaymentCallbackLog
   */
  omit?: Prisma.NowPaymentCallbackLogOmit<ExtArgs> | null
  /**
   * Filter, which NowPaymentCallbackLog to fetch.
   */
  where: Prisma.NowPaymentCallbackLogWhereUniqueInput
}

/**
 * NowPaymentCallbackLog findUniqueOrThrow
 */
export type NowPaymentCallbackLogFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NowPaymentCallbackLog
   */
  select?: Prisma.NowPaymentCallbackLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NowPaymentCallbackLog
   */
  omit?: Prisma.NowPaymentCallbackLogOmit<ExtArgs> | null
  /**
   * Filter, which NowPaymentCallbackLog to fetch.
   */
  where: Prisma.NowPaymentCallbackLogWhereUniqueInput
}

/**
 * NowPaymentCallbackLog findFirst
 */
export type NowPaymentCallbackLogFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NowPaymentCallbackLog
   */
  select?: Prisma.NowPaymentCallbackLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NowPaymentCallbackLog
   */
  omit?: Prisma.NowPaymentCallbackLogOmit<ExtArgs> | null
  /**
   * Filter, which NowPaymentCallbackLog to fetch.
   */
  where?: Prisma.NowPaymentCallbackLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NowPaymentCallbackLogs to fetch.
   */
  orderBy?: Prisma.NowPaymentCallbackLogOrderByWithRelationInput | Prisma.NowPaymentCallbackLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NowPaymentCallbackLogs.
   */
  cursor?: Prisma.NowPaymentCallbackLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NowPaymentCallbackLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NowPaymentCallbackLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NowPaymentCallbackLogs.
   */
  distinct?: Prisma.NowPaymentCallbackLogScalarFieldEnum | Prisma.NowPaymentCallbackLogScalarFieldEnum[]
}

/**
 * NowPaymentCallbackLog findFirstOrThrow
 */
export type NowPaymentCallbackLogFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NowPaymentCallbackLog
   */
  select?: Prisma.NowPaymentCallbackLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NowPaymentCallbackLog
   */
  omit?: Prisma.NowPaymentCallbackLogOmit<ExtArgs> | null
  /**
   * Filter, which NowPaymentCallbackLog to fetch.
   */
  where?: Prisma.NowPaymentCallbackLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NowPaymentCallbackLogs to fetch.
   */
  orderBy?: Prisma.NowPaymentCallbackLogOrderByWithRelationInput | Prisma.NowPaymentCallbackLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NowPaymentCallbackLogs.
   */
  cursor?: Prisma.NowPaymentCallbackLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NowPaymentCallbackLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NowPaymentCallbackLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NowPaymentCallbackLogs.
   */
  distinct?: Prisma.NowPaymentCallbackLogScalarFieldEnum | Prisma.NowPaymentCallbackLogScalarFieldEnum[]
}

/**
 * NowPaymentCallbackLog findMany
 */
export type NowPaymentCallbackLogFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NowPaymentCallbackLog
   */
  select?: Prisma.NowPaymentCallbackLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NowPaymentCallbackLog
   */
  omit?: Prisma.NowPaymentCallbackLogOmit<ExtArgs> | null
  /**
   * Filter, which NowPaymentCallbackLogs to fetch.
   */
  where?: Prisma.NowPaymentCallbackLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NowPaymentCallbackLogs to fetch.
   */
  orderBy?: Prisma.NowPaymentCallbackLogOrderByWithRelationInput | Prisma.NowPaymentCallbackLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing NowPaymentCallbackLogs.
   */
  cursor?: Prisma.NowPaymentCallbackLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NowPaymentCallbackLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NowPaymentCallbackLogs.
   */
  skip?: number
  distinct?: Prisma.NowPaymentCallbackLogScalarFieldEnum | Prisma.NowPaymentCallbackLogScalarFieldEnum[]
}

/**
 * NowPaymentCallbackLog create
 */
export type NowPaymentCallbackLogCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NowPaymentCallbackLog
   */
  select?: Prisma.NowPaymentCallbackLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NowPaymentCallbackLog
   */
  omit?: Prisma.NowPaymentCallbackLogOmit<ExtArgs> | null
  /**
   * The data needed to create a NowPaymentCallbackLog.
   */
  data: Prisma.XOR<Prisma.NowPaymentCallbackLogCreateInput, Prisma.NowPaymentCallbackLogUncheckedCreateInput>
}

/**
 * NowPaymentCallbackLog createMany
 */
export type NowPaymentCallbackLogCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many NowPaymentCallbackLogs.
   */
  data: Prisma.NowPaymentCallbackLogCreateManyInput | Prisma.NowPaymentCallbackLogCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * NowPaymentCallbackLog createManyAndReturn
 */
export type NowPaymentCallbackLogCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NowPaymentCallbackLog
   */
  select?: Prisma.NowPaymentCallbackLogSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the NowPaymentCallbackLog
   */
  omit?: Prisma.NowPaymentCallbackLogOmit<ExtArgs> | null
  /**
   * The data used to create many NowPaymentCallbackLogs.
   */
  data: Prisma.NowPaymentCallbackLogCreateManyInput | Prisma.NowPaymentCallbackLogCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * NowPaymentCallbackLog update
 */
export type NowPaymentCallbackLogUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NowPaymentCallbackLog
   */
  select?: Prisma.NowPaymentCallbackLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NowPaymentCallbackLog
   */
  omit?: Prisma.NowPaymentCallbackLogOmit<ExtArgs> | null
  /**
   * The data needed to update a NowPaymentCallbackLog.
   */
  data: Prisma.XOR<Prisma.NowPaymentCallbackLogUpdateInput, Prisma.NowPaymentCallbackLogUncheckedUpdateInput>
  /**
   * Choose, which NowPaymentCallbackLog to update.
   */
  where: Prisma.NowPaymentCallbackLogWhereUniqueInput
}

/**
 * NowPaymentCallbackLog updateMany
 */
export type NowPaymentCallbackLogUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update NowPaymentCallbackLogs.
   */
  data: Prisma.XOR<Prisma.NowPaymentCallbackLogUpdateManyMutationInput, Prisma.NowPaymentCallbackLogUncheckedUpdateManyInput>
  /**
   * Filter which NowPaymentCallbackLogs to update
   */
  where?: Prisma.NowPaymentCallbackLogWhereInput
  /**
   * Limit how many NowPaymentCallbackLogs to update.
   */
  limit?: number
}

/**
 * NowPaymentCallbackLog updateManyAndReturn
 */
export type NowPaymentCallbackLogUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NowPaymentCallbackLog
   */
  select?: Prisma.NowPaymentCallbackLogSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the NowPaymentCallbackLog
   */
  omit?: Prisma.NowPaymentCallbackLogOmit<ExtArgs> | null
  /**
   * The data used to update NowPaymentCallbackLogs.
   */
  data: Prisma.XOR<Prisma.NowPaymentCallbackLogUpdateManyMutationInput, Prisma.NowPaymentCallbackLogUncheckedUpdateManyInput>
  /**
   * Filter which NowPaymentCallbackLogs to update
   */
  where?: Prisma.NowPaymentCallbackLogWhereInput
  /**
   * Limit how many NowPaymentCallbackLogs to update.
   */
  limit?: number
}

/**
 * NowPaymentCallbackLog upsert
 */
export type NowPaymentCallbackLogUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NowPaymentCallbackLog
   */
  select?: Prisma.NowPaymentCallbackLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NowPaymentCallbackLog
   */
  omit?: Prisma.NowPaymentCallbackLogOmit<ExtArgs> | null
  /**
   * The filter to search for the NowPaymentCallbackLog to update in case it exists.
   */
  where: Prisma.NowPaymentCallbackLogWhereUniqueInput
  /**
   * In case the NowPaymentCallbackLog found by the `where` argument doesn't exist, create a new NowPaymentCallbackLog with this data.
   */
  create: Prisma.XOR<Prisma.NowPaymentCallbackLogCreateInput, Prisma.NowPaymentCallbackLogUncheckedCreateInput>
  /**
   * In case the NowPaymentCallbackLog was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.NowPaymentCallbackLogUpdateInput, Prisma.NowPaymentCallbackLogUncheckedUpdateInput>
}

/**
 * NowPaymentCallbackLog delete
 */
export type NowPaymentCallbackLogDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NowPaymentCallbackLog
   */
  select?: Prisma.NowPaymentCallbackLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NowPaymentCallbackLog
   */
  omit?: Prisma.NowPaymentCallbackLogOmit<ExtArgs> | null
  /**
   * Filter which NowPaymentCallbackLog to delete.
   */
  where: Prisma.NowPaymentCallbackLogWhereUniqueInput
}

/**
 * NowPaymentCallbackLog deleteMany
 */
export type NowPaymentCallbackLogDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NowPaymentCallbackLogs to delete
   */
  where?: Prisma.NowPaymentCallbackLogWhereInput
  /**
   * Limit how many NowPaymentCallbackLogs to delete.
   */
  limit?: number
}

/**
 * NowPaymentCallbackLog without action
 */
export type NowPaymentCallbackLogDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NowPaymentCallbackLog
   */
  select?: Prisma.NowPaymentCallbackLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NowPaymentCallbackLog
   */
  omit?: Prisma.NowPaymentCallbackLogOmit<ExtArgs> | null
}
