
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PrismaQueryLog` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model PrismaQueryLog
 * 
 */
export type PrismaQueryLogModel = runtime.Types.Result.DefaultSelection<Prisma.$PrismaQueryLogPayload>

export type AggregatePrismaQueryLog = {
  _count: PrismaQueryLogCountAggregateOutputType | null
  _avg: PrismaQueryLogAvgAggregateOutputType | null
  _sum: PrismaQueryLogSumAggregateOutputType | null
  _min: PrismaQueryLogMinAggregateOutputType | null
  _max: PrismaQueryLogMaxAggregateOutputType | null
}

export type PrismaQueryLogAvgAggregateOutputType = {
  id: number | null
  duration: number | null
}

export type PrismaQueryLogSumAggregateOutputType = {
  id: bigint | null
  duration: number | null
}

export type PrismaQueryLogMinAggregateOutputType = {
  id: bigint | null
  query: string | null
  duration: number | null
  createdAt: Date | null
}

export type PrismaQueryLogMaxAggregateOutputType = {
  id: bigint | null
  query: string | null
  duration: number | null
  createdAt: Date | null
}

export type PrismaQueryLogCountAggregateOutputType = {
  id: number
  query: number
  params: number
  duration: number
  createdAt: number
  _all: number
}


export type PrismaQueryLogAvgAggregateInputType = {
  id?: true
  duration?: true
}

export type PrismaQueryLogSumAggregateInputType = {
  id?: true
  duration?: true
}

export type PrismaQueryLogMinAggregateInputType = {
  id?: true
  query?: true
  duration?: true
  createdAt?: true
}

export type PrismaQueryLogMaxAggregateInputType = {
  id?: true
  query?: true
  duration?: true
  createdAt?: true
}

export type PrismaQueryLogCountAggregateInputType = {
  id?: true
  query?: true
  params?: true
  duration?: true
  createdAt?: true
  _all?: true
}

export type PrismaQueryLogAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PrismaQueryLog to aggregate.
   */
  where?: Prisma.PrismaQueryLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PrismaQueryLogs to fetch.
   */
  orderBy?: Prisma.PrismaQueryLogOrderByWithRelationInput | Prisma.PrismaQueryLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PrismaQueryLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PrismaQueryLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PrismaQueryLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PrismaQueryLogs
  **/
  _count?: true | PrismaQueryLogCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PrismaQueryLogAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PrismaQueryLogSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PrismaQueryLogMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PrismaQueryLogMaxAggregateInputType
}

export type GetPrismaQueryLogAggregateType<T extends PrismaQueryLogAggregateArgs> = {
      [P in keyof T & keyof AggregatePrismaQueryLog]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePrismaQueryLog[P]>
    : Prisma.GetScalarType<T[P], AggregatePrismaQueryLog[P]>
}




export type PrismaQueryLogGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PrismaQueryLogWhereInput
  orderBy?: Prisma.PrismaQueryLogOrderByWithAggregationInput | Prisma.PrismaQueryLogOrderByWithAggregationInput[]
  by: Prisma.PrismaQueryLogScalarFieldEnum[] | Prisma.PrismaQueryLogScalarFieldEnum
  having?: Prisma.PrismaQueryLogScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PrismaQueryLogCountAggregateInputType | true
  _avg?: PrismaQueryLogAvgAggregateInputType
  _sum?: PrismaQueryLogSumAggregateInputType
  _min?: PrismaQueryLogMinAggregateInputType
  _max?: PrismaQueryLogMaxAggregateInputType
}

export type PrismaQueryLogGroupByOutputType = {
  id: bigint
  query: string
  params: runtime.JsonValue | null
  duration: number
  createdAt: Date
  _count: PrismaQueryLogCountAggregateOutputType | null
  _avg: PrismaQueryLogAvgAggregateOutputType | null
  _sum: PrismaQueryLogSumAggregateOutputType | null
  _min: PrismaQueryLogMinAggregateOutputType | null
  _max: PrismaQueryLogMaxAggregateOutputType | null
}

type GetPrismaQueryLogGroupByPayload<T extends PrismaQueryLogGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PrismaQueryLogGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PrismaQueryLogGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PrismaQueryLogGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PrismaQueryLogGroupByOutputType[P]>
      }
    >
  >



export type PrismaQueryLogWhereInput = {
  AND?: Prisma.PrismaQueryLogWhereInput | Prisma.PrismaQueryLogWhereInput[]
  OR?: Prisma.PrismaQueryLogWhereInput[]
  NOT?: Prisma.PrismaQueryLogWhereInput | Prisma.PrismaQueryLogWhereInput[]
  id?: Prisma.BigIntFilter<"PrismaQueryLog"> | bigint | number
  query?: Prisma.StringFilter<"PrismaQueryLog"> | string
  params?: Prisma.JsonNullableFilter<"PrismaQueryLog">
  duration?: Prisma.IntFilter<"PrismaQueryLog"> | number
  createdAt?: Prisma.DateTimeFilter<"PrismaQueryLog"> | Date | string
}

export type PrismaQueryLogOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  query?: Prisma.SortOrder
  params?: Prisma.SortOrderInput | Prisma.SortOrder
  duration?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PrismaQueryLogWhereUniqueInput = Prisma.AtLeast<{
  id?: bigint | number
  AND?: Prisma.PrismaQueryLogWhereInput | Prisma.PrismaQueryLogWhereInput[]
  OR?: Prisma.PrismaQueryLogWhereInput[]
  NOT?: Prisma.PrismaQueryLogWhereInput | Prisma.PrismaQueryLogWhereInput[]
  query?: Prisma.StringFilter<"PrismaQueryLog"> | string
  params?: Prisma.JsonNullableFilter<"PrismaQueryLog">
  duration?: Prisma.IntFilter<"PrismaQueryLog"> | number
  createdAt?: Prisma.DateTimeFilter<"PrismaQueryLog"> | Date | string
}, "id">

export type PrismaQueryLogOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  query?: Prisma.SortOrder
  params?: Prisma.SortOrderInput | Prisma.SortOrder
  duration?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.PrismaQueryLogCountOrderByAggregateInput
  _avg?: Prisma.PrismaQueryLogAvgOrderByAggregateInput
  _max?: Prisma.PrismaQueryLogMaxOrderByAggregateInput
  _min?: Prisma.PrismaQueryLogMinOrderByAggregateInput
  _sum?: Prisma.PrismaQueryLogSumOrderByAggregateInput
}

export type PrismaQueryLogScalarWhereWithAggregatesInput = {
  AND?: Prisma.PrismaQueryLogScalarWhereWithAggregatesInput | Prisma.PrismaQueryLogScalarWhereWithAggregatesInput[]
  OR?: Prisma.PrismaQueryLogScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PrismaQueryLogScalarWhereWithAggregatesInput | Prisma.PrismaQueryLogScalarWhereWithAggregatesInput[]
  id?: Prisma.BigIntWithAggregatesFilter<"PrismaQueryLog"> | bigint | number
  query?: Prisma.StringWithAggregatesFilter<"PrismaQueryLog"> | string
  params?: Prisma.JsonNullableWithAggregatesFilter<"PrismaQueryLog">
  duration?: Prisma.IntWithAggregatesFilter<"PrismaQueryLog"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PrismaQueryLog"> | Date | string
}

export type PrismaQueryLogCreateInput = {
  id?: bigint | number
  query: string
  params?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  duration: number
  createdAt?: Date | string
}

export type PrismaQueryLogUncheckedCreateInput = {
  id?: bigint | number
  query: string
  params?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  duration: number
  createdAt?: Date | string
}

export type PrismaQueryLogUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  query?: Prisma.StringFieldUpdateOperationsInput | string
  params?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PrismaQueryLogUncheckedUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  query?: Prisma.StringFieldUpdateOperationsInput | string
  params?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PrismaQueryLogCreateManyInput = {
  id?: bigint | number
  query: string
  params?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  duration: number
  createdAt?: Date | string
}

export type PrismaQueryLogUpdateManyMutationInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  query?: Prisma.StringFieldUpdateOperationsInput | string
  params?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PrismaQueryLogUncheckedUpdateManyInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  query?: Prisma.StringFieldUpdateOperationsInput | string
  params?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PrismaQueryLogCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  query?: Prisma.SortOrder
  params?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PrismaQueryLogAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  duration?: Prisma.SortOrder
}

export type PrismaQueryLogMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  query?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PrismaQueryLogMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  query?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PrismaQueryLogSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  duration?: Prisma.SortOrder
}



export type PrismaQueryLogSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  query?: boolean
  params?: boolean
  duration?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["prismaQueryLog"]>

export type PrismaQueryLogSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  query?: boolean
  params?: boolean
  duration?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["prismaQueryLog"]>

export type PrismaQueryLogSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  query?: boolean
  params?: boolean
  duration?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["prismaQueryLog"]>

export type PrismaQueryLogSelectScalar = {
  id?: boolean
  query?: boolean
  params?: boolean
  duration?: boolean
  createdAt?: boolean
}

export type PrismaQueryLogOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "query" | "params" | "duration" | "createdAt", ExtArgs["result"]["prismaQueryLog"]>

export type $PrismaQueryLogPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PrismaQueryLog"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: bigint
    query: string
    params: runtime.JsonValue | null
    duration: number
    createdAt: Date
  }, ExtArgs["result"]["prismaQueryLog"]>
  composites: {}
}

export type PrismaQueryLogGetPayload<S extends boolean | null | undefined | PrismaQueryLogDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PrismaQueryLogPayload, S>

export type PrismaQueryLogCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PrismaQueryLogFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PrismaQueryLogCountAggregateInputType | true
  }

export interface PrismaQueryLogDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PrismaQueryLog'], meta: { name: 'PrismaQueryLog' } }
  /**
   * Find zero or one PrismaQueryLog that matches the filter.
   * @param {PrismaQueryLogFindUniqueArgs} args - Arguments to find a PrismaQueryLog
   * @example
   * // Get one PrismaQueryLog
   * const prismaQueryLog = await prisma.prismaQueryLog.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PrismaQueryLogFindUniqueArgs>(args: Prisma.SelectSubset<T, PrismaQueryLogFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PrismaQueryLogClient<runtime.Types.Result.GetResult<Prisma.$PrismaQueryLogPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PrismaQueryLog that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PrismaQueryLogFindUniqueOrThrowArgs} args - Arguments to find a PrismaQueryLog
   * @example
   * // Get one PrismaQueryLog
   * const prismaQueryLog = await prisma.prismaQueryLog.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PrismaQueryLogFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PrismaQueryLogFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PrismaQueryLogClient<runtime.Types.Result.GetResult<Prisma.$PrismaQueryLogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PrismaQueryLog that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrismaQueryLogFindFirstArgs} args - Arguments to find a PrismaQueryLog
   * @example
   * // Get one PrismaQueryLog
   * const prismaQueryLog = await prisma.prismaQueryLog.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PrismaQueryLogFindFirstArgs>(args?: Prisma.SelectSubset<T, PrismaQueryLogFindFirstArgs<ExtArgs>>): Prisma.Prisma__PrismaQueryLogClient<runtime.Types.Result.GetResult<Prisma.$PrismaQueryLogPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PrismaQueryLog that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrismaQueryLogFindFirstOrThrowArgs} args - Arguments to find a PrismaQueryLog
   * @example
   * // Get one PrismaQueryLog
   * const prismaQueryLog = await prisma.prismaQueryLog.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PrismaQueryLogFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PrismaQueryLogFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PrismaQueryLogClient<runtime.Types.Result.GetResult<Prisma.$PrismaQueryLogPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PrismaQueryLogs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrismaQueryLogFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PrismaQueryLogs
   * const prismaQueryLogs = await prisma.prismaQueryLog.findMany()
   * 
   * // Get first 10 PrismaQueryLogs
   * const prismaQueryLogs = await prisma.prismaQueryLog.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const prismaQueryLogWithIdOnly = await prisma.prismaQueryLog.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PrismaQueryLogFindManyArgs>(args?: Prisma.SelectSubset<T, PrismaQueryLogFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PrismaQueryLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PrismaQueryLog.
   * @param {PrismaQueryLogCreateArgs} args - Arguments to create a PrismaQueryLog.
   * @example
   * // Create one PrismaQueryLog
   * const PrismaQueryLog = await prisma.prismaQueryLog.create({
   *   data: {
   *     // ... data to create a PrismaQueryLog
   *   }
   * })
   * 
   */
  create<T extends PrismaQueryLogCreateArgs>(args: Prisma.SelectSubset<T, PrismaQueryLogCreateArgs<ExtArgs>>): Prisma.Prisma__PrismaQueryLogClient<runtime.Types.Result.GetResult<Prisma.$PrismaQueryLogPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PrismaQueryLogs.
   * @param {PrismaQueryLogCreateManyArgs} args - Arguments to create many PrismaQueryLogs.
   * @example
   * // Create many PrismaQueryLogs
   * const prismaQueryLog = await prisma.prismaQueryLog.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PrismaQueryLogCreateManyArgs>(args?: Prisma.SelectSubset<T, PrismaQueryLogCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PrismaQueryLogs and returns the data saved in the database.
   * @param {PrismaQueryLogCreateManyAndReturnArgs} args - Arguments to create many PrismaQueryLogs.
   * @example
   * // Create many PrismaQueryLogs
   * const prismaQueryLog = await prisma.prismaQueryLog.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PrismaQueryLogs and only return the `id`
   * const prismaQueryLogWithIdOnly = await prisma.prismaQueryLog.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PrismaQueryLogCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PrismaQueryLogCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PrismaQueryLogPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PrismaQueryLog.
   * @param {PrismaQueryLogDeleteArgs} args - Arguments to delete one PrismaQueryLog.
   * @example
   * // Delete one PrismaQueryLog
   * const PrismaQueryLog = await prisma.prismaQueryLog.delete({
   *   where: {
   *     // ... filter to delete one PrismaQueryLog
   *   }
   * })
   * 
   */
  delete<T extends PrismaQueryLogDeleteArgs>(args: Prisma.SelectSubset<T, PrismaQueryLogDeleteArgs<ExtArgs>>): Prisma.Prisma__PrismaQueryLogClient<runtime.Types.Result.GetResult<Prisma.$PrismaQueryLogPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PrismaQueryLog.
   * @param {PrismaQueryLogUpdateArgs} args - Arguments to update one PrismaQueryLog.
   * @example
   * // Update one PrismaQueryLog
   * const prismaQueryLog = await prisma.prismaQueryLog.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PrismaQueryLogUpdateArgs>(args: Prisma.SelectSubset<T, PrismaQueryLogUpdateArgs<ExtArgs>>): Prisma.Prisma__PrismaQueryLogClient<runtime.Types.Result.GetResult<Prisma.$PrismaQueryLogPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PrismaQueryLogs.
   * @param {PrismaQueryLogDeleteManyArgs} args - Arguments to filter PrismaQueryLogs to delete.
   * @example
   * // Delete a few PrismaQueryLogs
   * const { count } = await prisma.prismaQueryLog.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PrismaQueryLogDeleteManyArgs>(args?: Prisma.SelectSubset<T, PrismaQueryLogDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PrismaQueryLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrismaQueryLogUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PrismaQueryLogs
   * const prismaQueryLog = await prisma.prismaQueryLog.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PrismaQueryLogUpdateManyArgs>(args: Prisma.SelectSubset<T, PrismaQueryLogUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PrismaQueryLogs and returns the data updated in the database.
   * @param {PrismaQueryLogUpdateManyAndReturnArgs} args - Arguments to update many PrismaQueryLogs.
   * @example
   * // Update many PrismaQueryLogs
   * const prismaQueryLog = await prisma.prismaQueryLog.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PrismaQueryLogs and only return the `id`
   * const prismaQueryLogWithIdOnly = await prisma.prismaQueryLog.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PrismaQueryLogUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PrismaQueryLogUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PrismaQueryLogPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PrismaQueryLog.
   * @param {PrismaQueryLogUpsertArgs} args - Arguments to update or create a PrismaQueryLog.
   * @example
   * // Update or create a PrismaQueryLog
   * const prismaQueryLog = await prisma.prismaQueryLog.upsert({
   *   create: {
   *     // ... data to create a PrismaQueryLog
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PrismaQueryLog we want to update
   *   }
   * })
   */
  upsert<T extends PrismaQueryLogUpsertArgs>(args: Prisma.SelectSubset<T, PrismaQueryLogUpsertArgs<ExtArgs>>): Prisma.Prisma__PrismaQueryLogClient<runtime.Types.Result.GetResult<Prisma.$PrismaQueryLogPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PrismaQueryLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrismaQueryLogCountArgs} args - Arguments to filter PrismaQueryLogs to count.
   * @example
   * // Count the number of PrismaQueryLogs
   * const count = await prisma.prismaQueryLog.count({
   *   where: {
   *     // ... the filter for the PrismaQueryLogs we want to count
   *   }
   * })
  **/
  count<T extends PrismaQueryLogCountArgs>(
    args?: Prisma.Subset<T, PrismaQueryLogCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PrismaQueryLogCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PrismaQueryLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrismaQueryLogAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PrismaQueryLogAggregateArgs>(args: Prisma.Subset<T, PrismaQueryLogAggregateArgs>): Prisma.PrismaPromise<GetPrismaQueryLogAggregateType<T>>

  /**
   * Group by PrismaQueryLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrismaQueryLogGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PrismaQueryLogGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PrismaQueryLogGroupByArgs['orderBy'] }
      : { orderBy?: PrismaQueryLogGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PrismaQueryLogGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPrismaQueryLogGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PrismaQueryLog model
 */
readonly fields: PrismaQueryLogFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PrismaQueryLog.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PrismaQueryLogClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PrismaQueryLog model
 */
export interface PrismaQueryLogFieldRefs {
  readonly id: Prisma.FieldRef<"PrismaQueryLog", 'BigInt'>
  readonly query: Prisma.FieldRef<"PrismaQueryLog", 'String'>
  readonly params: Prisma.FieldRef<"PrismaQueryLog", 'Json'>
  readonly duration: Prisma.FieldRef<"PrismaQueryLog", 'Int'>
  readonly createdAt: Prisma.FieldRef<"PrismaQueryLog", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PrismaQueryLog findUnique
 */
export type PrismaQueryLogFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrismaQueryLog
   */
  select?: Prisma.PrismaQueryLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrismaQueryLog
   */
  omit?: Prisma.PrismaQueryLogOmit<ExtArgs> | null
  /**
   * Filter, which PrismaQueryLog to fetch.
   */
  where: Prisma.PrismaQueryLogWhereUniqueInput
}

/**
 * PrismaQueryLog findUniqueOrThrow
 */
export type PrismaQueryLogFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrismaQueryLog
   */
  select?: Prisma.PrismaQueryLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrismaQueryLog
   */
  omit?: Prisma.PrismaQueryLogOmit<ExtArgs> | null
  /**
   * Filter, which PrismaQueryLog to fetch.
   */
  where: Prisma.PrismaQueryLogWhereUniqueInput
}

/**
 * PrismaQueryLog findFirst
 */
export type PrismaQueryLogFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrismaQueryLog
   */
  select?: Prisma.PrismaQueryLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrismaQueryLog
   */
  omit?: Prisma.PrismaQueryLogOmit<ExtArgs> | null
  /**
   * Filter, which PrismaQueryLog to fetch.
   */
  where?: Prisma.PrismaQueryLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PrismaQueryLogs to fetch.
   */
  orderBy?: Prisma.PrismaQueryLogOrderByWithRelationInput | Prisma.PrismaQueryLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PrismaQueryLogs.
   */
  cursor?: Prisma.PrismaQueryLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PrismaQueryLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PrismaQueryLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PrismaQueryLogs.
   */
  distinct?: Prisma.PrismaQueryLogScalarFieldEnum | Prisma.PrismaQueryLogScalarFieldEnum[]
}

/**
 * PrismaQueryLog findFirstOrThrow
 */
export type PrismaQueryLogFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrismaQueryLog
   */
  select?: Prisma.PrismaQueryLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrismaQueryLog
   */
  omit?: Prisma.PrismaQueryLogOmit<ExtArgs> | null
  /**
   * Filter, which PrismaQueryLog to fetch.
   */
  where?: Prisma.PrismaQueryLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PrismaQueryLogs to fetch.
   */
  orderBy?: Prisma.PrismaQueryLogOrderByWithRelationInput | Prisma.PrismaQueryLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PrismaQueryLogs.
   */
  cursor?: Prisma.PrismaQueryLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PrismaQueryLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PrismaQueryLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PrismaQueryLogs.
   */
  distinct?: Prisma.PrismaQueryLogScalarFieldEnum | Prisma.PrismaQueryLogScalarFieldEnum[]
}

/**
 * PrismaQueryLog findMany
 */
export type PrismaQueryLogFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrismaQueryLog
   */
  select?: Prisma.PrismaQueryLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrismaQueryLog
   */
  omit?: Prisma.PrismaQueryLogOmit<ExtArgs> | null
  /**
   * Filter, which PrismaQueryLogs to fetch.
   */
  where?: Prisma.PrismaQueryLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PrismaQueryLogs to fetch.
   */
  orderBy?: Prisma.PrismaQueryLogOrderByWithRelationInput | Prisma.PrismaQueryLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PrismaQueryLogs.
   */
  cursor?: Prisma.PrismaQueryLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PrismaQueryLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PrismaQueryLogs.
   */
  skip?: number
  distinct?: Prisma.PrismaQueryLogScalarFieldEnum | Prisma.PrismaQueryLogScalarFieldEnum[]
}

/**
 * PrismaQueryLog create
 */
export type PrismaQueryLogCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrismaQueryLog
   */
  select?: Prisma.PrismaQueryLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrismaQueryLog
   */
  omit?: Prisma.PrismaQueryLogOmit<ExtArgs> | null
  /**
   * The data needed to create a PrismaQueryLog.
   */
  data: Prisma.XOR<Prisma.PrismaQueryLogCreateInput, Prisma.PrismaQueryLogUncheckedCreateInput>
}

/**
 * PrismaQueryLog createMany
 */
export type PrismaQueryLogCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PrismaQueryLogs.
   */
  data: Prisma.PrismaQueryLogCreateManyInput | Prisma.PrismaQueryLogCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PrismaQueryLog createManyAndReturn
 */
export type PrismaQueryLogCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrismaQueryLog
   */
  select?: Prisma.PrismaQueryLogSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PrismaQueryLog
   */
  omit?: Prisma.PrismaQueryLogOmit<ExtArgs> | null
  /**
   * The data used to create many PrismaQueryLogs.
   */
  data: Prisma.PrismaQueryLogCreateManyInput | Prisma.PrismaQueryLogCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PrismaQueryLog update
 */
export type PrismaQueryLogUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrismaQueryLog
   */
  select?: Prisma.PrismaQueryLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrismaQueryLog
   */
  omit?: Prisma.PrismaQueryLogOmit<ExtArgs> | null
  /**
   * The data needed to update a PrismaQueryLog.
   */
  data: Prisma.XOR<Prisma.PrismaQueryLogUpdateInput, Prisma.PrismaQueryLogUncheckedUpdateInput>
  /**
   * Choose, which PrismaQueryLog to update.
   */
  where: Prisma.PrismaQueryLogWhereUniqueInput
}

/**
 * PrismaQueryLog updateMany
 */
export type PrismaQueryLogUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PrismaQueryLogs.
   */
  data: Prisma.XOR<Prisma.PrismaQueryLogUpdateManyMutationInput, Prisma.PrismaQueryLogUncheckedUpdateManyInput>
  /**
   * Filter which PrismaQueryLogs to update
   */
  where?: Prisma.PrismaQueryLogWhereInput
  /**
   * Limit how many PrismaQueryLogs to update.
   */
  limit?: number
}

/**
 * PrismaQueryLog updateManyAndReturn
 */
export type PrismaQueryLogUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrismaQueryLog
   */
  select?: Prisma.PrismaQueryLogSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PrismaQueryLog
   */
  omit?: Prisma.PrismaQueryLogOmit<ExtArgs> | null
  /**
   * The data used to update PrismaQueryLogs.
   */
  data: Prisma.XOR<Prisma.PrismaQueryLogUpdateManyMutationInput, Prisma.PrismaQueryLogUncheckedUpdateManyInput>
  /**
   * Filter which PrismaQueryLogs to update
   */
  where?: Prisma.PrismaQueryLogWhereInput
  /**
   * Limit how many PrismaQueryLogs to update.
   */
  limit?: number
}

/**
 * PrismaQueryLog upsert
 */
export type PrismaQueryLogUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrismaQueryLog
   */
  select?: Prisma.PrismaQueryLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrismaQueryLog
   */
  omit?: Prisma.PrismaQueryLogOmit<ExtArgs> | null
  /**
   * The filter to search for the PrismaQueryLog to update in case it exists.
   */
  where: Prisma.PrismaQueryLogWhereUniqueInput
  /**
   * In case the PrismaQueryLog found by the `where` argument doesn't exist, create a new PrismaQueryLog with this data.
   */
  create: Prisma.XOR<Prisma.PrismaQueryLogCreateInput, Prisma.PrismaQueryLogUncheckedCreateInput>
  /**
   * In case the PrismaQueryLog was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PrismaQueryLogUpdateInput, Prisma.PrismaQueryLogUncheckedUpdateInput>
}

/**
 * PrismaQueryLog delete
 */
export type PrismaQueryLogDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrismaQueryLog
   */
  select?: Prisma.PrismaQueryLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrismaQueryLog
   */
  omit?: Prisma.PrismaQueryLogOmit<ExtArgs> | null
  /**
   * Filter which PrismaQueryLog to delete.
   */
  where: Prisma.PrismaQueryLogWhereUniqueInput
}

/**
 * PrismaQueryLog deleteMany
 */
export type PrismaQueryLogDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PrismaQueryLogs to delete
   */
  where?: Prisma.PrismaQueryLogWhereInput
  /**
   * Limit how many PrismaQueryLogs to delete.
   */
  limit?: number
}

/**
 * PrismaQueryLog without action
 */
export type PrismaQueryLogDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PrismaQueryLog
   */
  select?: Prisma.PrismaQueryLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PrismaQueryLog
   */
  omit?: Prisma.PrismaQueryLogOmit<ExtArgs> | null
}
