
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.js"
import * as $Class from "./internal/class.js"
import * as Prisma from "./internal/prismaNamespace.js"

export * as $Enums from './enums.js'
export * from "./enums.js"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more Users
 * const users = await prisma.user.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model UserSession
 * 
 */
export type UserSession = Prisma.UserSessionModel
/**
 * Model UserBalance
 * 
 */
export type UserBalance = Prisma.UserBalanceModel
/**
 * Model UserBalanceStats
 * 
 */
export type UserBalanceStats = Prisma.UserBalanceStatsModel
/**
 * Model ActivityLog
 * 
 */
export type ActivityLog = Prisma.ActivityLogModel
/**
 * Model Game
 * 
 */
export type Game = Prisma.GameModel
/**
 * Model GameTranslation
 * 
 */
export type GameTranslation = Prisma.GameTranslationModel
/**
 * Model WhitecliffApiLog
 * 
 */
export type WhitecliffApiLog = Prisma.WhitecliffApiLogModel
/**
 * Model DcsApiLog
 * 
 */
export type DcsApiLog = Prisma.DcsApiLogModel
/**
 * Model Transaction
 * 
 */
export type Transaction = Prisma.TransactionModel
/**
 * Model GameRound
 * 
 */
export type GameRound = Prisma.GameRoundModel
/**
 * Model GameBet
 * 
 */
export type GameBet = Prisma.GameBetModel
/**
 * Model GameWin
 * 
 */
export type GameWin = Prisma.GameWinModel
/**
 * Model TransactionBalanceDetail
 * 
 */
export type TransactionBalanceDetail = Prisma.TransactionBalanceDetailModel
/**
 * Model BonusDetail
 * 
 */
export type BonusDetail = Prisma.BonusDetailModel
/**
 * Model DepositDetail
 * 
 */
export type DepositDetail = Prisma.DepositDetailModel
/**
 * Model WithdrawDetail
 * 
 */
export type WithdrawDetail = Prisma.WithdrawDetailModel
/**
 * Model CompTransaction
 * 
 */
export type CompTransaction = Prisma.CompTransactionModel
/**
 * Model DailyCompEarning
 * 
 */
export type DailyCompEarning = Prisma.DailyCompEarningModel
/**
 * Model Promotion
 * 
 */
export type Promotion = Prisma.PromotionModel
/**
 * Model PromotionTranslation
 * 
 */
export type PromotionTranslation = Prisma.PromotionTranslationModel
/**
 * Model UserPromotion
 * 
 */
export type UserPromotion = Prisma.UserPromotionModel
/**
 * Model NowPaymentCallbackLog
 * 
 */
export type NowPaymentCallbackLog = Prisma.NowPaymentCallbackLogModel
/**
 * Model ExchangeRate
 * 
 */
export type ExchangeRate = Prisma.ExchangeRateModel
/**
 * Model VipLevel
 * 
 */
export type VipLevel = Prisma.VipLevelModel
/**
 * Model VipMembership
 * 
 */
export type VipMembership = Prisma.VipMembershipModel
/**
 * Model VipHistory
 * 
 */
export type VipHistory = Prisma.VipHistoryModel
/**
 * Model Rolling
 * 
 */
export type Rolling = Prisma.RollingModel
/**
 * Model UserToken
 * 
 */
export type UserToken = Prisma.UserTokenModel
/**
 * Model EmailLog
 * 
 */
export type EmailLog = Prisma.EmailLogModel
/**
 * Model GameSession
 * 
 */
export type GameSession = Prisma.GameSessionModel
/**
 * Model BankAccount
 * 
 */
export type BankAccount = Prisma.BankAccountModel
/**
 * Model PrismaQueryLog
 * 
 */
export type PrismaQueryLog = Prisma.PrismaQueryLogModel
/**
 * Model AffiliateCode
 * 
 */
export type AffiliateCode = Prisma.AffiliateCodeModel
/**
 * Model Referral
 * 
 */
export type Referral = Prisma.ReferralModel
/**
 * Model AffiliateWallet
 * 
 */
export type AffiliateWallet = Prisma.AffiliateWalletModel
/**
 * Model AffiliateCommission
 * 
 */
export type AffiliateCommission = Prisma.AffiliateCommissionModel
/**
 * Model AffiliateTier
 * 
 */
export type AffiliateTier = Prisma.AffiliateTierModel
