export enum FileUsageType {
  USER_AVATAR = 'USER_AVATAR',
  CASINO_PROVIDER_LOGO = 'CASINO_PROVIDER_LOGO',
  CASINO_CATEGORY_ICON = 'CASINO_CATEGORY_ICON',
  CASINO_CATEGORY_BANNER = 'CASINO_CATEGORY_BANNER',
  TIER_IMAGE = 'TIER_IMAGE',
  CHAT_MESSAGE = 'CHAT_MESSAGE',
  SUPPORT_CHAT_MESSAGE = 'SUPPORT_CHAT_MESSAGE',
  QUEST_ICON = 'QUEST_ICON',
  // Add more types here as needed
  // BANNER = 'BANNER',
  // POST_IMAGE = 'POST_IMAGE',
}
