export enum FileUsageType {
  USER_AVATAR = 'USER_AVATAR',
  CASINO_PROVIDER_LOGO = 'CASINO_PROVIDER_LOGO',
  CASINO_CATEGORY_ICON = 'CASINO_CATEGORY_ICON',
  CASINO_CATEGORY_BANNER = 'CASINO_CATEGORY_BANNER',
  TIER_IMAGE = 'TIER_IMAGE',
  CHAT_MESSAGE = 'CHAT_MESSAGE',
  SUPPORT_CHAT_MESSAGE = 'SUPPORT_CHAT_MESSAGE',
  ARTIFACT_CATALOG_IMAGE = 'ARTIFACT_CATALOG_IMAGE',
}
