export enum FileUsageType {
    USER_PROFILE = 'USER_PROFILE',
    CASINO_PROVIDER_LOGO = 'CASINO_PROVIDER_LOGO',
    CASINO_CATEGORY_ICON = 'CASINO_CATEGORY_ICON',
    CASINO_CATEGORY_BANNER = 'CASINO_CATEGORY_BANNER',
    // Add more types here as needed
    // BANNER = 'BANNER',
    // POST_IMAGE = 'POST_IMAGE',
}
