/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/vue-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationReturnType
} from '@tanstack/vue-query';

import {
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  CreateDepositRequestDto,
  CreateDepositResponseDto
} from '../../models';

import { customInstance } from '../../axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary 입금 요청
 */
export const depositControllerCreateDeposit = (
    createDepositRequestDto: MaybeRef<CreateDepositRequestDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      createDepositRequestDto = unref(createDepositRequestDto);
      
      return customInstance<CreateDepositResponseDto>(
      {url: `/deposits`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createDepositRequestDto, signal
    },
      options);
    }
  


export const getDepositControllerCreateDepositMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof depositControllerCreateDeposit>>, TError,{data: CreateDepositRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof depositControllerCreateDeposit>>, TError,{data: CreateDepositRequestDto}, TContext> => {

const mutationKey = ['depositControllerCreateDeposit'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof depositControllerCreateDeposit>>, {data: CreateDepositRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  depositControllerCreateDeposit(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DepositControllerCreateDepositMutationResult = NonNullable<Awaited<ReturnType<typeof depositControllerCreateDeposit>>>
    export type DepositControllerCreateDepositMutationBody = CreateDepositRequestDto
    export type DepositControllerCreateDepositMutationError = void

    /**
 * @summary 입금 요청
 */
export const useDepositControllerCreateDeposit = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof depositControllerCreateDeposit>>, TError,{data: CreateDepositRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof depositControllerCreateDeposit>>,
        TError,
        {data: CreateDepositRequestDto},
        TContext
      > => {

      const mutationOptions = getDepositControllerCreateDepositMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    