import { SupportStatus, SupportPriority } from '@prisma/client';
import { SupportException } from '../support.exception';
import { MessageCode } from '@repo/shared';

export interface SupportTicketProps {
    id: bigint;
    userId: bigint;
    adminId: bigint | null;
    roomId: bigint;
    category: string | null;
    subject: string | null;
    status: SupportStatus;
    priority: SupportPriority;
    closedAt: Date | null;
    createdAt: Date;
    updatedAt: Date;
}

export class SupportTicket {
    private constructor(private _props: SupportTicketProps) { }

    static create(params: {
        userId: bigint;
        roomId: bigint;
        category?: string;
        subject?: string;
        priority?: SupportPriority;
    }): SupportTicket {
        const now = new Date();
        return new SupportTicket({
            id: 0n, // Placeholder, usually generated by DB (autoincrement)
            userId: params.userId,
            adminId: null,
            roomId: params.roomId,
            category: params.category ?? null,
            subject: params.subject ?? null,
            status: SupportStatus.OPEN,
            priority: params.priority ?? SupportPriority.NORMAL,
            closedAt: null,
            createdAt: now,
            updatedAt: now,
        });
    }

    static fromPersistence(props: SupportTicketProps): SupportTicket {
        return new SupportTicket(props);
    }

    // Getters
    get id(): bigint { return this._props.id; }
    get userId(): bigint { return this._props.userId; }
    get adminId(): bigint | null { return this._props.adminId; }
    get roomId(): bigint { return this._props.roomId; }
    get category(): string | null { return this._props.category; }
    get subject(): string | null { return this._props.subject; }
    get status(): SupportStatus { return this._props.status; }
    get priority(): SupportPriority { return this._props.priority; }
    get closedAt(): Date | null { return this._props.closedAt; }
    get createdAt(): Date { return this._props.createdAt; }
    get updatedAt(): Date { return this._props.updatedAt; }

    // Business Logic
    public assign(adminId: bigint): void {
        if (this._props.status === SupportStatus.CLOSED) {
            throw new SupportException('Cannot assign a closed ticket', MessageCode.VALIDATION_ERROR);
        }
        this._props.adminId = adminId;
        this._props.status = SupportStatus.IN_PROGRESS;
        this._props.updatedAt = new Date();
    }

    public close(): void {
        if (this._props.status === SupportStatus.CLOSED) {
            return;
        }
        this._props.status = SupportStatus.CLOSED;
        this._props.closedAt = new Date();
        this._props.updatedAt = new Date();
    }

    public updatePriority(priority: SupportPriority): void {
        this._props.priority = priority;
        this._props.updatedAt = new Date();
    }

    public setPending(): void {
        if (this._props.status === SupportStatus.CLOSED) {
            throw new SupportException('Cannot set a closed ticket to pending', MessageCode.VALIDATION_ERROR);
        }
        this._props.status = SupportStatus.PENDING;
        this._props.updatedAt = new Date();
    }
}
