export const TIER_REPOSITORY = Symbol('TIER_REPOSITORY');
export const USER_TIER_REPOSITORY = Symbol('USER_TIER_REPOSITORY');
export const TIER_HISTORY_REPOSITORY = Symbol('TIER_HISTORY_REPOSITORY');
