/* Jest mock for @repo/shared used in unit tests */
export const MessageCode = {
  ARTIFACT_POLICY_NOT_FOUND: 'ARTIFACT_POLICY_NOT_FOUND',
  ARTIFACT_NOT_FOUND: 'ARTIFACT_NOT_FOUND',
  ARTIFACT_CODE_DUPLICATED: 'ARTIFACT_CODE_DUPLICATED',
  ARTIFACT_INVALID_PROBABILITY: 'ARTIFACT_INVALID_PROBABILITY',
  ARTIFACT_PROBABILITY_OUT_OF_RANGE: 'ARTIFACT_PROBABILITY_OUT_OF_RANGE',
  ARTIFACT_PROBABILITY_SUM_INVALID: 'ARTIFACT_PROBABILITY_SUM_INVALID',
  ARTIFACT_GRADES_INCOMPLETE: 'ARTIFACT_GRADES_INCOMPLETE',
  ARTIFACT_INVALID_POLICY: 'ARTIFACT_INVALID_POLICY',
  ARTIFACT_INVALID_DRAW_PRICE: 'ARTIFACT_INVALID_DRAW_PRICE',
  ARTIFACT_INVALID_DRAW_PRICE_VALUE: 'ARTIFACT_INVALID_DRAW_PRICE_VALUE',
  ARTIFACT_INVALID_SYNTHESIS_CONFIG: 'ARTIFACT_INVALID_SYNTHESIS_CONFIG',
  ARTIFACT_INVALID_SYNTHESIS_REQUIRED_COUNT: 'ARTIFACT_INVALID_SYNTHESIS_REQUIRED_COUNT',
  ARTIFACT_INVALID_SYNTHESIS_SUCCESS_RATE: 'ARTIFACT_INVALID_SYNTHESIS_SUCCESS_RATE',
  ARTIFACT_INVALID_SYNTHESIS_GUARANTEED_COUNT: 'ARTIFACT_INVALID_SYNTHESIS_GUARANTEED_COUNT',
  ARTIFACT_POLICY_INCOMPLETE: 'ARTIFACT_POLICY_INCOMPLETE',
} as const;
export type MessageCode = (typeof MessageCode)[keyof typeof MessageCode];
