/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  computed,
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  CreateBankDepositRequestDto,
  CreateCryptoDepositRequestDto,
  DepositControllerCancelDeposit200,
  DepositControllerCreateBankDeposit201,
  DepositControllerCreateCryptoDeposit201,
  DepositControllerGetAvailableMethods200,
  DepositControllerGetDepositDetail200,
  DepositControllerGetMyDeposits200,
  DepositControllerGetMyDepositsParams,
  ErrorResponseDto
} from '../../models';

import { customInstance } from '../../axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve list of available deposit methods (crypto, bank transfer). (사용 가능한 입금 수단 목록을 조회합니다.)
 * @summary Get available deposit methods / 사용 가능한 입금 수단 조회
 */
export const depositControllerGetAvailableMethods = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<DepositControllerGetAvailableMethods200>(
      {url: `/deposits/methods`, method: 'GET', signal
    },
      options);
    }
  



export const getDepositControllerGetAvailableMethodsQueryKey = () => {
    return [
    'deposits','methods'
    ] as const;
    }

    
export const getDepositControllerGetAvailableMethodsQueryOptions = <TData = Awaited<ReturnType<typeof depositControllerGetAvailableMethods>>, TError = ErrorResponseDto>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof depositControllerGetAvailableMethods>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getDepositControllerGetAvailableMethodsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof depositControllerGetAvailableMethods>>> = ({ signal }) => depositControllerGetAvailableMethods(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof depositControllerGetAvailableMethods>>, TError, TData> 
}

export type DepositControllerGetAvailableMethodsQueryResult = NonNullable<Awaited<ReturnType<typeof depositControllerGetAvailableMethods>>>
export type DepositControllerGetAvailableMethodsQueryError = ErrorResponseDto


/**
 * @summary Get available deposit methods / 사용 가능한 입금 수단 조회
 */

export function useDepositControllerGetAvailableMethods<TData = Awaited<ReturnType<typeof depositControllerGetAvailableMethods>>, TError = ErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof depositControllerGetAvailableMethods>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDepositControllerGetAvailableMethodsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




/**
 * Retrieve my deposit history with pagination. (내 입금 내역을 페이징하여 조회합니다.)
 * @summary Get my deposit list / 내 입금 목록 조회
 */
export const depositControllerGetMyDeposits = (
    params?: MaybeRef<DepositControllerGetMyDepositsParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = unref(params);
      
      return customInstance<DepositControllerGetMyDeposits200>(
      {url: `/deposits`, method: 'GET',
        params: unref(params), signal
    },
      options);
    }
  



export const getDepositControllerGetMyDepositsQueryKey = (params?: MaybeRef<DepositControllerGetMyDepositsParams>,) => {
    return [
    'deposits', ...(params ? [params]: [])
    ] as const;
    }

    
export const getDepositControllerGetMyDepositsQueryOptions = <TData = Awaited<ReturnType<typeof depositControllerGetMyDeposits>>, TError = ErrorResponseDto>(params?: MaybeRef<DepositControllerGetMyDepositsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof depositControllerGetMyDeposits>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getDepositControllerGetMyDepositsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof depositControllerGetMyDeposits>>> = ({ signal }) => depositControllerGetMyDeposits(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof depositControllerGetMyDeposits>>, TError, TData> 
}

export type DepositControllerGetMyDepositsQueryResult = NonNullable<Awaited<ReturnType<typeof depositControllerGetMyDeposits>>>
export type DepositControllerGetMyDepositsQueryError = ErrorResponseDto


/**
 * @summary Get my deposit list / 내 입금 목록 조회
 */

export function useDepositControllerGetMyDeposits<TData = Awaited<ReturnType<typeof depositControllerGetMyDeposits>>, TError = ErrorResponseDto>(
 params?: MaybeRef<DepositControllerGetMyDepositsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof depositControllerGetMyDeposits>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDepositControllerGetMyDepositsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




/**
 * Retrieve detailed information of a specific deposit. (특정 입금의 상세 정보를 조회합니다.)
 * @summary Get deposit detail / 입금 상세 조회
 */
export const depositControllerGetDepositDetail = (
    uid: MaybeRef<string>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      uid = unref(uid);
      
      return customInstance<DepositControllerGetDepositDetail200>(
      {url: `/deposits/${uid}`, method: 'GET', signal
    },
      options);
    }
  



export const getDepositControllerGetDepositDetailQueryKey = (uid?: MaybeRef<string>,) => {
    return [
    'deposits',uid
    ] as const;
    }

    
export const getDepositControllerGetDepositDetailQueryOptions = <TData = Awaited<ReturnType<typeof depositControllerGetDepositDetail>>, TError = ErrorResponseDto>(uid: MaybeRef<string>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof depositControllerGetDepositDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getDepositControllerGetDepositDetailQueryKey(uid);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof depositControllerGetDepositDetail>>> = ({ signal }) => depositControllerGetDepositDetail(uid, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(uid))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof depositControllerGetDepositDetail>>, TError, TData> 
}

export type DepositControllerGetDepositDetailQueryResult = NonNullable<Awaited<ReturnType<typeof depositControllerGetDepositDetail>>>
export type DepositControllerGetDepositDetailQueryError = ErrorResponseDto


/**
 * @summary Get deposit detail / 입금 상세 조회
 */

export function useDepositControllerGetDepositDetail<TData = Awaited<ReturnType<typeof depositControllerGetDepositDetail>>, TError = ErrorResponseDto>(
 uid: MaybeRef<string>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof depositControllerGetDepositDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDepositControllerGetDepositDetailQueryOptions(uid,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




/**
 * Cancel a pending deposit request. (대기 중인 입금 요청을 취소합니다.)
 * @summary Cancel deposit request / 입금 신청 취소
 */
export const depositControllerCancelDeposit = (
    uid: MaybeRef<string>,
 options?: SecondParameter<typeof customInstance>,) => {
      uid = unref(uid);
      
      return customInstance<DepositControllerCancelDeposit200>(
      {url: `/deposits/${uid}`, method: 'DELETE'
    },
      options);
    }
  


export const getDepositControllerCancelDepositMutationOptions = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof depositControllerCancelDeposit>>, TError,{uid: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof depositControllerCancelDeposit>>, TError,{uid: string}, TContext> => {

const mutationKey = ['depositControllerCancelDeposit'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof depositControllerCancelDeposit>>, {uid: string}> = (props) => {
          const {uid} = props ?? {};

          return  depositControllerCancelDeposit(uid,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DepositControllerCancelDepositMutationResult = NonNullable<Awaited<ReturnType<typeof depositControllerCancelDeposit>>>
    
    export type DepositControllerCancelDepositMutationError = ErrorResponseDto

    /**
 * @summary Cancel deposit request / 입금 신청 취소
 */
export const useDepositControllerCancelDeposit = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof depositControllerCancelDeposit>>, TError,{uid: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof depositControllerCancelDeposit>>,
        TError,
        {uid: string},
        TContext
      > => {

      const mutationOptions = getDepositControllerCancelDepositMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Create a new cryptocurrency deposit request. (새로운 암호화폐 입금 요청을 생성합니다.)
 * @summary Create crypto deposit request / 암호화폐 입금 요청 생성
 */
export const depositControllerCreateCryptoDeposit = (
    createCryptoDepositRequestDto: MaybeRef<CreateCryptoDepositRequestDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      createCryptoDepositRequestDto = unref(createCryptoDepositRequestDto);
      
      return customInstance<DepositControllerCreateCryptoDeposit201>(
      {url: `/deposits/crypto`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCryptoDepositRequestDto, signal
    },
      options);
    }
  


export const getDepositControllerCreateCryptoDepositMutationOptions = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof depositControllerCreateCryptoDeposit>>, TError,{data: CreateCryptoDepositRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof depositControllerCreateCryptoDeposit>>, TError,{data: CreateCryptoDepositRequestDto}, TContext> => {

const mutationKey = ['depositControllerCreateCryptoDeposit'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof depositControllerCreateCryptoDeposit>>, {data: CreateCryptoDepositRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  depositControllerCreateCryptoDeposit(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DepositControllerCreateCryptoDepositMutationResult = NonNullable<Awaited<ReturnType<typeof depositControllerCreateCryptoDeposit>>>
    export type DepositControllerCreateCryptoDepositMutationBody = CreateCryptoDepositRequestDto
    export type DepositControllerCreateCryptoDepositMutationError = ErrorResponseDto

    /**
 * @summary Create crypto deposit request / 암호화폐 입금 요청 생성
 */
export const useDepositControllerCreateCryptoDeposit = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof depositControllerCreateCryptoDeposit>>, TError,{data: CreateCryptoDepositRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof depositControllerCreateCryptoDeposit>>,
        TError,
        {data: CreateCryptoDepositRequestDto},
        TContext
      > => {

      const mutationOptions = getDepositControllerCreateCryptoDepositMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Create a new bank transfer deposit request. (새로운 무통장 입금 요청을 생성합니다.)
 * @summary Create bank deposit request / 무통장 입금 요청 생성
 */
export const depositControllerCreateBankDeposit = (
    createBankDepositRequestDto: MaybeRef<CreateBankDepositRequestDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      createBankDepositRequestDto = unref(createBankDepositRequestDto);
      
      return customInstance<DepositControllerCreateBankDeposit201>(
      {url: `/deposits/bank`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createBankDepositRequestDto, signal
    },
      options);
    }
  


export const getDepositControllerCreateBankDepositMutationOptions = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof depositControllerCreateBankDeposit>>, TError,{data: CreateBankDepositRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof depositControllerCreateBankDeposit>>, TError,{data: CreateBankDepositRequestDto}, TContext> => {

const mutationKey = ['depositControllerCreateBankDeposit'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof depositControllerCreateBankDeposit>>, {data: CreateBankDepositRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  depositControllerCreateBankDeposit(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DepositControllerCreateBankDepositMutationResult = NonNullable<Awaited<ReturnType<typeof depositControllerCreateBankDeposit>>>
    export type DepositControllerCreateBankDepositMutationBody = CreateBankDepositRequestDto
    export type DepositControllerCreateBankDepositMutationError = ErrorResponseDto

    /**
 * @summary Create bank deposit request / 무통장 입금 요청 생성
 */
export const useDepositControllerCreateBankDeposit = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof depositControllerCreateBankDeposit>>, TError,{data: CreateBankDepositRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof depositControllerCreateBankDeposit>>,
        TError,
        {data: CreateBankDepositRequestDto},
        TContext
      > => {

      const mutationOptions = getDepositControllerCreateBankDepositMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    