/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  ChangePasswordRequestDto,
  CredentialUserControllerChangePassword200,
  CredentialUserControllerCheckStatus200,
  CredentialUserControllerLogin200,
  CredentialUserControllerLogout200,
  CredentialUserControllerRequestPasswordReset200,
  CredentialUserControllerResetPassword200,
  CredentialUserLoginRequestDto,
  ErrorResponseDto,
  RegisterRequestDto,
  RegistrationControllerRegister201,
  RequestPasswordResetRequestDto,
  ResetPasswordRequestDto
} from '../../models';

import { customInstance } from '../../axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Email/Password 기반 로그인
 * @summary Login (로그인)
 */
export const credentialUserControllerLogin = (
    credentialUserLoginRequestDto: MaybeRef<CredentialUserLoginRequestDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      credentialUserLoginRequestDto = unref(credentialUserLoginRequestDto);
      
      return customInstance<CredentialUserControllerLogin200>(
      {url: `/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: credentialUserLoginRequestDto, signal
    },
      options);
    }
  


export const getCredentialUserControllerLoginMutationOptions = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof credentialUserControllerLogin>>, TError,{data: CredentialUserLoginRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof credentialUserControllerLogin>>, TError,{data: CredentialUserLoginRequestDto}, TContext> => {

const mutationKey = ['credentialUserControllerLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof credentialUserControllerLogin>>, {data: CredentialUserLoginRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  credentialUserControllerLogin(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CredentialUserControllerLoginMutationResult = NonNullable<Awaited<ReturnType<typeof credentialUserControllerLogin>>>
    export type CredentialUserControllerLoginMutationBody = CredentialUserLoginRequestDto
    export type CredentialUserControllerLoginMutationError = ErrorResponseDto

    /**
 * @summary Login (로그인)
 */
export const useCredentialUserControllerLogin = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof credentialUserControllerLogin>>, TError,{data: CredentialUserLoginRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof credentialUserControllerLogin>>,
        TError,
        {data: CredentialUserLoginRequestDto},
        TContext
      > => {

      const mutationOptions = getCredentialUserControllerLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * 현재 세션 종료. 인증 상태와 관계없이 항상 성공 응답을 반환합니다.
 * @summary Logout (로그아웃)
 */
export const credentialUserControllerLogout = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CredentialUserControllerLogout200>(
      {url: `/auth/logout`, method: 'POST', signal
    },
      options);
    }
  


export const getCredentialUserControllerLogoutMutationOptions = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof credentialUserControllerLogout>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof credentialUserControllerLogout>>, TError,void, TContext> => {

const mutationKey = ['credentialUserControllerLogout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof credentialUserControllerLogout>>, void> = () => {
          

          return  credentialUserControllerLogout(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CredentialUserControllerLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof credentialUserControllerLogout>>>
    
    export type CredentialUserControllerLogoutMutationError = ErrorResponseDto

    /**
 * @summary Logout (로그아웃)
 */
export const useCredentialUserControllerLogout = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof credentialUserControllerLogout>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof credentialUserControllerLogout>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getCredentialUserControllerLogoutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * 현재 로그인 세션 유효 여부 확인
 * @summary Auth Status (인증 상태)
 */
export const credentialUserControllerCheckStatus = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CredentialUserControllerCheckStatus200>(
      {url: `/auth/status`, method: 'GET', signal
    },
      options);
    }
  



export const getCredentialUserControllerCheckStatusQueryKey = () => {
    return [
    'auth','status'
    ] as const;
    }

    
export const getCredentialUserControllerCheckStatusQueryOptions = <TData = Awaited<ReturnType<typeof credentialUserControllerCheckStatus>>, TError = ErrorResponseDto>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof credentialUserControllerCheckStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getCredentialUserControllerCheckStatusQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof credentialUserControllerCheckStatus>>> = ({ signal }) => credentialUserControllerCheckStatus(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof credentialUserControllerCheckStatus>>, TError, TData> 
}

export type CredentialUserControllerCheckStatusQueryResult = NonNullable<Awaited<ReturnType<typeof credentialUserControllerCheckStatus>>>
export type CredentialUserControllerCheckStatusQueryError = ErrorResponseDto


/**
 * @summary Auth Status (인증 상태)
 */

export function useCredentialUserControllerCheckStatus<TData = Awaited<ReturnType<typeof credentialUserControllerCheckStatus>>, TError = ErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof credentialUserControllerCheckStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCredentialUserControllerCheckStatusQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




/**
 * 로그인한 사용자가 현재 비밀번호를 알고 있는 상태에서 비밀번호를 변경합니다.
 * @summary Change Password / 비밀번호 변경
 */
export const credentialUserControllerChangePassword = (
    changePasswordRequestDto: MaybeRef<ChangePasswordRequestDto>,
 options?: SecondParameter<typeof customInstance>,) => {
      changePasswordRequestDto = unref(changePasswordRequestDto);
      
      return customInstance<CredentialUserControllerChangePassword200>(
      {url: `/auth/password`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: changePasswordRequestDto
    },
      options);
    }
  


export const getCredentialUserControllerChangePasswordMutationOptions = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof credentialUserControllerChangePassword>>, TError,{data: ChangePasswordRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof credentialUserControllerChangePassword>>, TError,{data: ChangePasswordRequestDto}, TContext> => {

const mutationKey = ['credentialUserControllerChangePassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof credentialUserControllerChangePassword>>, {data: ChangePasswordRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  credentialUserControllerChangePassword(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CredentialUserControllerChangePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof credentialUserControllerChangePassword>>>
    export type CredentialUserControllerChangePasswordMutationBody = ChangePasswordRequestDto
    export type CredentialUserControllerChangePasswordMutationError = ErrorResponseDto

    /**
 * @summary Change Password / 비밀번호 변경
 */
export const useCredentialUserControllerChangePassword = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof credentialUserControllerChangePassword>>, TError,{data: ChangePasswordRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof credentialUserControllerChangePassword>>,
        TError,
        {data: ChangePasswordRequestDto},
        TContext
      > => {

      const mutationOptions = getCredentialUserControllerChangePasswordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * 비밀번호를 잊은 경우 이메일로 재설정 토큰을 발송합니다.
 * @summary Request Password Reset / 비밀번호 재설정 요청
 */
export const credentialUserControllerRequestPasswordReset = (
    requestPasswordResetRequestDto: MaybeRef<RequestPasswordResetRequestDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      requestPasswordResetRequestDto = unref(requestPasswordResetRequestDto);
      
      return customInstance<CredentialUserControllerRequestPasswordReset200>(
      {url: `/auth/password/reset-request`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: requestPasswordResetRequestDto, signal
    },
      options);
    }
  


export const getCredentialUserControllerRequestPasswordResetMutationOptions = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof credentialUserControllerRequestPasswordReset>>, TError,{data: RequestPasswordResetRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof credentialUserControllerRequestPasswordReset>>, TError,{data: RequestPasswordResetRequestDto}, TContext> => {

const mutationKey = ['credentialUserControllerRequestPasswordReset'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof credentialUserControllerRequestPasswordReset>>, {data: RequestPasswordResetRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  credentialUserControllerRequestPasswordReset(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CredentialUserControllerRequestPasswordResetMutationResult = NonNullable<Awaited<ReturnType<typeof credentialUserControllerRequestPasswordReset>>>
    export type CredentialUserControllerRequestPasswordResetMutationBody = RequestPasswordResetRequestDto
    export type CredentialUserControllerRequestPasswordResetMutationError = ErrorResponseDto

    /**
 * @summary Request Password Reset / 비밀번호 재설정 요청
 */
export const useCredentialUserControllerRequestPasswordReset = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof credentialUserControllerRequestPasswordReset>>, TError,{data: RequestPasswordResetRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof credentialUserControllerRequestPasswordReset>>,
        TError,
        {data: RequestPasswordResetRequestDto},
        TContext
      > => {

      const mutationOptions = getCredentialUserControllerRequestPasswordResetMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * 이메일로 받은 토큰을 사용하여 비밀번호를 재설정합니다.
 * @summary Reset Password / 비밀번호 재설정
 */
export const credentialUserControllerResetPassword = (
    resetPasswordRequestDto: MaybeRef<ResetPasswordRequestDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      resetPasswordRequestDto = unref(resetPasswordRequestDto);
      
      return customInstance<CredentialUserControllerResetPassword200>(
      {url: `/auth/password/reset`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: resetPasswordRequestDto, signal
    },
      options);
    }
  


export const getCredentialUserControllerResetPasswordMutationOptions = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof credentialUserControllerResetPassword>>, TError,{data: ResetPasswordRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof credentialUserControllerResetPassword>>, TError,{data: ResetPasswordRequestDto}, TContext> => {

const mutationKey = ['credentialUserControllerResetPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof credentialUserControllerResetPassword>>, {data: ResetPasswordRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  credentialUserControllerResetPassword(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CredentialUserControllerResetPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof credentialUserControllerResetPassword>>>
    export type CredentialUserControllerResetPasswordMutationBody = ResetPasswordRequestDto
    export type CredentialUserControllerResetPasswordMutationError = ErrorResponseDto

    /**
 * @summary Reset Password / 비밀번호 재설정
 */
export const useCredentialUserControllerResetPassword = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof credentialUserControllerResetPassword>>, TError,{data: ResetPasswordRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof credentialUserControllerResetPassword>>,
        TError,
        {data: ResetPasswordRequestDto},
        TContext
      > => {

      const mutationOptions = getCredentialUserControllerResetPasswordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Creates a new user account with email and password. (이메일과 비밀번호로 새로운 사용자 계정을 생성합니다.)
 * @summary Register (회원가입)
 */
export const registrationControllerRegister = (
    registerRequestDto: MaybeRef<RegisterRequestDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      registerRequestDto = unref(registerRequestDto);
      
      return customInstance<RegistrationControllerRegister201>(
      {url: `/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerRequestDto, signal
    },
      options);
    }
  


export const getRegistrationControllerRegisterMutationOptions = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registrationControllerRegister>>, TError,{data: RegisterRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof registrationControllerRegister>>, TError,{data: RegisterRequestDto}, TContext> => {

const mutationKey = ['registrationControllerRegister'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registrationControllerRegister>>, {data: RegisterRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  registrationControllerRegister(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RegistrationControllerRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof registrationControllerRegister>>>
    export type RegistrationControllerRegisterMutationBody = RegisterRequestDto
    export type RegistrationControllerRegisterMutationError = ErrorResponseDto

    /**
 * @summary Register (회원가입)
 */
export const useRegistrationControllerRegister = <TError = ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registrationControllerRegister>>, TError,{data: RegisterRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof registrationControllerRegister>>,
        TError,
        {data: RegisterRequestDto},
        TContext
      > => {

      const mutationOptions = getRegistrationControllerRegisterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    