/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  ErrorResponseDto,
  UserAdminControllerListUsers200,
  UserAdminControllerListUsersParams
} from '../../models';

import { customInstance } from '../../axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 관리자가 등록된 사용자 목록을 조회합니다. 페이징, 필터링, 정렬 기능을 지원합니다.
 * @summary Get user list / 사용자 목록 조회 (관리자용)
 */
export const userAdminControllerListUsers = (
    params?: MaybeRef<UserAdminControllerListUsersParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = unref(params);
      
      return customInstance<UserAdminControllerListUsers200>(
      {url: `/admin/users`, method: 'GET',
        params: unref(params), signal
    },
      options);
    }
  



export const getUserAdminControllerListUsersQueryKey = (params?: MaybeRef<UserAdminControllerListUsersParams>,) => {
    return [
    'admin','users', ...(params ? [params]: [])
    ] as const;
    }

    
export const getUserAdminControllerListUsersQueryOptions = <TData = Awaited<ReturnType<typeof userAdminControllerListUsers>>, TError = ErrorResponseDto>(params?: MaybeRef<UserAdminControllerListUsersParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userAdminControllerListUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getUserAdminControllerListUsersQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof userAdminControllerListUsers>>> = ({ signal }) => userAdminControllerListUsers(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof userAdminControllerListUsers>>, TError, TData> 
}

export type UserAdminControllerListUsersQueryResult = NonNullable<Awaited<ReturnType<typeof userAdminControllerListUsers>>>
export type UserAdminControllerListUsersQueryError = ErrorResponseDto


/**
 * @summary Get user list / 사용자 목록 조회 (관리자용)
 */

export function useUserAdminControllerListUsers<TData = Awaited<ReturnType<typeof userAdminControllerListUsers>>, TError = ErrorResponseDto>(
 params?: MaybeRef<UserAdminControllerListUsersParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userAdminControllerListUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUserAdminControllerListUsersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




