export const COMP_REPOSITORY = Symbol('COMP_REPOSITORY');
export const COMP_CONFIG_REPOSITORY = Symbol('COMP_CONFIG_REPOSITORY');
export const COMP_DAILY_SETTLEMENT_REPOSITORY = Symbol(
  'COMP_DAILY_SETTLEMENT_REPOSITORY',
);
