export const COMP_REPOSITORY = Symbol('COMP_REPOSITORY');
export const COMP_CONFIG_REPOSITORY = Symbol('COMP_CONFIG_REPOSITORY');
export const COMP_CLAIM_HISTORY_REPOSITORY = Symbol(
  'COMP_CLAIM_HISTORY_REPOSITORY',
);
