
import mjml2html from 'mjml';
import * as fs from 'fs';
import * as path from 'path';

const MJML_DIR = path.join(__dirname, '../src/modules/notification/template/infrastructure/renderers/mjml');
const OUTPUT_FILE = path.join(__dirname, '../src/modules/notification/template/infrastructure/renderers/layouts/email-layouts.ts');

async function compileMjml() {
    console.log('Compiling MJML templates...');

    if (!fs.existsSync(MJML_DIR)) {
        console.error(`MJML directory not found: ${MJML_DIR}`);
        process.exit(1);
    }

    const files = fs.readdirSync(MJML_DIR).filter(file => file.endsWith('.mjml'));
    const layouts: Record<string, string> = {};

    for (const file of files) {
        const templateName = path.parse(file).name; // default, promotion
        const filePath = path.join(MJML_DIR, file);
        const mjmlContent = fs.readFileSync(filePath, 'utf-8');

        try {
            console.log(`Compiling ${file}...`);
            // mjml2html options: minify for production
            const result = mjml2html(mjmlContent, {
                minify: true,
                keepComments: false,
                validationLevel: 'soft', // Handlebars syntax might trigger warnings
            });

            if (result.errors.length > 0) {
                console.warn(`Warnings in ${file}:`, result.errors);
            }

            layouts[templateName] = result.html;
        } catch (error) {
            console.error(`Error compiling ${file}:`, error);
        }
    }

    // Generate TypeScript file
    const tsContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * This file is generated by scripts/generate-email-layouts.ts
 * Edit the .mjml files in ../mjml/ instead.
 */

export const EmailLayouts = ${JSON.stringify(layouts, null, 4)};
`;

    fs.writeFileSync(OUTPUT_FILE, tsContent);
    console.log(`Successfully generated ${Object.keys(layouts).length} layouts to ${OUTPUT_FILE}`);
}

compileMjml();
