export enum UpdateOperation {
  ADD = 'ADD',
  SUBTRACT = 'SUBTRACT',
}

export const WalletActionName = {
  // 입금 관련
  APPROVE_DEPOSIT: 'APPROVE_DEPOSIT',

  // 출금 관련
  REQUEST_WITHDRAWAL: 'REQUEST_WITHDRAWAL',
  REJECT_WITHDRAWAL: 'REJECT_WITHDRAWAL',
  CANCEL_WITHDRAWAL: 'CANCEL_WITHDRAWAL',
  RESTORE_BALANCE_ON_FAILURE: 'RESTORE_BALANCE_ON_FAILURE',

  // 프로모션/보너스 관련
  GRANT_PROMOTION_BONUS: 'GRANT_PROMOTION_BONUS',
  APPLY_COUPON_PROMOTION: 'APPLY_COUPON_PROMOTION',
  CLAIM_COMP: 'CLAIM_COMP',
  CLAIM_TIER_REWARD: 'CLAIM_TIER_REWARD',

  // 카지노 관련
  CASINO_BET: 'CASINO_BET',
  CASINO_WIN: 'CASINO_WIN',
  CASINO_REFUND: 'CASINO_REFUND',
  CASINO_BET_CASH: 'CASINO_BET_CASH',
  CASINO_BET_BONUS: 'CASINO_BET_BONUS',
  CASINO_WIN_CASH: 'CASINO_WIN_CASH',
  CASINO_WIN_BONUS: 'CASINO_WIN_BONUS',
  CASINO_REFUND_CASH: 'CASINO_REFUND_CASH',
  CASINO_REFUND_BONUS: 'CASINO_REFUND_BONUS',
  CASINO_JACKPOT: 'CASINO_JACKPOT',
  CASINO_BONUS: 'CASINO_BONUS',

  // 시스템/기타
  ADMIN_ADJUSTMENT: 'ADMIN_ADJUSTMENT',
  ADMIN_MANUAL_ADJUSTMENT: 'ADMIN_MANUAL_ADJUSTMENT',
  VAULT_OPERATION: 'VAULT_OPERATION',
} as const;

export type WalletActionName =
  (typeof WalletActionName)[keyof typeof WalletActionName];
