import { Injectable, Inject, Logger, HttpStatus } from '@nestjs/common';
import { Transactional } from '@nestjs-cls/transactional';
import { USER_REPOSITORY } from 'src/modules/user/ports/out/user.repository.token';
import type { UserRepositoryPort } from 'src/modules/user/ports/out/user.repository.port';
import { hashPassword } from 'src/utils/password.util';
import { ACTIVITY_LOG } from 'src/common/activity-log/activity-log.token';
import type { ActivityLogPort } from 'src/common/activity-log/activity-log.port';
import { ActivityType } from 'src/common/activity-log/activity-log.types';
import type { RequestClientInfo } from 'src/common/http/types/client-info.types';
import { ApiException } from 'src/common/http/exception/api.exception';
import { MessageCode } from 'src/common/http/types';
import { nanoid } from 'nanoid';

export interface ResetUserPasswordAdminParams {
  targetUserId: bigint;
  adminUserId: bigint;
  newPassword?: string; // 선택사항, 미제공 시 자동 생성
  requestInfo: RequestClientInfo;
}

export interface ResetUserPasswordAdminResult {
  newPassword: string; // 생성된 비밀번호
}

/**
 * 관리자용 사용자 비밀번호 초기화 Use Case
 *
 * 관리자가 특정 사용자의 비밀번호를 초기화합니다.
 * 새 비밀번호를 제공하지 않으면 자동으로 생성합니다.
 */
@Injectable()
export class ResetUserPasswordAdminService {
  private readonly logger = new Logger(ResetUserPasswordAdminService.name);

  constructor(
    @Inject(USER_REPOSITORY)
    private readonly userRepository: UserRepositoryPort,
    @Inject(ACTIVITY_LOG)
    private readonly activityLog: ActivityLogPort,
  ) {}

  @Transactional()
  async execute(
    params: ResetUserPasswordAdminParams,
  ): Promise<ResetUserPasswordAdminResult> {
    const { targetUserId, adminUserId, newPassword, requestInfo } = params;

    // 1. 대상 사용자 조회
    const targetUser = await this.userRepository.findById(targetUserId);
    if (!targetUser) {
      throw new ApiException(
        MessageCode.USER_NOT_FOUND,
        HttpStatus.NOT_FOUND,
      );
    }

    // 2. 일반 회원가입 사용자인지 확인
    if (!targetUser.isCredentialUser()) {
      throw new ApiException(
        MessageCode.AUTH_INVALID_CREDENTIALS,
        HttpStatus.BAD_REQUEST,
      );
    }

    // 3. 새 비밀번호 생성 또는 사용
    const finalPassword = newPassword || this.generateRandomPassword();

    // 4. 비밀번호 해싱
    const passwordHash = await hashPassword(finalPassword);

    // 5. 비밀번호 업데이트
    await this.userRepository.updatePassword(targetUserId, passwordHash);

    // 6. Activity Log 기록
    try {
      await this.activityLog.logSuccess(
        {
          userId: adminUserId,
          activityType: ActivityType.PASSWORD_RESET,
          description: `관리자가 사용자 비밀번호 초기화 - 대상 사용자: ${targetUser.email}`,
          metadata: {
            targetUserId: targetUserId.toString(),
            targetUserEmail: targetUser.email,
            isAutoGenerated: !newPassword,
          },
        },
        requestInfo,
      );
    } catch (error) {
      // Activity Log 실패는 비밀번호 초기화 성공에 영향을 주지 않도록 처리
      this.logger.error(
        error,
        `Activity log 기록 실패 (비밀번호 초기화는 성공) - targetUserId: ${targetUserId}, adminUserId: ${adminUserId}`,
      );
    }

    return {
      newPassword: finalPassword,
    };
  }

  /**
   * 랜덤 비밀번호 생성
   * 12자리, 대문자, 소문자, 숫자 포함
   */
  private generateRandomPassword(): string {
    // nanoid를 사용하여 안전한 랜덤 문자열 생성
    // 대문자, 소문자, 숫자 포함
    const uppercase = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    const lowercase = 'abcdefghijklmnopqrstuvwxyz';
    const numbers = '0123456789';
    const allChars = uppercase + lowercase + numbers;

    // nanoid로 기본 문자열 생성 (10자)
    let password = nanoid(10);

    // 최소 1개의 대문자, 소문자, 숫자 포함 보장
    const randomUpper = uppercase[Math.floor(Math.random() * uppercase.length)];
    const randomLower = lowercase[Math.floor(Math.random() * lowercase.length)];
    const randomNumber = numbers[Math.floor(Math.random() * numbers.length)];

    // 랜덤 위치에 삽입
    const chars = password.split('');
    chars[0] = randomUpper;
    chars[1] = randomLower;
    chars[2] = randomNumber;

    // 나머지 문자는 랜덤하게 채움
    for (let i = 3; i < chars.length; i++) {
      chars[i] = allChars[Math.floor(Math.random() * allChars.length)];
    }

    // 셔플
    for (let i = chars.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [chars[i], chars[j]] = [chars[j], chars[i]];
    }

    return chars.join('');
  }
}

