/**
 * 카지노 모듈 공통 에러 코드
 */
export enum CasinoErrorCode {
  // 파라미터 누락 관련
  PARAMETER_MISSING = 'PARAMETER_MISSING',
  USER_BALANCE_NOT_FOUND = 'USER_BALANCE_NOT_FOUND',

  // 인증/권한
  ACCESS_DENIED = 'ACCESS_DENIED',

  // 사용자 관련
  INVALID_USER = 'INVALID_USER',

  // 금액/거래 관련
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
  INVALID_TXN = 'INVALID_TXN',
  BET_ALREADY_CANCELLED = 'BET_ALREADY_CANCELLED',

  // 중복 관련
  DUPLICATE_DEBIT = 'DUPLICATE_DEBIT',
  DUPLICATE_CREDIT = 'DUPLICATE_CREDIT',
  BONUS_ALREADY_PROCESSED = 'BONUS_ALREADY_PROCESSED',

  // 제품/게임 관련
  INVALID_PRODUCT = 'INVALID_PRODUCT',

  // 시스템 에러
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
