/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */
import type { CommissionRateResponseDtoTier } from './commissionRateResponseDtoTier';

export interface CommissionRateResponseDto {
  /** 티어 */
  tier: CommissionRateResponseDtoTier;
  /** 기본 요율 */
  baseRate: string;
  /**
   * 수동 설정 요율
   * @nullable
   */
  customRate: string | null;
  /** 수동 요율 사용 여부 */
  isCustomRate: boolean;
  /** 실제 적용되는 요율 */
  effectiveRate: string;
}
