/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */
import type { ApiResponseDto } from './apiResponseDto';
import type { CredentialAdminControllerLogin200AllOf } from './credentialAdminControllerLogin200AllOf';

export type CredentialAdminControllerLogin200 = ApiResponseDto & CredentialAdminControllerLogin200AllOf;
