/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */
import type { ChangePasswordResponseDto } from './changePasswordResponseDto';

export type CredentialUserControllerChangePassword200AllOf = {
  data?: ChangePasswordResponseDto;
};
