/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * Error code if bonus processing failed
 */
export type GetBonusResponseDtoError = typeof GetBonusResponseDtoError[keyof typeof GetBonusResponseDtoError];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetBonusResponseDtoError = {
  INVALID_USER: 'INVALID_USER',
  ACCESS_DENIED: 'ACCESS_DENIED',
  INVALID_TXN: 'INVALID_TXN',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_PRODUCT: 'INVALID_PRODUCT',
  DUPLICATE_BONUS: 'DUPLICATE_BONUS',
} as const;
