/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */

export interface GetWhitecliffBalanceRequestDto {
  /** User ID of WHITECLIFF (화이트클리프 사용자 ID) */
  user_id: number;
  /** Product's ID (상품 ID). 
    This field can be IGNORED if the integrator does not have a separate wallet. (통합사가 별도의 지갑이 없는 경우 이 필드는 무시해도 됩니다.) */
  prd_id?: number;
  /** Session ID (세션 ID) */
  sid?: string;
}
