/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */

export interface ResetPasswordRequestDto {
  /** 비밀번호 재설정 토큰 */
  token: string;
  /** 새 비밀번호 */
  newPassword: string;
}
