/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */
import type { PaginatedResponseDto } from './paginatedResponseDto';
import type { SessionAdminControllerListSessions200AllOf } from './sessionAdminControllerListSessions200AllOf';

export type SessionAdminControllerListSessions200 = PaginatedResponseDto & SessionAdminControllerListSessions200AllOf;
