/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */
import type { SessionAdminControllerListSessionsSortBy } from './sessionAdminControllerListSessionsSortBy';
import type { SessionAdminControllerListSessionsSortOrder } from './sessionAdminControllerListSessionsSortOrder';
import type { SessionAdminControllerListSessionsStatus } from './sessionAdminControllerListSessionsStatus';
import type { SessionAdminControllerListSessionsType } from './sessionAdminControllerListSessionsType';

export type SessionAdminControllerListSessionsParams = {
/**
 * 페이지 번호 (기본값: 1)
 * @minimum 1
 */
page?: number;
/**
 * 페이지당 항목 수 (기본값: 20, 최대: 100)
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * 정렬 필드
 */
sortBy?: SessionAdminControllerListSessionsSortBy;
/**
 * 정렬 방향 (asc, desc)
 */
sortOrder?: SessionAdminControllerListSessionsSortOrder;
/**
 * 사용자 ID 필터
 */
userId?: string;
/**
 * 세션 상태 필터
 */
status?: SessionAdminControllerListSessionsStatus;
/**
 * 세션 타입 필터
 */
type?: SessionAdminControllerListSessionsType;
/**
 * 활성 세션만 조회할지 여부 (기본값: false)
 */
activeOnly?: boolean;
/**
 * 시작 날짜 (ISO 8601 형식) - 생성일 기준
 */
startDate?: string;
/**
 * 종료 날짜 (ISO 8601 형식) - 생성일 기준
 */
endDate?: string;
};
