/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */

export interface SetCustomRateDto {
  /** 어필리에이트 ID */
  affiliateId: number;
  /**
   * 설정할 커미션 요율 (0.01 = 1%, 최대 1.0 = 100%)
   * @pattern ^0(\.\d{1,4})?$|^1(\.0{1,4})?$
   */
  customRate: string;
}
