/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */
import type { UserBalanceItemDto } from './userBalanceItemDto';

export interface UserBalanceResponseDto {
  /** 사용자 잔액 정보 */
  wallets: UserBalanceItemDto[];
}
