/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */

export interface VipLevelResponseDto {
  /** VIP 레벨 ID */
  id: number;
  /** 다국어 키 */
  nameKey: string;
  /** 레벨 순위 */
  rank: number;
  /** 필요 롤링 */
  requiredRolling: number;
  /** 레벨업 보너스 */
  levelUpBonus: number;
  /** 콤프 비율 */
  compRate: number;
}
