/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */
import type { WhitecliffTestControllerGetProductGameListBodyGameCurrency } from './whitecliffTestControllerGetProductGameListBodyGameCurrency';
import type { WhitecliffTestControllerGetProductGameListBodyLanguage } from './whitecliffTestControllerGetProductGameListBodyLanguage';

export type WhitecliffTestControllerGetProductGameListBody = {
  /** 통화 */
  gameCurrency?: WhitecliffTestControllerGetProductGameListBodyGameCurrency;
  /** 언어 */
  language: WhitecliffTestControllerGetProductGameListBodyLanguage;
  /** 게임 상품 ID (선택사항) */
  prd_id?: number;
};
