/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */
import type { WithdrawCommissionDtoCurrency } from './withdrawCommissionDtoCurrency';

export interface WithdrawCommissionDto {
  /** 출금할 통화 */
  currency: WithdrawCommissionDtoCurrency;
  /**
   * 출금할 금액 (소수점 포함 가능, 예: "100.50")
   * @pattern ^\d+(\.\d{1,2})?$
   */
  amount: string;
}
