/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DPC Backend API
 * DPC Backend API 문서
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/vue-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationReturnType
} from '@tanstack/vue-query';

import {
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  AppendWagerRequestDto,
  AppendWagerResponseDto,
  CancelWagerRequestDto,
  CancelWagerResponseDto,
  DcsLoginResponseDto,
  EndWagerRequestDto,
  EndWagerResponseDto,
  FreeSpinResultRequestDto,
  FreeSpinResultResponseDto,
  GetDcsBalanceRequestDto,
  GetDcsBalanceResponseDto,
  LoginRequestDto,
  PromoPayoutRequestDto,
  PromoPayoutResponseDto,
  WagerRequestDto,
  WagerResponseDto
} from '../../models';

import { customInstance } from '../../axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary 로그인 콜백
 */
export const dcsCallbackControllerLogin = (
    loginRequestDto: MaybeRef<LoginRequestDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      loginRequestDto = unref(loginRequestDto);
      
      return customInstance<DcsLoginResponseDto>(
      {url: `/dopaminedev/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequestDto, signal
    },
      options);
    }
  


export const getDcsCallbackControllerLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dcsCallbackControllerLogin>>, TError,{data: LoginRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof dcsCallbackControllerLogin>>, TError,{data: LoginRequestDto}, TContext> => {

const mutationKey = ['dcsCallbackControllerLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dcsCallbackControllerLogin>>, {data: LoginRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  dcsCallbackControllerLogin(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DcsCallbackControllerLoginMutationResult = NonNullable<Awaited<ReturnType<typeof dcsCallbackControllerLogin>>>
    export type DcsCallbackControllerLoginMutationBody = LoginRequestDto
    export type DcsCallbackControllerLoginMutationError = unknown

    /**
 * @summary 로그인 콜백
 */
export const useDcsCallbackControllerLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dcsCallbackControllerLogin>>, TError,{data: LoginRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof dcsCallbackControllerLogin>>,
        TError,
        {data: LoginRequestDto},
        TContext
      > => {

      const mutationOptions = getDcsCallbackControllerLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary 베팅 콜백
 */
export const dcsCallbackControllerWager = (
    wagerRequestDto: MaybeRef<WagerRequestDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      wagerRequestDto = unref(wagerRequestDto);
      
      return customInstance<WagerResponseDto>(
      {url: `/dopaminedev/wager`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: wagerRequestDto, signal
    },
      options);
    }
  


export const getDcsCallbackControllerWagerMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dcsCallbackControllerWager>>, TError,{data: WagerRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof dcsCallbackControllerWager>>, TError,{data: WagerRequestDto}, TContext> => {

const mutationKey = ['dcsCallbackControllerWager'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dcsCallbackControllerWager>>, {data: WagerRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  dcsCallbackControllerWager(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DcsCallbackControllerWagerMutationResult = NonNullable<Awaited<ReturnType<typeof dcsCallbackControllerWager>>>
    export type DcsCallbackControllerWagerMutationBody = WagerRequestDto
    export type DcsCallbackControllerWagerMutationError = unknown

    /**
 * @summary 베팅 콜백
 */
export const useDcsCallbackControllerWager = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dcsCallbackControllerWager>>, TError,{data: WagerRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof dcsCallbackControllerWager>>,
        TError,
        {data: WagerRequestDto},
        TContext
      > => {

      const mutationOptions = getDcsCallbackControllerWagerMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary 베팅 취소 콜백
 */
export const dcsCallbackControllerCancelWager = (
    cancelWagerRequestDto: MaybeRef<CancelWagerRequestDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      cancelWagerRequestDto = unref(cancelWagerRequestDto);
      
      return customInstance<CancelWagerResponseDto>(
      {url: `/dopaminedev/cancelWager`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: cancelWagerRequestDto, signal
    },
      options);
    }
  


export const getDcsCallbackControllerCancelWagerMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dcsCallbackControllerCancelWager>>, TError,{data: CancelWagerRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof dcsCallbackControllerCancelWager>>, TError,{data: CancelWagerRequestDto}, TContext> => {

const mutationKey = ['dcsCallbackControllerCancelWager'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dcsCallbackControllerCancelWager>>, {data: CancelWagerRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  dcsCallbackControllerCancelWager(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DcsCallbackControllerCancelWagerMutationResult = NonNullable<Awaited<ReturnType<typeof dcsCallbackControllerCancelWager>>>
    export type DcsCallbackControllerCancelWagerMutationBody = CancelWagerRequestDto
    export type DcsCallbackControllerCancelWagerMutationError = unknown

    /**
 * @summary 베팅 취소 콜백
 */
export const useDcsCallbackControllerCancelWager = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dcsCallbackControllerCancelWager>>, TError,{data: CancelWagerRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof dcsCallbackControllerCancelWager>>,
        TError,
        {data: CancelWagerRequestDto},
        TContext
      > => {

      const mutationOptions = getDcsCallbackControllerCancelWagerMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary 추가 베팅 콜백
 */
export const dcsCallbackControllerAppendWager = (
    appendWagerRequestDto: MaybeRef<AppendWagerRequestDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      appendWagerRequestDto = unref(appendWagerRequestDto);
      
      return customInstance<AppendWagerResponseDto>(
      {url: `/dopaminedev/appendWager`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: appendWagerRequestDto, signal
    },
      options);
    }
  


export const getDcsCallbackControllerAppendWagerMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dcsCallbackControllerAppendWager>>, TError,{data: AppendWagerRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof dcsCallbackControllerAppendWager>>, TError,{data: AppendWagerRequestDto}, TContext> => {

const mutationKey = ['dcsCallbackControllerAppendWager'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dcsCallbackControllerAppendWager>>, {data: AppendWagerRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  dcsCallbackControllerAppendWager(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DcsCallbackControllerAppendWagerMutationResult = NonNullable<Awaited<ReturnType<typeof dcsCallbackControllerAppendWager>>>
    export type DcsCallbackControllerAppendWagerMutationBody = AppendWagerRequestDto
    export type DcsCallbackControllerAppendWagerMutationError = unknown

    /**
 * @summary 추가 베팅 콜백
 */
export const useDcsCallbackControllerAppendWager = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dcsCallbackControllerAppendWager>>, TError,{data: AppendWagerRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof dcsCallbackControllerAppendWager>>,
        TError,
        {data: AppendWagerRequestDto},
        TContext
      > => {

      const mutationOptions = getDcsCallbackControllerAppendWagerMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary 베팅 종료 및 지급 콜백
 */
export const dcsCallbackControllerEndWager = (
    endWagerRequestDto: MaybeRef<EndWagerRequestDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      endWagerRequestDto = unref(endWagerRequestDto);
      
      return customInstance<EndWagerResponseDto>(
      {url: `/dopaminedev/endWager`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: endWagerRequestDto, signal
    },
      options);
    }
  


export const getDcsCallbackControllerEndWagerMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dcsCallbackControllerEndWager>>, TError,{data: EndWagerRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof dcsCallbackControllerEndWager>>, TError,{data: EndWagerRequestDto}, TContext> => {

const mutationKey = ['dcsCallbackControllerEndWager'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dcsCallbackControllerEndWager>>, {data: EndWagerRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  dcsCallbackControllerEndWager(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DcsCallbackControllerEndWagerMutationResult = NonNullable<Awaited<ReturnType<typeof dcsCallbackControllerEndWager>>>
    export type DcsCallbackControllerEndWagerMutationBody = EndWagerRequestDto
    export type DcsCallbackControllerEndWagerMutationError = unknown

    /**
 * @summary 베팅 종료 및 지급 콜백
 */
export const useDcsCallbackControllerEndWager = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dcsCallbackControllerEndWager>>, TError,{data: EndWagerRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof dcsCallbackControllerEndWager>>,
        TError,
        {data: EndWagerRequestDto},
        TContext
      > => {

      const mutationOptions = getDcsCallbackControllerEndWagerMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary 무료 스핀 결과 콜백
 */
export const dcsCallbackControllerFreeSpinResult = (
    freeSpinResultRequestDto: MaybeRef<FreeSpinResultRequestDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      freeSpinResultRequestDto = unref(freeSpinResultRequestDto);
      
      return customInstance<FreeSpinResultResponseDto>(
      {url: `/dopaminedev/freeSpinResult`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: freeSpinResultRequestDto, signal
    },
      options);
    }
  


export const getDcsCallbackControllerFreeSpinResultMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dcsCallbackControllerFreeSpinResult>>, TError,{data: FreeSpinResultRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof dcsCallbackControllerFreeSpinResult>>, TError,{data: FreeSpinResultRequestDto}, TContext> => {

const mutationKey = ['dcsCallbackControllerFreeSpinResult'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dcsCallbackControllerFreeSpinResult>>, {data: FreeSpinResultRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  dcsCallbackControllerFreeSpinResult(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DcsCallbackControllerFreeSpinResultMutationResult = NonNullable<Awaited<ReturnType<typeof dcsCallbackControllerFreeSpinResult>>>
    export type DcsCallbackControllerFreeSpinResultMutationBody = FreeSpinResultRequestDto
    export type DcsCallbackControllerFreeSpinResultMutationError = unknown

    /**
 * @summary 무료 스핀 결과 콜백
 */
export const useDcsCallbackControllerFreeSpinResult = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dcsCallbackControllerFreeSpinResult>>, TError,{data: FreeSpinResultRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof dcsCallbackControllerFreeSpinResult>>,
        TError,
        {data: FreeSpinResultRequestDto},
        TContext
      > => {

      const mutationOptions = getDcsCallbackControllerFreeSpinResultMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary 잔액 조회 콜백
 */
export const dcsCallbackControllerGetBalance = (
    getDcsBalanceRequestDto: MaybeRef<GetDcsBalanceRequestDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      getDcsBalanceRequestDto = unref(getDcsBalanceRequestDto);
      
      return customInstance<GetDcsBalanceResponseDto>(
      {url: `/dopaminedev/getBalance`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getDcsBalanceRequestDto, signal
    },
      options);
    }
  


export const getDcsCallbackControllerGetBalanceMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dcsCallbackControllerGetBalance>>, TError,{data: GetDcsBalanceRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof dcsCallbackControllerGetBalance>>, TError,{data: GetDcsBalanceRequestDto}, TContext> => {

const mutationKey = ['dcsCallbackControllerGetBalance'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dcsCallbackControllerGetBalance>>, {data: GetDcsBalanceRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  dcsCallbackControllerGetBalance(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DcsCallbackControllerGetBalanceMutationResult = NonNullable<Awaited<ReturnType<typeof dcsCallbackControllerGetBalance>>>
    export type DcsCallbackControllerGetBalanceMutationBody = GetDcsBalanceRequestDto
    export type DcsCallbackControllerGetBalanceMutationError = unknown

    /**
 * @summary 잔액 조회 콜백
 */
export const useDcsCallbackControllerGetBalance = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dcsCallbackControllerGetBalance>>, TError,{data: GetDcsBalanceRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof dcsCallbackControllerGetBalance>>,
        TError,
        {data: GetDcsBalanceRequestDto},
        TContext
      > => {

      const mutationOptions = getDcsCallbackControllerGetBalanceMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary 프로모션 지급 콜백
 */
export const dcsCallbackControllerPromoPayout = (
    promoPayoutRequestDto: MaybeRef<PromoPayoutRequestDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      promoPayoutRequestDto = unref(promoPayoutRequestDto);
      
      return customInstance<PromoPayoutResponseDto>(
      {url: `/dopaminedev/promoPayout`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: promoPayoutRequestDto, signal
    },
      options);
    }
  


export const getDcsCallbackControllerPromoPayoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dcsCallbackControllerPromoPayout>>, TError,{data: PromoPayoutRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof dcsCallbackControllerPromoPayout>>, TError,{data: PromoPayoutRequestDto}, TContext> => {

const mutationKey = ['dcsCallbackControllerPromoPayout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dcsCallbackControllerPromoPayout>>, {data: PromoPayoutRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  dcsCallbackControllerPromoPayout(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DcsCallbackControllerPromoPayoutMutationResult = NonNullable<Awaited<ReturnType<typeof dcsCallbackControllerPromoPayout>>>
    export type DcsCallbackControllerPromoPayoutMutationBody = PromoPayoutRequestDto
    export type DcsCallbackControllerPromoPayoutMutationError = unknown

    /**
 * @summary 프로모션 지급 콜백
 */
export const useDcsCallbackControllerPromoPayout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dcsCallbackControllerPromoPayout>>, TError,{data: PromoPayoutRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof dcsCallbackControllerPromoPayout>>,
        TError,
        {data: PromoPayoutRequestDto},
        TContext
      > => {

      const mutationOptions = getDcsCallbackControllerPromoPayoutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    